indilib/indi

3rdparty/indi-shelyak/CMakeLists.txt, 3rdparty/indi-shelyak/README.md, 3rdparty/indi-shelyak/indi-shelyak.xml, 3rdparty/indi-shelyak/indi_shelyakeshel_spectrograph.cpp, 3rdparty/indi-shelyak/indi_shelyakeshel_spectrograph.h
=> Shelyak eShel driver

3rdparty/CMakeLists.txt, 3rdparty/indi-asi/CMakeLists.txt.user, 3rdparty/indi-asi/README.md
The directory change broke the build of 3rdparty drivers. This should fix it.
=> Follow indi-asicam -> indi-asi in cmake/config/README

libindi/drivers/telescope/lx200pulsar2.cpp, libindi/drivers/telescope/lx200pulsar2.h
Much improved version  of the Pulsar 2 driver. Functional, but still work in progress.
=> New version of Pulsar 2 driver (still beta)

3rdparty/indi-duino/devices/CMakeLists.txt, 3rdparty/indi-duino/devices/servo_sk.xml, 3rdparty/indi-duino/indi_duino.xml.cmake, 3rdparty/indi-duino/indiduino.cpp, 3rdparty/indi-duino/indiduino.h
Added support for servos in Indiduino, with a sample XML skeleton.
=> Servos in Indiduino

macosx/INDI Server/INDI Server-Info.plist, macosx/INDI Server/INDI Server.xcodeproj/project.pbxproj
=> INDI Server for OSX 2.2.16

3rdparty/indi-asi/asi_ccd.cpp
Line 621: change from %d to %.2f
=> Proper format for "SetControlValue" debug message.

3rdparty/indi-duino/devices/focuser_sk.xml, 3rdparty/indi-duino/devices/servo_sk.xml, 3rdparty/indi-duino/indiduino.cpp, 3rdparty/indi-duino/indiduino.h
Added joystick capabilities for servo and analog outputs
Demonstrated the syntax for joystick mappings for servos in servo_sk.xml sample skeleton
Demonstrate the syntax for joystick mappings for analog outputs in focuser_sk.xml skeleton
Corrected some old bugs
Simplified the servo switching : they are now switched with a single "AtMostOne" switch instead of two "OneOfMany"
=> Joystick for Indiduino

libindi/CMakeLists.txt, libindi/drivers.xml, libindi/drivers/focuser/microtouch.cpp, libindi/drivers/focuser/microtouch.h
Comments welcome, first PR ever.
Basic movement, getting Temperature, set TempCallibration, get/set Motorspeed and abort/zero works. Still some work to do.
//ToDo
- TempComp
- Reset to Position
- ...
=> Initial Microtouch driver, based on Moonlite driver

libindi/drivers/focuser/microtouch.cpp, libindi/drivers/focuser/microtouch.h
Added some code to the Microtouch driver to help debugging
=> Debug information for Microtouch Driver

libindi/drivers/focuser/microtouch.cpp
- Bugfix: Correct operation for POS>9999
=> Bugfix: Correct operation for POS>9999

libindi/drivers/focuser/microtouch.cpp, libindi/drivers/focuser/microtouch.h
Added: TempComp and ResetToPosition and minor fixes
=> Added: TempComp and ResetToPosition

3rdparty/indi-gpsd/CMakeLists.txt, 3rdparty/indi-gpsd/config.h.cmake, 3rdparty/indi-gpsd/gps_driver.cpp, 3rdparty/indi-gpsd/indi_gpsd.xml, 3rdparty/indi-gpsd/indi_gpsd.xml.cmake, debian/indi-gpsd/changelog
- Guard against garbage position on no-fix condition
- Improve fix detection logic
- Remove improper string comparison
- Switch towards single sourcing of version info
=> Gpsd function improvements

libindi/indiserver.c
reduces download time of 16Mp fits from nanopi2 with 0.3 seconds per frame.
=>  increase read and write buffers for indiserver - reduces download time

libindi/base64.c, libindi/indidriver.c, libindi/libs/indibase/baseclient.cpp, libindi/libs/indibase/baseclientqt.cpp
but slower! -yet faster than it was
=> resored '\n' - indi is safe and sound :)

3rdparty/indi-ssag/CMakeLists.txt, 3rdparty/indi-ssag/openssag.cpp, 3rdparty/indi-ssag/openssag_loader.cpp, 3rdparty/indi-ssag/ssagccd.cpp
Tested binary with kstars and indiserver command line invocation.
=> indi-ssag can now be built with cmake

libindi/drivers/filter_wheel/ifwoptec.cpp, libindi/drivers/filter_wheel/ifwoptec.h
add only ifwoptec.* to indi/libindi/drivers/filter_wheel as new driver 
Hope this is correct this time, as ou can see I'm not feel confident with github
=> Proposal new filter wheel driver Optec IFW

3rdparty/indi-gphoto/gphoto_driver.cpp
These modifications support the 350D both with and without mirror lock for any shutter speed (bulb and camera presets).
=> Modifications for Canon 350D

3rdparty/indi-asi/asi_wheel.cpp
Yang pointer this out. (however in this case id = index)
=> indi_asi_wheel: small fix in initialization

libindi/drivers/telescope/lx200pulsar2.cpp, libindi/drivers/telescope/lx200pulsar2.h
This modification fix problems with the detection of slewing and parking operations, setting time, date and site coordinates, and the sync-ing of the telescope to specific coordinates. These issues were caused by variable timing of calls to tcflush() and differences in the command format between the LX200 and Pulsar controllers. This version does not support Pulsar2 specific features yet.
=> Modifications in pulsar2

libindi/indiserver.c
This method avoids ignoring SIGCHLD, which propagates to child
processes and prevents forks from being able to detect the end of their
subprocesses. As an example, when indiserver is a system service
launched by openrc, ignoring SIGCHLD in indiserver prevents
astrometry.net from retrieving output from its tools.
=> Adding code to reap zombie processes as they appear.

libindi/CMakeLists.txt, libindi/drivers.xml, libindi/drivers/focuser/usbfocusv3.cpp, libindi/drivers/focuser/usbfocusv3.h
Please find the sources for a new full featured USB_focus_v3 driver, including automatic temperature compensation as well as direction and compensation sign adjustment. The code is still experimental, since up to now it only has been tested at a single USV_focus_v3 sample with firmware 1505.
=> New open source driver for USB_focus_v3

libindi/CMakeLists.txt, libindi/drivers.xml, libindi/drivers/filter_wheel/quantum_wheel.cpp, libindi/drivers/filter_wheel/quantum_wheel.h
I have added new driver for Quantum Electronic Filter Wheel 7 x 1,25" controlled over USB.
=> Quantum Filter Wheel added to libindi core drivers

libindi/drivers/telescope/lx200pulsar2.cpp
Connecting the driver to indiserver should work again.
=> Bug fix in ISGetProperties in lx200pulsar2.cpp

libindi/drivers/telescope/lx200generic.cpp
=> 10Micron driver got renamed to 10micron, so check for that instead

3rdparty/indi-nexstarevo/nexstarevo.cpp, 3rdparty/indi-nexstarevo/nexstarevo.h
Make the driver functional with new connection framework.
Not using the FD from the framework yet - just update to the new structure and make preparation for migrating in the future.
=> Adapt to the new connection framework

libindi/drivers/telescope/skywatcherAPI.cpp, libindi/drivers/telescope/skywatcherAPI.h, libindi/drivers/telescope/skywatcherAPIMount.cpp, libindi/drivers/telescope/skywatcherAPIMount.h
1. Fix the broken handshaking
2. Implemented parking/unparking
3. Final fixes to the mount positioning for Virtuoso mounts
=> New updates for the indi_skywatcherAPIMount driver

3rdparty/indi-gphoto/gphoto_driver.cpp
Added code to explicitly raise and lower RTS line when the serial port is open.
=> Adding explicit RTS Line control

libindi/libs/indibase/indidome.cpp, libindi/libs/indibase/indidome.h
Correction to OpticalCenter and OpticalVector and simplification of
calculus.
=> DomeSync correction

3rdparty/indi-nexstarevo/nexstarevo.cpp
Make the driver work with skysafari middleware driver
=> Change slew mode switch name to same as in telescope_simulator

3rdparty/fliusb/fliusb.c
this is attempt to fix the compilation for 4.8... it will not change the behaviour for other versions
=> fliusb.ko: attempt to fix it for 4.8 kernel

libindi/indiapi.h, libindi/indidriver.c
caption is self explanatory :)
=> indidriver: fix XML escaping for property message

3rdparty/fliusb/fliusb.c
installed VM with kernel 4.8 and it works finally :)
=> fliusb.ko: finally fixed and tested on linux 4.8

3rdparty/indi-fli/99-fli.rules, 3rdparty/indi-fli/CMakeLists.txt
Jasem, as per your request, rules for FLI :)
=> indi-fli: add udev rules

libindi/libs/webcam/v4l2_base.cpp, libindi/libs/webcam/v4l2_record/ser_recorder.cpp
I've added V4L2 integer menus (specifically for the rpi camera).
Also try to stop capturing/recording when device is disconnected.
Finally check if a V4L2 control is mutable before setting it (it can be grabbed, inactive,....)
=> V4L2 integer menus

libindi/libs/webcam/v4l2_base.cpp
Secured formatting of strings in static arrays with their own array size.
Let's see if this is enough to fix #242.
=> Secured formatting of strings in static arrays

3rdparty/CMakeLists.txt, 3rdparty/indi-mgen/mgc.h, 3rdparty/indi-mgen/mgcmd_get_fw_version.h, 3rdparty/indi-mgen/mgcmd_nop1.h, 3rdparty/indi-mgen/mgcmd_read_adcs.h, 3rdparty/indi-mgen/mgcp_enter_normal_mode.h, 3rdparty/indi-mgen/mgcp_query_device.h, 3rdparty/indi-mgen/mgen.h, 3rdparty/indi-mgen/mgen_device.cpp, 3rdparty/indi-mgen/mgen_device.h, 3rdparty/indi-mgen/mgenautoguider.cpp, 3rdparty/indi-mgen/mgenautoguider.h, 3rdparty/indi-mgen/mgio_insert_button.h, 3rdparty/indi-mgen/mgio_read_display_frame.h
WIP on warnings on all Travis checks.
=> Fix warnings in MGen driver

3rdparty/libqhy/85-qhy.rules, libindi/drivers/telescope/lx200ap.cpp, libindi/drivers/telescope/lx200ap.h
Based on converation with krno on fixing behavior of AstroPhysics mount driver.
I've tested these changes with my Mach1 and it is working much better.
=> Fixes for indi_lx200ap handling of MoveTo and Slew Rates

libindi/drivers/telescope/temmadriver.cpp
- Set serial communication for 19200 8e1 which is what temma uses
- Better handling of the eq busy light to improve integration with dome
- Minor kludge at handshake to get more reliable initial handshake
=> Updates to the temma mount driver

libindi/libs/indibase/baseclientqt.cpp
This file doesn't seem to be built (?)  but I though I'd catch the one remaining place the string "CONNECTION" is being used.
=> Caught one more location where CONNECTION property is being used

3rdparty/CMakeLists.txt, 3rdparty/indi-rtlsdr/AUTHORS, 3rdparty/indi-rtlsdr/CMakeLists.txt, 3rdparty/indi-rtlsdr/COPYING.LIB, 3rdparty/indi-rtlsdr/ChangeLog, 3rdparty/indi-rtlsdr/INSTALL, 3rdparty/indi-rtlsdr/README, 3rdparty/indi-rtlsdr/config.h.cmake, 3rdparty/indi-rtlsdr/indi_rtlsdr.xml, 3rdparty/indi-rtlsdr/indi_rtlsdr.xml.cmake, 3rdparty/indi-rtlsdr/indi_rtlsdr_detector.cpp, 3rdparty/indi-rtlsdr/indi_rtlsdr_detector.h, cmake_modules/FindRTLSDR.cmake, libindi/examples/tutorial_eight/simple_detector_simulator.cpp, libindi/examples/tutorial_eight/simple_detector_simulator.h, libindi/libs/indibase/indidetector.cpp, libindi/libs/indibase/indidetector.h, travis-ci/deps-linux.sh, travis-ci/deps-osx.sh
I added a driver for the RTL2832U software defined radios, added also a function in indidetector to notify the driver of any change of the detector parameters: modified the DetectorInfo property to RW.
Please forgive me for any build errors, since my compiler builds fine, I cannot know if travis runs successfully by now.
=> RTL-SDR driver and fixes and adds for Detector interface

3rdparty/indi-inovaplx/inovaplx_ccd.cpp, 3rdparty/indi-rtlsdr/CMakeLists.txt, 3rdparty/indi-rtlsdr/indi_rtlsdr_detector.cpp, 3rdparty/indi-rtlsdr/indi_rtlsdr_detector.h, 3rdparty/libdspau/AUTHORS, 3rdparty/libdspau/CMakeLists.txt, 3rdparty/libdspau/ChangeLog, 3rdparty/libdspau/INSTALL, 3rdparty/libdspau/libdspau-correlations.c, 3rdparty/libdspau/libdspau-fft.c, 3rdparty/libdspau/libdspau-filters.c, 3rdparty/libdspau/libdspau-stats.c, 3rdparty/libdspau/libdspau.h, libindi/libs/indibase/indidetector.cpp
I added correlation functions to libdspau, and I corrected memory over-usage issues.
I also added some code to set min, max, step in detector settings.
=> Additions to libdspau

3rdparty/indi-eqmod/align/align.cpp, 3rdparty/indi-eqmod/align/align.h, 3rdparty/indi-eqmod/align/pointset.cpp, 3rdparty/indi-eqmod/align/pointset.h, 3rdparty/indi-eqmod/eqmod.cpp
Issue discussed in the forum [here](http://indilib.org/forum/mounts/2512-eqmod-alignment-cleared-when-a-new-client-is-connected.html)
=> Fix Eqmod align poinset initialization

3rdparty/indi-eqmod/eqmod.cpp, 3rdparty/indi-eqmod/scope-limits/scope-limits.cpp, 3rdparty/indi-eqmod/scope-limits/scope-limits.h
Horizon data file is also loaded on first connection, if it exists.
=> Fix Horizon data being cleared on connection

libindi/libs/indibase/indidome.cpp
- Minor fix to slit sync math - will probably find more soon
=> - Change the shutter switch to allow only one selected for open/close

3rdparty/indi-inovaplx/inovaplx_ccd.h
=> Comment unused variables in indi-inovaplx [3rdparty]

libindi/libs/indibase/indidome.cpp
I found another error in the dome sync math, as well, base dome is not getting side of pier updates from the telescope.  Both corrected in this PR
=> Updates to dome sync math

libindi/CMakeLists.txt, libindi/drivers/auxiliary/sqm_simulator.cpp, libindi/drivers/auxiliary/sqm_simulator.h
I've implemented a little SQM simulator. Look at it and tell me what you think about it. Use when you like it.
=> Added Sky Quality Meter simulator

3rdparty/indi-eqmod/eqmod.cpp, 3rdparty/indi-eqmod/scope-limits/scope-limits.cpp, 3rdparty/indi-eqmod/skywatcher.cpp, 3rdparty/indi-eqmod/skywatcher.h
It seems that indi-eqmod should not compile since some months ago, I wonder how the build server succeeds.
=> Added standard/libnova missing headers. Init SkywatcherFeatures struct.

libindi/libs/indicom.c
Commit bbbead91e73ba04e65b219c84b02b9913bbf7a17 introduced a special case for Gemini UDP mode in tty_write and tty_read and broke them for any writes or reads that had zero bytes in them due to use of strncpy which terminates at the first zero byte. My dome driver happens to be one so I bisected what broke it in the last few days. The change also introduced a potential buffer overflow in case someone writes or reads more than about 256 bytes at a time. In this change it's only a problem for the Gemini special case, but should preferably be cleaned up properly.
=> Fix tty_write and tty_read for non-text protocols

3rdparty/indi-armadillo-platypus/99-armadilloplatypus.rules, 3rdparty/indi-armadillo-platypus/AUTHORS, 3rdparty/indi-armadillo-platypus/CMakeLists.txt, 3rdparty/indi-armadillo-platypus/INSTALL, 3rdparty/indi-armadillo-platypus/README, 3rdparty/indi-armadillo-platypus/arm_plat_focuser_common.cpp, 3rdparty/indi-armadillo-platypus/arm_plat_focuser_common.h, 3rdparty/indi-armadillo-platypus/armadillo_focuser.cpp, 3rdparty/indi-armadillo-platypus/config.h.cmake, 3rdparty/indi-armadillo-platypus/indi_armplatfocuser.xml.cmake, 3rdparty/indi-armadillo-platypus/platypus_focuser.cpp
As mentioned in the forum :-)
Covering focuser and USB for the moment. Looking forward to code more drivers.
=> Initial drivers for Lunatico's Armadillo and Platypus

3rdparty/indi-rtlsdr/indi_rtlsdr_detector.cpp, 3rdparty/libdspau/libdspau-fft.c, 3rdparty/libdspau/libdspau.h
Added support for multidimensional fourier transforms
=> modified fft in dspau

.travis.yml, travis-ci/deps-osx.sh
The reason was just cmake already present in the Xcode 8.3 image
=> Fix the OSX build issue on travis

3rdparty/indi-armadillo-platypus/arm_plat_focuser_common.cpp, 3rdparty/indi-armadillo-platypus/arm_plat_focuser_common.h
just also sent the doc directly via email.
Thanks
=> Adding sync command

.gitignore, libindi/drivers/telescope/celestrondriver.cpp, libindi/drivers/telescope/celestrondriver.h, libindi/drivers/telescope/celestrongps.cpp, libindi/drivers/telescope/celestrongps.h
All the commands are implemented, but it will need more testing before merging it into master. I will send you more pull requests with corrections.
=> Refactor celestrondriver.cpp

.circleci/build-3rdparty.sh, .circleci/build-all.sh, .circleci/build-core.sh, .circleci/build-deb-packages.sh, .circleci/build-libs.sh, .circleci/config.yml, .circleci/run-tests.sh, docker/debian_buster/Dockerfile, docker/debian_stretch/Dockerfile, docker/ubuntu_artful/Dockerfile, docker/ubuntu_bionic/Dockerfile
This commit should fix (in debian/ubuntu containers) the issue which cause unit tests not being run on CircleCI.
There are also some cosmetic changes, like removing trailing spaces and empty lines at the end of some files.
=> Make unit tests work in debian/ubuntu-based containers under CircleCI

libindi/drivers/focuser/focuslynxbase.cpp
Remove wrong model type / code
Correct syntax type for future usage
Correct Switch setting when reading the Hug config
=> Small cleaning focuser models

libindi/drivers/telescope/lx200ss2000pc.cpp, libindi/drivers/telescope/lx200ss2000pc.h
As detailed in the forums
http://www.indilib.org/forum/mounts/3231-ekos-sends-wrong-latitude-longitude-to-mount.html
=> Fix for Longitude not set correctly.

libindi/drivers/telescope/celestrongps.cpp
Please find the fix to close issue #547
=> fix park position by adding get_azalt() in SetCurrentPark

libindi/drivers/telescope/lx200_OnStep.cpp
=> Replace deprecated usleep with nanosleep

3rdparty/indi-maxdomeii/maxdomeii.cpp, 3rdparty/indi-maxdomeii/maxdomeiidriver.cpp
This commit fixes an error that caused an invalid checksum byte in the packets sent to the MaxDomeII controller.
=> Fix checksum error in maxdomeii. Implement dome motion buttons

3rdparty/indi-asi/asi_ccd.cpp, 3rdparty/indi-asi/asi_ccd.h
This update adds displaying of SDK version and ADC (Analog-to-Digital Converter) bit depth that were introduced in the latest SDK update.
=> Asi additional infos

3rdparty/indi-nightscape/README, 3rdparty/indi-nightscape/nightscape.cpp, 3rdparty/indi-nightscape/nightscape.h, cmake_modules/FindD2XX.cmake
Needed to handle libftdi defaults correctly when libd2xx is not installed.
=> Some additional changes to cleanup D2XX handling

libindi/drivers/telescope/lx200ss2000pc.cpp
This is a fix for the LX200 Sky Sensor 2000 PC, which crashes after the last stable due to the tty_nread_section(...) serial buffer overflow protection. 
Verified working.
=> Fix for LX200 Sky Sensor 2000 PC new RB_MAX_LEN buffer handling

3rdparty/indi-rtlsdr/indi_rtlsdr_detector.cpp
Here I extended the capture limit of rtlsdr to a whole sidereal day
=> [indi-rtlsdr] capture limit set to sidereal day

3rdparty/indi-duino/README, 3rdparty/indi-duino/indiduino.cpp, 3rdparty/indi-duino/indiduino.h, 3rdparty/indi-duino/libfirmata/src/arduino.cpp, 3rdparty/indi-duino/libfirmata/src/arduino.h, 3rdparty/indi-duino/libfirmata/src/firmata.cpp, 3rdparty/indi-duino/libfirmata/src/firmata.h
This pull request contains various fixes to ensure that indiduino driver shows real state of the device.
It is my first attempt to hack indi, so feedback is welcome.
=> Improve indiduino driver reliability

travis-ci/install-gtest.sh
Try use c++11 for gtest build on travis
=> WIP: Try c++11 for gtest

libindi/drivers/auxiliary/usb_dewpoint.cpp, libindi/drivers/auxiliary/usb_dewpoint.h
- similar serial communication cleanup USB_FocusV3 earlier with one function handling it instead of each command separately
- attempt command resync on connect
- added poll period control
=> Update to USB_Dewpoint driver

libindi/drivers/auxiliary/snapcap.cpp, libindi/drivers/auxiliary/snapcap.h
- serial communication cleaned up
- lowered minimum light brightness limit as it seems to work fine and is needed to get shutter time slow enough for my camera
- some other clean ups of left overs from Flip Flat driver
=> Update to Gemini SnapCap driver

libindi/drivers/auxiliary/flip_flat.cpp, libindi/drivers/auxiliary/flip_flat.h
- serial communications consolidated to one function
- clang-formatted
=> Update to FlipFlat driver

libindi/libs/indibase/indiccd.cpp
added XPIXSZ and YPIXSZ to indiccd.cpp
=> added XPIXSZ and YPIXSZ

libindi/drivers/weather/vantage.cpp, libindi/drivers/weather/weatherwatcher.cpp
Vantage: (issue ticket and forum report)
https://github.com/indilib/indi/issues/743
https://www.indilib.org/forum/general/3407-vantage-pro-2-driver.html#30941
WeatherWatcher: (issue ticket)
https://github.com/indilib/indi/issues/744
This was corrected and tested in my observatory.
Committing to public repository.
=> Small bug corrections on vantage and weatherwatcher drivers

3rdparty/indi-mgen/mgc.h, 3rdparty/indi-mgen/mgcmd_get_fw_version.h, 3rdparty/indi-mgen/mgcmd_nop1.h, 3rdparty/indi-mgen/mgcmd_read_adcs.h, 3rdparty/indi-mgen/mgcp_enter_normal_mode.h, 3rdparty/indi-mgen/mgcp_query_device.h, 3rdparty/indi-mgen/mgen.h, 3rdparty/indi-mgen/mgen_device.cpp, 3rdparty/indi-mgen/mgen_device.h, 3rdparty/indi-mgen/mgenautoguider.cpp, 3rdparty/indi-mgen/mgenautoguider.h, 3rdparty/indi-mgen/mgio_insert_button.h, 3rdparty/indi-mgen/mgio_read_display_frame.h
MGEN-UI-buttons now ordered as on the original device:
[  ESC ].   [  SET ]
[  UP  ]
[ LEFT ]   [ RIGHT ]
[ DOWN ]
=> changed UI button order to a more natural/MGEN way

libindi/drivers/focuser/focuslynxbase.cpp, libindi/drivers/focuser/focuslynxbase.h
Reading of all Temp information via new function after connection to the
HUB
Some new code cleaning
=> Write Max travel value to the HUB (Function was missing)

libindi/CMakeLists.txt, libindi/drivers.xml, libindi/drivers/weather/openweathermap.cpp, libindi/drivers/weather/openweathermap.h
This is practically search & replace job of the WunderGround API driver, which is due to be shut down at the end of this year, hence my reason for doing this. Obviously the data has slightly different format and content but all useful data should now be parsed. Converting varying weather conditions to the WEATHER_FORECAST property is a bit up to interpretation, but I assigned 0 only to clear condition, 1 to varying "some cloud or mist" conditions and 2 to pretty much everything else. I just wrote this today so don't have much experience what kind of conditions there are in practice :)
=> Initial driver to use weather data from OpenWeatherMap service

3rdparty/indi-starbook/starbook_types.cpp, 3rdparty/indi-starbook/starbook_types.h
Due to strict checks friend functions in `starbook` namespace broke the build.
=> Fix friend function scope in starbook namespace

3rdparty/indi-ssag/ssagccd.cpp
Fix for the Orion SSAG abort exposure issue.  Improves guiding reliability while switching targets or stopping guiding.
=> SSAG abort exposure fix

libindi/drivers/telescope/lx200_OnStep.cpp
Missed a couple of places in the previous pull request. Hope I got them all this time.
=> Really changed the labels this time, for consistency with Android App

3rdparty/indi-eqmod/eqmod.cpp, 3rdparty/indi-eqmod/eqmod.h, 3rdparty/indi-eqmod/indi_eqmod_sk.xml, 3rdparty/indi-eqmod/test/test_eqmod.cpp
This is what I have so far for
https://github.com/indilib/indi/issues/798
I have found that pier side and limits checking on south hemisphere was broken - pier side should not depend on hemisphere.
I have not tested it much yet, I just made it pass the unit tests.
=> WIP: Replace FORCECWUP with TARGETPIERSIDE in eqmod

3rdparty/generic-ccd/README, 3rdparty/indi-altaircam/indi_altair.cpp, 3rdparty/indi-apogee/README, 3rdparty/indi-armadillo-platypus/README, 3rdparty/indi-fli/README, 3rdparty/indi-gige/README, 3rdparty/indi-gphoto/README, 3rdparty/indi-gphoto/gphoto_driver.cpp, 3rdparty/indi-inovaplx/README, 3rdparty/indi-limesdr/README, 3rdparty/indi-qhy/README, 3rdparty/indi-qsi/README, 3rdparty/indi-radiosim/README, 3rdparty/indi-rtlsdr/README, 3rdparty/indi-sbig/README, 3rdparty/indi-sbig/sbig_ccd.cpp, 3rdparty/indi-shelyak/indi_shelyakeshel_spectrograph.cpp, 3rdparty/indi-shelyak/indi_shelyakspox_spectrograph.cpp, 3rdparty/indi-spectracyber/Readme, 3rdparty/indi-spectracyber/spectracyber.cpp, 3rdparty/indi-sx/README
I probably did not get all of them, but here are a few updates to the spelling of various line comments, debug messages and one of the values in a drop downs for shelyakeshel_spectrograph.
=> Amended spelling on various comments and messages in /3rdparty

libindi/drivers/video/v4l2driver.cpp
Info from https://www.indilib.org/forum/ccds-dslrs/4392-indi-v4l2-pixel-size-detection.html#33709
=> Add SVBONY SV105 to V4L pixel size table

libindi/drivers/telescope/pmc8.cpp, libindi/drivers/telescope/pmc8.h, libindi/drivers/telescope/pmc8driver.cpp, libindi/drivers/telescope/pmc8driver.h
updated PMC8 to select mounts G11, EXOS2, iEXOS100.
=> updated PMC-Eight mounts

libindi/CMakeLists.txt, libindi/drivers.xml, libindi/drivers/dome/scopedome_dome.cpp, libindi/drivers/dome/scopedome_dome.h, libindi/drivers/dome/scopedome_sim.cpp, libindi/drivers/dome/scopedome_usb21.cpp
I've now used this driver for over a year actively so I guess it's starting to be ready for wider testing too :)  I wrote some documentation for it in http://s2.org/~jpaana/scopedome/ which also documents the prerequisites and other caveats. I didn't want to squash the commits so that there is some history left. Phew!
=> Driver for ScopeDome dome controller

3rdparty/indi-avalon/CMakeLists.txt, 3rdparty/indi-avalon/lx200stargo.cpp
Bug fix correcting the display of the pier side.
=> Pier side display corrected

libindi/drivers.xml, libindi/drivers/focuser/deepskydad_af1.cpp, libindi/drivers/focuser/deepskydad_af1.h
Hello,
I have added the INDI driver for Deep Sky Dad Autofocuser 1 (AF1). Based on Moonlite driver. 
Autofocuser source code (firmware, ASCOM): https://github.com/DeepSkyDad/AF1
Autofocuser website: https://deepskydad/autofocuser
Best regards,
Pavle
=> Adding DeepSkyDad AF1 driver

3rdparty/indi-duino/indiduino.cpp, 3rdparty/indi-duino/libfirmata/src/firmata.cpp, 3rdparty/indi-duino/libfirmata/src/firmata.h
Here are some indi-duino fixes.
=> indi-duino fixes

libindi/CMakeLists.txt, libindi/drivers/focuser/celestron.cpp, libindi/drivers/focuser/celestron.h, libindi/drivers/focuser/celestronauxpacket.cpp, libindi/drivers/focuser/celestronauxpacket.h
These changes implement a working version of the Celestron focuser driver.
Changes are to CMake, celestron.cpp.h and new files celestronauxpacket.cpp.h.
=> Celestron work

3rdparty/indi-duino/indiduino.cpp
This reduces load on indiserver and client.
=> indi-duino: send message only if the value really changes

.github/ISSUE_TEMPLATE/bug_template.md
Looking at issues I can see an emerging pattern and lack of proper data to tackle some of the issues.
=> Create issue template for bug reports

3rdparty/indi-starbook/README.rst, 3rdparty/indi-starbook/indi_starbook.cpp, 3rdparty/indi-starbook/starbook_types.cpp, 3rdparty/indi-starbook/starbook_types.h
Somehow my PR slipped through OSX CI
=> Starbook 0.5~something

libindi/drivers/telescope/celestrondriver.cpp, libindi/drivers/telescope/celestrondriver.h, libindi/drivers/telescope/celestrongps.cpp, libindi/drivers/telescope/celestrongps.h
the Indi track mode has been changed to Sidereal, Solar, or Lunar for Equatorial mounts only
=> Change INDI Track Mode

3rdparty/indi-talon6/ChangeLog, 3rdparty/indi-talon6/README, 3rdparty/indi-talon6/talon6.cpp, 3rdparty/indi-talon6/talon6.h, debian/indi-talon6/changelog
hi Jasem,
It has been raining a lot recently, so here's the first (almost) feature complete Talon6 driver version.
Main features added:
- Sync roof position ticks
- Enable / Disable safety conditions that allow to control manually the roof
- Go To command to control partial open / close positions.
About the documentation, can you allow direct access to the web pages or shall I send you a .html zipped file?
Some weeks ago I sent you the documentation for Weather Watcher driver but it's not yet online. Was not useful / complete? shall i integrate some more infos?
Best
Ferrante
=> Talon 6 RoR -V 1.0

3rdparty/indi-dreamfocuser/CMakeLists.txt, 3rdparty/indi-dreamfocuser/config.h.cmake, 3rdparty/indi-dreamfocuser/dreamfocuser.cpp, 3rdparty/indi-dreamfocuser/dreamfocuser.h
Just small updates in a few places.
=> Improve Sync, Park, FocusMax. Add driver version.

libindi/drivers.xml, libindi/drivers/dome/scopedome_dome.cpp, libindi/drivers/dome/scopedome_dome.h
- Added calibration function
- Updated homing function to correct for overshoot and to also reset the larger rotation counter
- Added some info messages to different functions
- Added enum for status register bits
=> ScopeDome calibration and other clean up

3rdparty/indi-avalon/CMakeLists.txt, 3rdparty/indi-avalon/lx200stargo.cpp, 3rdparty/indi-avalon/lx200stargo.h, debian/indi-avalon/changelog
A new set of features are added:
- Switch for enabling / disabling the keypad
- System slewing speed settings
Have fun!
Wolfgang
=> Avalon Stargo 1.5 - Keypad and System Slew Speed

libindi/CMakeLists.txt, libindi/drivers.xml, libindi/drivers/auxiliary/lpm.cpp, libindi/drivers/auxiliary/lpm.h
An indi-lib driver for Astromechanics LPM (light pollution meter) PRO.
https://www.astromechanics.org/lpm.html
Find the documentation attached to this pull request. Feedback, improvements, etc. welcome.
[Astromechanics_LPM_Documentation.tar.gz]
(https://github.com/indilib/indi/files/3241811/Astromechanics_LPM_Documentation.tar.gz)
=> new driver for Astromechanics LPM (light pollution meter) pro

libindi/drivers.xml, libindi/drivers/focuser/sestosenso.cpp, libindi/drivers/focuser/sestosenso.h
Added a Calibration routine.
Changed the focuser in motion timer function to cease when movement has ceased.
Reset temperature counter to allow updates of the temperature.
=> Added calibration and fixed temperature update

libindi/libs/stream/ccvt_misc.c, libindi/libs/webcam/v4l2_base.cpp
This PR is expected to fix the issue discussed at https://www.indilib.org/forum/ccds-dslrs/3180-v4l2-subframe-error-with-phd2.html. A regular issue had to be created, but was not. I'll open one to describe the intent.
=> Bugfix for V4L2 odd crop dimensions

libindi/drivers/auxiliary/pegasus_ppb.cpp
Tested locally after debugging with E.Souglakos
Signed-off-by: Pierros Papadeas <pierros@papadeas.gr>
=> Fix Dew control and Current sensing on PPB

libindi/libs/stream/streammanager.cpp, libindi/libs/stream/streammanager.h
=> Apply gamma when downscaling 16bit to 8bit stream

CMakeLists.txt, drivers.xml, drivers/focuser/deepskydad_af3.cpp, drivers/focuser/deepskydad_af3.h
Driver for our new autofocuser
=> Deep Sky Dad AF3 driver

drivers/filter_wheel/ifwoptec.cpp, drivers/focuser/moonlite_dro.cpp, drivers/focuser/onfocus.cpp, drivers/focuser/smartfocus.cpp, drivers/focuser/steeldrive.cpp, drivers/telescope/ieqdriverbase.cpp, drivers/telescope/lx200_OnStep.cpp, drivers/telescope/lx200ap_experimental.cpp, drivers/telescope/lx200generic.cpp, drivers/video/v4l2driver.cpp, drivers/weather/weather_safety_proxy.cpp, libs/indibase/indidome.cpp
Overseen by the previous inspection.
Many thanks for reviewing this and your patience.
=> A few more typo fixes

drivers.xml, drivers/video/v4l2driver.cpp
A simple change to add the iOptron iPolar scope with the correct pixel sizes.
=> Added support for iOptron iPolar.

libs/indicom.c, libs/indicom.h
Added functions in common routine source.
* Added photon flux calculation
* Added Planck constant and Lumen value #defines
* Updated absolute magnitude and parallax estimations
=> [INDI common]

drivers/focuser/deepskydad_af3.cpp, drivers/focuser/deepskydad_af3.h
I added backlash compensation to deepskydad AF3.
=> Backlash compensation

CMakeLists.txt, drivers.xml, drivers/focuser/sestosenso2.cpp, drivers/focuser/sestosenso2.h
Adding new indi driver for support SestoSenso2 focuser
Version: 0.1
=>  New driver for SestoSenso2 focuser

libs/indicom.c
[indicom.c] Removed line that adds 90.0 to declination in interferometry_calc_uv_coordinates
=> Changed UV plot helper

drivers/rotator/nightcrawler.cpp, libs/indibase/connectionplugins/connectionserial.cpp, libs/indibase/indidome.cpp, libs/indibase/indirotatorinterface.cpp
In commit df9760729845782dbe6a4daac435749ce41c7481 "ENABLED"
was replaced by "INDI_ENABLED". Some files however missed the update.
=> Change "ENABLED" to "INDI_ENABLED"

base64.c, base64.h, indiapi.h, indidriver.c, libs/indibase/baseclient.cpp, libs/indibase/baseclientqt.cpp, libs/lilxml.c, test/core/test_base64.cpp
Hi, found one real memory problem with uninitialized data in newLilXML that initParser can have problem with freeing pointers that might be randomly initialized.
Also added some asserts (only active in debug builds).
And some other rewrites that I hope are ok.
=> Some asserts and one memory error.

drivers/focuser/deepskydad_af3.cpp, drivers/focuser/deepskydad_af3.h
max position was implemented using the INDI framework
=> Fixed issues with deepskydad_af3_focus driver

CMakeLists.txt, drivers.xml, drivers/auxiliary/pegasus_ppba.cpp, drivers/auxiliary/pegasus_ppba.h
Here is a first version for the new Pegasus Powerbox Advance.
Anthony.
=> Added Pegasus Powerbox Advance driver

drivers/README.md
Hi, some misspellings and I think the capture has moved to main panel by default? Just a suggestion if you like it.
Regards, Lars
=> Minor template fixes.

drivers/telescope/skywatcherAPIMount.cpp
The same fix for skywatcherAPIMount. Tested, works. 
Thanks for the original fix!
=> Snooping was not active

libs/indibase/baseclientqt.cpp
Fixed a small syntax error in baseclientqt.cpp that was introduced with memory allocation changes.
=> Syntax error fix

drivers/dome/scopedome_dome.cpp
Celebrating the official work-on-dome-driver week, here are a few fixes I had accumulated :)
=> ScopeDome: fix relay inputs and add rotary link watchdog and polling limits

drivers/telescope/lx200gemini.cpp
Further fix to address issues with park and the Losmandy Gemini.
The Ekos summary screen reported "Slewing" after the park was completed, even though shutdown scripts executed properly.
Traced to the EqNP property state not being set to IPS_IDLE on park complete.  This left the state at IPS_BUSY, which was interpreted as a continued slew state in Ekos (referencing state evaluation in Telescope::Status Telescope::status() in inditelescope.cpp in kstars)
With EqNP state set to IPS_IDLE after park, Ekos summary now correctly reports Parked.
Also fixed the issue where EqNP was left busy after the end of a slew, as signalled by the yellow indicator on the indi driver page.
=> Set Eq Coords property state to OK & IDLE as needed

drivers/focuser/deepskydad_af3.cpp
To be a bit more accurate, reduced the debounce value from 0.5 to 0.1
=> Reduce Temperature Debouncing

drivers/weather/weatherwatcher.cpp, drivers/weather/weatherwatcher.h
Hi,
I use my own DIY weather station, and needed Humidity, Pressure and Clouds % in the WeatherWatcher driver.
I also re-ordered "Rain" (index 0) in the source code, for better reading.
Do you want to add these values in the upstream driver ?
Best regards,
Blaise
=> Added Humidity, Pressure and Clouds to the WeatherWatcher driver

drivers/telescope/lx200pulsar2.cpp, drivers/telescope/lx200pulsar2.h
These changes implement some things that were non-working in the original version, plus add support for several more advanced Pulsar2 features.  Many thanks to the original creator (Camiel Severijns) for review and additional contributions and testing.
=> Many bug fixes and additions supporting advanced Pulsar2 features

CMakeLists.txt, drivers.xml, drivers/focuser/rbfocus.cpp, drivers/focuser/rbfocus.h
Closed by mistake pull request resubmitted.
=> rbfocus driver intitial release

drivers/telescope/celestrongps.cpp, libs/indibase/dsp/dspinterface.cpp, libs/indibase/indiccd.cpp, libs/indibase/indilogger.cpp, libs/indibase/indisensorinterface.cpp
I unified the various libraries using INDI::mkpath (IndiUtility)
=> use of the common mkpath function

drivers.xml, drivers/focuser/sestosenso2.cpp, drivers/focuser/sestosenso2.h
Added warning and alert state if 12V power is insufficent.
Voltage polled alongside temprature.
=> Sesto Senso 2: Support for displaying 12V input voltage.

drivers.xml, drivers/focuser/sestosenso2.cpp, drivers/focuser/sestosenso2.h
Moved firmware info to Connection tab
=> Sesto Senso 2: Log & display firmware version

CMakeLists.txt, drivers.xml, drivers/telescope/crux_mount.cpp, drivers/telescope/crux_mount.h
Added new INDI Telescope for CRUX Mount of HOBYM Observatory.
https://www.hobym.net/
hparksy@gmail.com
=> add HOBYM Crux telescope driver

drivers/telescope/lx200_10micron.cpp, drivers/telescope/lx200_10micron.h
Read UnattendedFlip setting from mount and config, Update where needed.
Log why and if sendScopeLocation and sendScopeTime are being called.
Clean up code, reorganize and comment API calls.
=> UnattendedFlip handling, implements #1276

CMakeLists.txt, drivers.xml, drivers/focuser/activefocuser.cpp, drivers/focuser/activefocuser.h, drivers/focuser/activefocuser_utils.cpp, drivers/focuser/activefocuser_utils.h
Here is my contribution to the indi repository by adding the INDI driver for the ActiveFocuser system (focuser for Mewlon-250CRS and CCA250).
You can download the driver informations for the website on this [link](http://www.takahashi-europe.com/support/softwares/activefocuser/driver-informations-indi.zip).
=> ActiveFocuser driver release

drivers/agent/agent_imager.cpp, examples/tutorial_four/simpleskeleton.cpp, indidevapi.h, indidriver.c, libs/indibase/basedevice.cpp, libs/indibase/basedevice.h, libs/indibase/defaultdevice.cpp, libs/indibase/indiproperty.cpp, libs/indibase/indiproperty.h, libs/indibase/indiutility.h, libs/lx/Lx.cpp
Hi!
I found an unfinished "INDI::Property" class. I have moved some of the scattered code into this class.
For those who are bored:
I am thinking to use "BaseDevice" and "Property" to implement the idea:
https://github.com/pawel-soja/indi/tree/widgets/examples/example_widgets
=> Indibase/refactoring - update INDI::Property

drivers/focuser/sestosenso2.cpp
This allows the user presets on the firmware to be loaded and saved.
This simulates what the RUNPRESET command should be doing.
=> Sesto Senso 2: Workaround apply motor preset issue

libs/indibase/basedevice.cpp, libs/indibase/basedevice.h, libs/indibase/basedevice_p.h, libs/indibase/defaultdevice.cpp
Hi!
I extracted the data of the INDI::BaseDevice class.
By the way, I improved a few places.
=> Refactoring/INDI::BaseDevice - D-Pointer implemented

eventloop.c, indidriver.c, libs/indibase/indicorrelator.cpp, libs/indibase/indicorrelator.h, libs/indicom.c, libs/indicom.h, tools/getINDIproperty.c, tools/setINDIproperty.c
While browsing the sources, I immediately made corrections.
- less mallocs
- less unnecessary dependencies between files
- Separation of the common part in indidriver (escapeXML_vprintf)
- null-terminated strings in tty_error_msg
- others to improve readability
=> Refactoring - less dependencies between files / less mallocs

drivers/video/v4l2driver.cpp, drivers/video/v4l2driver.h
By this, i get deterministic stacked results, with the same amount of stacked frames.
=> Frame Based V4L Stacking and lazy stop capture for better loop perf

CMakeLists.txt, drivers.xml, drivers/dome/ddw_dome.cpp, drivers/dome/ddw_dome.h
Fairly simple dome driver as the controller handles most things by itself. The only slightly complicated aspect was that the controller may respond to hand controller commands at any point, but that was pretty straight forward to poll. 
Missing functionality in this first version:
- initiating dome calibration
- using direct LX200 protocol mount interception / slaving the controller supports (may not be needed nor wanted versus regular INDI dome slaving)
- relative movements and CW/CCW hand controller emulation
- shutter closing/dome moving order when parking is probably not optimal if parking position is not the same as home position where electrical connections are (shutter can only be operated there)
=> Driver for Digital Dome Works (DDW) from Technical Innovations

drivers/dome/ddw_dome.cpp
Forgot the existence of handy helper functions for setting state instead of trying to handle them manually :)
=> Fixes to handling of state changes in DDW driver

drivers/dome/ddw_dome.cpp
Hopefully final fix to the state change logic when controller completes operation.
=> DDW state change fix part 2 

CMakeLists.txt, libs/indibase/basedevice.cpp, libs/indibase/basedevice.h, libs/indibase/defaultdevice.cpp, libs/indibase/property/indiproperty.cpp, libs/indibase/property/indiproperty.h, libs/indibase/property/indipropertyview.h, libs/indibase/property/indipropertyview_client.cpp, libs/indibase/property/indipropertyview_driver.cpp
Hi,
Another portion of new methods to improve access to low-level functions.
Extracting the apply/define implementation for client/driver side.
Compiled and tested with the pyindi-client project.
@geehalel I'll give you a suggestion to simplify indiclientpython.i.
=> PropertyView - client/server side + refactor

drivers/telescope/lx200pulsar2.cpp, libs/indibase/property/indipropertybasic.cpp, libs/indibase/property/indipropertybasic.h, libs/indibase/property/indipropertyview.h
Hi!
Changes:
- the ability to dynamically add widgets
- checking the number of widgets
- getting the address to PropertyView<> from INDI::PropertyXXX
- adding getters to PropertyView<IBLOB>
- const fix
- fix for loop
=> INDI::PropertyXXX - push widgets, get size - implementation

libs/indibase/indiccd.h, libs/indibase/indiccdchip.h, libs/indibase/indisensorinterface.h, libs/stream/streammanager.cpp, libs/stream/streammanager.h, libs/stream/streammanager_p.h
Hi!
Unfortunately, in https://github.com/indilib/indi/pull/1372 I made a mistake removing the reference. Image enlargement in the preview does not work.
I noticed this in testing after implementing D-Pointer.
Changes:
- Reference bugfix - new implementation
- D-Pointer
- Use INDI::PropertyXXX - it's safe, because old IXXX / IXXXPropertyView were in the private section
- More readable public header streammanager.h
- Add missing const
Dependent libraries recompilation required - last time ;)
=> StreamManager - Bugfix - D-Pointer implementation

CMakeLists.txt, examples/tutorial_three/simpleccd.cpp, examples/tutorial_three/simpleccd.h, libs/indibase/timer/indielapsedtimer.cpp, libs/indibase/timer/indielapsedtimer.h, libs/indibase/timer/indielapsedtimer_p.h, libs/indibase/timer/inditimer.cpp, libs/indibase/timer/inditimer.h, libs/indibase/timer/inditimer_p.h
Hi!
I am rewriting camera drivers, I notice quite a lot of redundant code.
This pull request includes a simple implementation of high-level timers like Qt-Timers.
INDI::Timer uses the low level timers from eventloop.c.
Public header files have a description.
=> Implementation of high-level timers

eventloop.c
Hi!
Currently, timers are stored in an array that is increased, decreased, copied and sorted each time.
Implementation should be list-based from the beginning (all source file).
Changes:
- Simple list implementation
- Entries are kept sorted by **increasing** time from epoch - The first item is fired and removed from the list
- malloc / free for a single element only.
In the future, I will rework (all source file) it and minimize the allocation.
=> EventLoop - List implementation for timers

drivers.xml, drivers/focuser/dmfc.cpp, drivers/focuser/dmfc.h
Changes to indi_dmfc_focuser driver in order to support  Devices (Pegasus ScopsOAG and FocusCube v2).
=> Added PegasusAstro new devices

.github/workflows/macos.yml, scripts/requisites-install.sh
Bonus `scripts/requisites-install.sh` for Linux/MacOS
=> Add GitHub Actions for MacOS.

CMakeLists.txt, drivers.xml, drivers/focuser/dmfc.cpp, drivers/focuser/dmfc.h, drivers/focuser/pegasus_focuscube.cpp, drivers/focuser/pegasus_focuscube.h, drivers/focuser/pegasus_scopsoag.cpp, drivers/focuser/pegasus_scopsoag.h
=>  separate focuscube and scopsoag behavior to new drivers

libs/indibase/baseclient.cpp, libs/indibase/baseclient.h, libs/indiuserio.c
=> Fix sockets in INDI::BaseClient

libs/indibase/baseclient.cpp
@knro I lost one commit. Closes the connection if sending has failed.
Check if you still have SIGPIPE.
I'll do more tests by constantly sending data and closing the connection.
=> INDI::BaseClient - Disconnect if sending has failed.

drivers/telescope/temmadriver.cpp
Changed the slew direction of the temma driver as per the issue (#1441)
=> Changed E-W direction in driver as (#1441)

CMakeLists.txt, drivers.xml, drivers/dome/scopedome_arduino.cpp, drivers/dome/scopedome_arduino.h, drivers/dome/scopedome_dome.cpp, drivers/dome/scopedome_dome.h, drivers/dome/scopedome_sim.cpp, drivers/dome/scopedome_sim.h, drivers/dome/scopedome_usb21.cpp, drivers/dome/scopedome_usb21.h
Finally long overdue update to the ScopeDome driver I've worked on and off for more than a year now :) Finally got testers for the new Arduino Card controller (I only got the controllers from ScopeDome, but they weren't connected to anything) to get that work completed and fixed last regression from the older USB Card 2.1 path so I've now run this code myself for couple of weeks without issues. Progress got documented mostly in INDI forum thread at https://www.indilib.org/forum/domes/7648-cannot-connect-to-2m-scopedome-arduino.html
Other than that the code got cleaner and now uses the new PropertyWidget types, which simplify the code even further.
Main changes:
- abstract card specific functionality better to support very different controller types
- add support for new ScopeDome Arduino …
=> ScopeDome driver update

drivers/telescope/lx200_OnStep.cpp
Resolves issue here: https://www.indilib.org/forum/development/1406-driver-onstep-lx200-like-for-indi.html?start=624#71684
=> OnStep: Fix for issue mentioned on forums

drivers/telescope/eq500x.cpp, drivers/telescope/eq500x.h, drivers/telescope/lx200telescope.h
This PR fixes some parts of the refactoring that occurred in 7488e284ee58e4b78c33eea554d5a3c63f919764, and makes sure CI tests pass.
=> Fix EQ500X driver and tests after refactoring.

drivers/focuser/rainbowRSF.cpp
1) Update the comments about the Rainbox Focuser API, based on the new API doc sent by Rainbow Astro.
2) Previously I had allowed position messages using the sDDDD or sDD.DDD formats.
Removed the former, as we learned from Rainbow Astro that it is not a valid message format.
=> Update Rainbow Focuser API Comments, Follow Updated API

drivers/telescope/paramount.cpp
* TheSkyX async command updates related to recently updated GuideTimer additions
* Correction to Pier-side polarity
As a result of the change in pier-side requiring re-calibration of guiding, I've bumped the version to 1.4
Everything has been successfully night-sky tested on a Paramount MX+ running on Ubuntu 20.
=> TheSkyX/Paramount Pier-side + guide async cmd fixes

drivers/auxiliary/pegasus_uch.cpp, drivers/auxiliary/pegasus_uch.h
Fixing the problem that device not appeared at IndiPanel.
=> Pegasus UCH

drivers/focuser/myfocuserpro2.cpp, drivers/focuser/myfocuserpro2.h
Please set polling to 2s or higher.
=> Improved handling of myFP2ESP controllers

libs/indicom.c
Adaption of FreeBSD ports tree patch.
Original-Author: Jose Alonso Cardenas Marquez <acm@FreeBSD.org>
=> indicom: fix FreeBSD compilation

drivers/focuser/planewave_efa.cpp, drivers/focuser/planewave_efa.h
Description of changes in this indilib forum entry:
https://indilib.org/forum/focusers-filter-wheels/10434-problem-connecting-to-planewave-efa-handshake-fails.html#76116
=> fixes to PlaneWave EFA driver

drivers/telescope/lx200pulsar2.cpp, drivers/telescope/lx200telescope.cpp
This should fix it for all the places that IUSaveText wasn't used in relation to SiteName, and also fix the pulsar2 driver to use IUSaveText. (I can't test that one.) 
I am away from home, but I am not 100% able to test on OnStep.
=> LX200 SiteName Fix V2

drivers.xml, drivers/weather/openweathermap.cpp, drivers/weather/openweathermap.h
Updates and cleanup for the OpenWeatherMap driver:
- use new property api
- report curl errors
- fix labels and reset values for rain & snow
- clean up json parsing by moving repeated code to lambda function
- run astyle for header
=> Updates and cleanup for the OpenWeatherMap driver

drivers/telescope/lx200_OnStep.cpp
Thought this was in there, but apparently messed it up at some point messing with git.
=> OnStep: Remove Focuser on disconnect

drivers/telescope/skywatcherAPI.cpp, drivers/telescope/skywatcherAPI.h, drivers/telescope/skywatcherAPIMount.cpp, drivers/telescope/skywatcherAPIMount.h
Improve Skywatcher GOTO by using iterative goto and also the tracking quality.
=> Improve Skywatcher tracking

drivers/telescope/rainbow.cpp
This fixes the firmware appears in the "General Info" tab
=> Fix a problem on the Serial Number and Firmware display

drivers/telescope/lx200_TeenAstro.cpp, drivers/telescope/lx200_TeenAstro.h
Can now update slew rate from the INDI driver as well as from the handset.
=> Fixed updating of slew rate

.github/workflows/pyindi.yml
run actual pyindi tests, not just import the pyindi lib to verify that python binding is working
=> Pyindi - run actual tests

drivers/telescope/lx200driver.cpp
https://github.com/indilib/indi/issues/1604
=> Fix setObjectRA and setObjectDEC for short and long format and longer format for issue #1604

drivers/telescope/lx200ap_v2.cpp, drivers/telescope/lx200apdriver.cpp
Bug formatting utc string for negative values
=> Fix but setting AP UTC

indiserver.cpp, integs/CMakeLists.txt, integs/ConnectionMock.cpp, integs/ConnectionMock.h, integs/IndiServerController.h, integs/ProcessController.cpp, integs/ProcessController.h, integs/TestClientQueries.cpp, integs/TestIndiSetProp.cpp, integs/TestIndiserverSingleDriver.cpp
This MR fixes half closed client beeing dropped by indiserver
=> Fix for indi_setprop

indiserver.cpp, integs/ProcessController.cpp, integs/ProcessController.h, integs/TestIndiserverSingleDriver.cpp
Fix indiserver keeping connections open up to a crash.
=> Fix socket leak

indiserver.cpp, integs/TestIndiserverSingleDriver.cpp
The size passed to munmap didn't match the size from mmap... Not all mapping were removed
=> Fix memory leak when converting blob to base64

drivers/telescope/lx200gemini.cpp, drivers/telescope/lx200gemini.h
I've added some basic PEC status and control to the lx200gemini driver.
=> Adding some basic PEC status and control to lx200gemini

drivers/telescope/lx200gemini.cpp, drivers/telescope/lx200gemini.h
I'm not sure if I'm making this merge request correctly. I was expecting just my latest commit to show up, but I see "3 commits" 
Simple update described in the title.
=> Added "enable pec at boot" switch, and a display for "current pec guide speed" 

libs/dsp/fits.h
=> Fix compilation with older gcc (debian 9 / stretch)

drivers/telescope/lx200apdriver.cpp
Small fix to the AP v2 driver, suggested my Mike Hanson
=> Fix issue in AstroPhysics getApMountFeatures

integs/ProcessController.cpp
The test fail to report correctly when indiserver got signalled
=> Check for signalled process in integration test

drivers/telescope/lx200ap_v2.cpp, drivers/telescope/lx200ap_v2.h, drivers/telescope/lx200apdriver.cpp, drivers/telescope/lx200apdriver.h
Mike H's latest changes to use correct rate tables for different mounts and controllers
=> ap rate tables

drivers/ccd/ccd_simulator.cpp, drivers/ccd/guide_simulator.cpp
Periodic error simulation seems broken. Fix.
=> fix periodic error simulation

libs/locale_compat.h
https://devblogs.microsoft.com/cppblog/msvc-preprocessor-progress-towards-conformance/
=> Fix locale_compat.h for newest MSVC

indiserver.cpp
Valgrind showed some memory leaks in indiserver.
This PR should fix them.
=> Fix memory leaks in indiserver

CMakeLists.txt, drivers.xml, drivers/telescope/lx200_OpenAstroTech.cpp, drivers/telescope/lx200_OpenAstroTech.h, drivers/telescope/lx200generic.cpp
Adds a driver for [OpenAstroTech](https://openastrotech.com) mounts.
=> Driver for OpenAstroTech mounts

.github/workflows/default.yml
This pull request turns back the building and testing of INDI on a Fedora system.
https://github.com/indilib/indi/issues/1682
https://github.com/indilib/indi/actions/runs/3263141923
=> Enable fedora build

.github/docker/Dockerfile.debian, .github/docker/Dockerfile.fedora, .github/docker/Dockerfile.ubuntu, .github/workflows/pyindi.yml, scripts/indi-core-build.sh, scripts/requisites-install.sh
This pull request enables INDI_BUILD_QT5_CLIENT that is building the `INDI::BaseClientQt` class.
=> Enable INDI_BUILD_QT5_CLIENT

CMakeLists.txt, drivers/auxiliary/Excalibur.cpp, drivers/auxiliary/Excalibur.h
Adding RB Focus Excalibur driver to INDI Core
=> Add Excalibur Driver

drivers/weather/uranusmeteo.cpp, drivers/weather/uranusmeteo.h, libs/indibase/indigps.cpp, libs/indibase/indiweather.cpp, libs/indibase/indiweather.h, libs/indibase/indiweatherinterface.cpp, libs/indibase/indiweatherinterface.h
+ Improve Uranus Meteo driver
+ Fix Weather Interface
+ Fix GPS Interface
=> Update weather interface to define update period, refresh and override

drivers/telescope/lx200_10micron.cpp, drivers/telescope/lx200_10micron.h
Fixes for https://github.com/indilib/indi/issues/1582 # lx200_10micron not correctly reporting the parking status
- park status notifications
- extra debugging for command errors
=> fix for issue1582 park status notifications and extra debugging for command errors

drivers/telescope/lx200gemini.cpp, drivers/telescope/lx200gemini.h
Changing numbers to switches, and handling states better.
=> General cleanup

drivers/telescope/lx200gemini.cpp, drivers/telescope/lx200gemini.h
Switch Flip Points to use sexagesimal numbers.
=> Switch Flip Points to use sexagesimal numbers.

drivers.xml, drivers/auxiliary/snapcap.cpp, drivers/auxiliary/snapcap.h, drivers/auxiliary/usb_dewpoint.cpp, drivers/auxiliary/usb_dewpoint.h, drivers/focuser/usbfocusv3.cpp, drivers/focuser/usbfocusv3.h
Update USB Focus V3, USB Dewpoint and Gemini SnapCap drivers to new style properties and some clean up.
=> Some property updates to my drivers

drivers/auxiliary/gps_simulator.cpp, drivers/weather/uranusmeteo.cpp, libs/indibase/indigps.cpp, libs/indibase/indigps.h
Update INDI::GPS class and classes inheriting INDI::GPS to be inline with INDI 2.0.0
=> Refactor INDI::GPS to be inline with INDI 2.0.0

drivers/telescope/lx200gemini.cpp, drivers/telescope/lx200gemini.h
Changed tabs to spaces, improved error handling, moved properties into better associated tabs.
=> General cleanup. Improve error checking and layout.

libs/indiclient/baseclient.cpp, libs/indiclient/baseclient_p.h
Referring to: https://github.com/indilib/indi/issues/1808
=> Don't call serverDisconnected if the client is not connected

drivers/ccd/ccd_simulator.cpp, drivers/ccd/ccd_simulator.h, drivers/ccd/guide_simulator.cpp, drivers/ccd/guide_simulator.h, libs/indibase/CMakeLists.txt, libs/indibase/fitskeyword.cpp, libs/indibase/fitskeyword.h, libs/indibase/indiccd.cpp, libs/indibase/indiccd.h
Preparation for adding XISF support (or other file formats)
=> Refactor CCD::addFITSKeywords()

drivers/dome/ddw_dome.cpp, drivers/dome/ddw_dome.h
Forgot I had this one done as well when making the previous PR (#1816).
=> Update DDW dome driver for new property functions.

drivers/telescope/lx200gemini.cpp, drivers/telescope/lx200gemini.h
Also fixed flip points not syncing with the mount, initial value of "start PEC at boot", and some pretty print.
=> Added Safety and Goto Limits

drivers/rotator/pegasus_falcon.cpp
1. The comparison of the answer of "MoveRotator()" is  restricted to 8 chars so that a correct result is generated.
2. A firmware bug in version1.4 sometimes reports success after a move command even though there was no movement of the rotator. This occurs regularly with small angles. Therefore angles of 0.01° or smaller are captured and an artificial OK is generated.
NOTE: This changes are required for full functionality of the Falcon rotator with the [new rotatorsettings module](https://invent.kde.org/education/kstars/-/merge_requests/793) in KStars.
=> Correct "MoveRotator()" command and handle firmware 1.4 bug of Falcon rotator

spec/libindi.spec
@knro Any chance you can update the spec file when you update the version in CMakeFile? I don't mind doing this, but that would keep them in sync better.
=> version_201: update spec to 2.0.1git

cmake_modules/UnityBuild.cmake, drivers/README.md, drivers/ccd/guide_simulator.cpp, scripts/indi-core-deb.sh, test/alignment/alignment_scope.h
Fixes various documentation typos and some source comment typos
=> Fix various typos

CMakeLists.txt, drivers.xml, drivers/telescope/CMakeLists.txt, drivers/telescope/planewave_mount.cpp, drivers/telescope/planewave_mount.h, libs/httplib-LICENSE, libs/httplib.h, libs/inicpp.h
Preliminary support for Planewave
=> Preliminary support for Planewave

drivers.xml, drivers/auxiliary/CMakeLists.txt, drivers/auxiliary/wanderer_cover_v4_ec.cpp, drivers/auxiliary/wanderer_cover_v4_ec.h
=> Driver for WandererCover V4-EC added

drivers/focuser/sestosenso2.cpp
Artistic Style: done
Testing Suite: done
Tested with latest Kstars 3.6.9:
- Move In: Ok
- Move Out: Ok
- AF Overscan: Ok
- Rapid IN/OUT movements: Ok
Fixes #1999
=> Sesto Senso 2 changing state before changing position

drivers.xml, drivers/rotator/CMakeLists.txt, drivers/rotator/wanderer_rotator_mini.cpp, drivers/rotator/wanderer_rotator_mini.h
The WandererRotator Mini (V2) is a groundbreaking rotator ideal for astrophotography. The most attracting feature of the WandererRotator Mini is the excellent rigidity based on the patented rotating structure. Within the maximum payload, the rotator guarantees absolutely zero flexure at any angle. The WandererRotator Mini is the most low profile rotator in its class and rotates at up to 4.5 degrees per second. In addition, WandererRotator Mini has very high positioning accuracy. With 1142 steps per degree, its resolution can reach up to 0.005 degrees, which provides the possibility of accurate de-rotation.
=> Driver for WandererRotator Mini V1&V2 added

drivers/auxiliary/pegasus_ppb.cpp, drivers/auxiliary/pegasus_ppba.cpp, drivers/auxiliary/pegasus_spb.cpp, drivers/auxiliary/pegasus_upb.cpp, drivers/telescope/lx200_OnStep.cpp, libs/indibase/defaultdevice.h, libs/indibase/indiweatherinterface.cpp, libs/indibase/indiweatherinterface.h
* Use modern INDI properties in WeatherInterface
* Save Parameter Range to config file
* Fix Warning and Alert ranges
=> Weather Interface Refactor

drivers/focuser/celestron.cpp, drivers/focuser/celestron.h, drivers/telescope/celestrongps.cpp, drivers/telescope/celestrongps.h
Closes issue #2026
I've tested the standalone driver changes, but I no longer have a Celestron mount to test the CelestronGPS driver changes.
=> SCT focuser interface compliance (#2026)

drivers/auxiliary/pegasus_upb.cpp, drivers/auxiliary/pegasus_upb.h
@knro , commented few lines which includes .ntp, nnp, i.e to set Count but not able to set Count with new INDI properties
=> Migrate Pegasus Upb

drivers.xml, drivers/auxiliary/CMakeLists.txt, drivers/auxiliary/Terrans_PowerBoxPro_V2.cpp, drivers/auxiliary/Terrans_PowerBoxPro_V2.h
Dear INDI developers：
We are the Terrans Industry, and here we apply to have our new product add the driver for Terrans PowerBox Pro V2  to INDI.
This is our first time writing an INDI driver, and we sincerely hope to get your help. Thank you very much.
This is the website of the product's ： https://www.terrans-industry.com/powerboxprov2
Driver name： Terrans PowerBox Pro V2
Version：V 1.0.0
Features: Terrans PowerBoxPro V2 is a comprehensive power and USB data management device used for remote astronomical photography. Equipped with four USB 3.1 ports (backward compatible with USB 2.0), two USB 2.0 ports, six 12VDC output ports, one 3V-12V DC adjustable port, one 19V NUC power supply port, and an external temperature and humidity sensor port. Supports a maximum power output of 180W.
This …
=> Add Terrans PowerBoxPro V2 Driver

drivers.xml, drivers/auxiliary/CMakeLists.txt, drivers/auxiliary/Terrans_PowerBoxGo_V2.cpp, drivers/auxiliary/Terrans_PowerBoxGo_V2.h
This is the official driver for Terrans PowerBoxGo V2, The old style properties have been modified.Thank you.
=> Add New Driver Terrans PowerBoxGo V2

drivers/auxiliary/STAR2000.cpp, drivers/auxiliary/STAR2000.h, drivers/auxiliary/arduino_st4.cpp, drivers/auxiliary/gpusb.cpp, drivers/telescope/astrotrac.cpp, drivers/telescope/celestrongps.cpp, drivers/telescope/crux_mount.cpp, drivers/telescope/ieqpro.cpp, drivers/telescope/ieqprolegacy.cpp, drivers/telescope/ioptronv3.cpp, drivers/telescope/lx200_OpenAstroTech.cpp, drivers/telescope/lx200_TeenAstro.cpp, drivers/telescope/lx200ap_v2.cpp, drivers/telescope/lx200pulsar2.cpp, drivers/telescope/lx200telescope.cpp, drivers/telescope/paramount.cpp, drivers/telescope/pmc8.cpp, drivers/telescope/rainbow.cpp, drivers/telescope/skywatcherAPIMount.cpp, drivers/telescope/synscandriver.cpp, drivers/telescope/telescope_simulator.cpp, drivers/telescope/temmadriver.cpp, libs/indibase/indiccd.cpp, libs/indibase/indifocuserinterface.cpp, libs/indibase/indigps.cpp, libs/indibase/indigpsinterface.h, libs/indibase/indiguiderinterface.cpp, libs/indibase/indiguiderinterface.h, obsolete/lx200ap.cpp, obsolete/skywatcherAltAzSimple.cpp
=> Initial work for guider and focuser interface refactor

drivers/auxiliary/Excalibur.cpp, drivers/auxiliary/alto.cpp, drivers/auxiliary/alto.h, drivers/auxiliary/deepskydad_fp1.cpp, drivers/auxiliary/dragonlight.cpp, drivers/auxiliary/flip_flat.cpp, drivers/auxiliary/giotto.cpp, drivers/auxiliary/light_panel_simulator.cpp, drivers/auxiliary/light_panel_simulator.h, drivers/auxiliary/pegasus_flatmaster.cpp, drivers/auxiliary/snapcap.cpp, drivers/auxiliary/wanderer_cover.cpp, drivers/auxiliary/wanderer_cover_v4_ec.cpp, drivers/focuser/alluna_tcs2.cpp, drivers/focuser/alluna_tcs2.h, libs/indibase/defaultdevice.h, libs/indibase/indidustcapinterface.cpp, libs/indibase/indidustcapinterface.h, libs/indibase/indilightboxinterface.cpp, libs/indibase/indilightboxinterface.h
Update light box and dust cap interfaces to new style
=> Update light box and dust cap interfaces to new style

libs/indibase/inditelescope.cpp
Telescope TrackStateSP property changes not applied
=> Fixed missing apply() on TrackStateSP property

drivers/dome/scopedome_arduino.cpp, drivers/dome/scopedome_arduino.h, drivers/dome/scopedome_dome.cpp, drivers/dome/scopedome_dome.h, drivers/dome/scopedome_usb21.cpp, drivers/dome/scopedome_usb21.h
- improve debug logging by decoding the command names.
- add logic to retrying shutter operation in case we lose connection before completion. This occasionally happens during winter if there's a lot of snow and ice on my dome. Apparently the voltage drops too much due to shutter motor needing more power than usual causing the controller to reset. This ensures the shutter will always close eventually.
=> Miscellaneous ScopeDome driver updates.

drivers/telescope/telescope_simulator.cpp
=> Fixed crash due not checking boundary values of the axis in telescope_simulator

drivers/telescope/scopesim_helper.cpp, drivers/telescope/telescope_simulator.cpp
This commit implies the necessary changes to work with  https://invent.kde.org/education/kstars/-/merge_requests/1391
=> Draft: Reuse calibration after rotation

drivers.xml, drivers/dome/CMakeLists.txt, drivers/dome/alpaca_dome.cpp, drivers/dome/alpaca_dome.h, drivers/weather/CMakeLists.txt, drivers/weather/weather_safety_alpaca.cpp, drivers/weather/weather_safety_alpaca.h
I added two alpaca devices that can be configured.
I did not have the opportunity to test every commands for the alpaca dome because the remote site I use only permits opening the roof.
I guess others should also work.
=> Feat(): alpaca dome and alpaca weather safety

drivers/telescope/lx200gps.cpp
unpark was not updating values and following move failed
=> fix unpark lx200gps.cpp

drivers/auxiliary/cheapodc.cpp, drivers/auxiliary/cheapodc.h
Allows for up to 4 additional power outputs added to the core 2 dew controller outputs. Each of the 4 additional outputs may be disabled, configured to track the core dew controller outputs, have independent PWM control or Boolean full on/full off control. Added control of these new outputs to the Main Control tab.
=> Upgrade to add support for CheapoDC v2.2.0. 

drivers/ccd/guide_simulator.cpp, drivers/ccd/guide_simulator.h, drivers/telescope/telescope_simulator.cpp, drivers/telescope/telescope_simulator.h
Adds controls for seeing, periodic error. 
Adds controls to add random RA and DEC position noise, and linear RA and DEC drift to the guide simulator. 
Adds the ability to simulate DEC guiding pulse backlash in the telescope simulator.
Refactors some of the code in guide_simulator.
=> Improve guide simulator

drivers.xml, drivers/auxiliary/CMakeLists.txt, drivers/auxiliary/gemini_flatpanel.cpp, drivers/auxiliary/gemini_flatpanel.h
Driver for Gemini automated flat panels.
Manufacturer: Gemini
Website: https://gemini-astro.com/
Aliexpress Store: https://www.aliexpress.com/item/1005008429423723.html
The manufacturer was kind enough to provide a sample of the Rev 2 product for development and testing.
This driver also tries to implement the protocol for Rev 1 of the product though I didn't have the device to fully test the driver.
I tried to add the listing with some screenshots as is stated in the docs, but the editor was not working that well for me.
I'm no sure how to reference it here, the only link I have is:
https://indilib.org/devices/listings/jrhuerta.html
=> Add driver for Gemini Flatpanels (Rev 1 and 2)

libindi.pc.cmake
=> Pass -lindiclient in pkg-config

drivers.xml, drivers/auxiliary/CMakeLists.txt, drivers/auxiliary/wanderer_dew_terminator.cpp, drivers/auxiliary/wanderer_dew_terminator.h
=> Driver for Wanderer Dew Terminator added.
