indilib/indi

3rdparty/indi-qhy/qhy_ccd.cpp
3rdparty/indi-qhy/qhy_ccd.h
macosx/INDI Server/INDI Server.xcodeproj/project.pbxproj

Changes to QHY driver necessary to build it on OSX with libqhy 1.6.

QHY driver added to OSX bundle again

---

3rdparty/indi-asi/asi_ccd.cpp

Line 561, 621: change from %d to %.2f

Proper format for "SetControlValue" debug message.

---

3rdparty/indi-asi/asi_ccd.cpp

Regardless of the status returned by the ASIStartExposure() it was called 3 times in a row.

ASI: fix triple calling of ASIStartExposure()

---

libindi/base64.c

Complete rewrite of to64frombits() - gives 2x the performance of the old implementation.
Here are some test results on RPI3:
memcmp of two encoded buffers: 0 (len1 = 53333336 len2 = 53333336)
Base64 encode (INDI) took 18955ms
Base64 encode (FAST) took 8155ms
FAST took 43.0% of the time that INDI used.

indilib make base64 encoding 2x faster

---

libindi/base64.c

Jasem there was a wried corner case in the code when one "=" had to be added the last byte was off by 2... I think now it is fixed. I wrote  a rigorous auto tests which does not fail any more. The good news is that the fix does not affect the performance at all...

libindi: fixed fast base64 encoding - the last byte was wrong sometimes

---

3rdparty/indi-asi/99-asi.rules
libindi/indidriver.c

* remove buffered write of BLOBS  - did not test the performance compared to buffered version, but fwrite() does an extra copy into the stdio buffer which written at a later time with write() syscall,  so using only write() should be faster - removed one unnecessary copy.
* indi_asi_ccd: increase usbfs_memory_mb to 200mb so that ASI1600 can work with other cameras on the same Linux host, new SDK is on the way in a day or two. ZWO guys did a good job on this.

Remove buffered write of BLOBS some and ASI optimized

---

libindi/CMakeLists.txt

Currently the AlignmentDriver library is only built for "Linux" platforms. However, it's a dependency and must be linked on all platforms causing linker errors. I've removed the platform condition and it builds and links on OSX with no additional changes.

Build alignment module on all platforms

---

cmake_modules/FindUSB-1.cmake

I'm working on building indi/kstars on OSX and ran into a problem with libusb when installed with homebrew. This patch adds an additional header search path for cmake and allows indi to build on OSX.

libusb paths for osx w/homebrew

---

3rdparty/indi-dsi/CMakeLists.txt
3rdparty/indi-dsi/DsiColorIII.cpp
3rdparty/indi-dsi/DsiColorIII.h
3rdparty/indi-dsi/DsiDeviceFactory.cpp

This should add support for the DSI Color III. I don't have a DSI Color III to test with, but I have verified that this doesn't break support for my DSI Pro I.

Add initial support for DSI Color III.

---

libindi/drivers/telescope/lx200driver.cpp

This change reverts a recent change made for OnStep support. The OnStep firmware was recently changed to support the standard LX200 set longitude command (:SgDDD:MM#). The previous sign change may have broken support for other LX200-protocol mounts that use this code (though I don't have any of these devices to test with).
Adding @azwing in case he has input.

Remove sign from LX200 set longitude command

---

3rdparty/indi-gphoto/gphoto_driver.cpp
3rdparty/indi-sbig/sbig_ccd.cpp
3rdparty/indi-sbig/sbig_ccd.h

Just a few small contributions to remove some compiler warnings.
I don't have hardware to test these changes, but thought we could discuss them here.

Fix constant string conversion to non-const char*

---

3rdparty/indi-sbig/sbig_ccd.cpp

Some little changes to get 9x9 binning work for SBIG STF-8300M CCD

Get 9x9 binning mode work for SBIG CCD's

---

libindi/CMakeLists.txt
libindi/libs/indibase/indiproperty.cpp
libindi/libs/indicom.c

Make possible to build INDI for Android. Almost all features of Windows build are the same for Android build.

Build INDI(Qt client) for Android

---

libindi/drivers/dome/roll_off.cpp

Sorry the logging messages when the park-aware button was used were both incorrect and confusing. Hope this improves it a bit....
See related discussion here http://www.indilib.org/forum/ekos/1598-feedback-for-the-new-feature-scope-park-aware.html

Fix the confusing log messages I added in the last commit

---

3rdparty/CMakeLists.txt
3rdparty/indi-gige/AUTHORS
3rdparty/indi-gige/CMakeLists.txt
3rdparty/indi-gige/INSTALL
3rdparty/indi-gige/README
3rdparty/indi-gige/config.h.cmake
3rdparty/indi-gige/indi_gige_ccd.xml
3rdparty/indi-gige/src/ArvFactory.cpp
3rdparty/indi-gige/src/ArvGeneric.cpp
3rdparty/indi-gige/src/ArvGeneric.h
3rdparty/indi-gige/src/ArvInterface.h
3rdparty/indi-gige/src/BlackFly.cpp
3rdparty/indi-gige/src/BlackFly.h
3rdparty/indi-gige/src/config.h
3rdparty/indi-gige/src/indi_gige.cpp
3rdparty/indi-gige/src/indi_gige.h
cmake_modules/FindARAVIS.cmake
cmake_modules/FindGLIB2.cmake

This commit enables initial support for Point Grey machine vision
cameras, and in general, for any camera supported through Project
Aravis.
These cameras are mainly geared towards high speed video streams, and do
not typically support very high exposure times. This driver attempts to
operate the camera in the most manual mode possible. Because most
cameras slave the programmable exposure time to the configured
framerate, which cannot be set lower than 1.0 FPS, out of the box these
cameras do not support longer exposure times, unless the frame rate is
manually disabled.
Unfortunately, this is a vendor-specific operation, here implemented for
the "BlackFly" family from Point Grey.
However, typically, it is not so difficult to set disable the frame
rate. Look in arvcamera.c (in Project …

Initial support for GigE machine vision cameras.

---

libindi/drivers/filter_wheel/ifwoptec.cpp

Typo correction to use plural for Filter label in driver interface
The Warning was due to space char in the REGEX string. replace the char by the string [:space:]

Fix compilation warning

---

debian/libindi/control

This enables (AFAIK) to build libindi on trusty and harms nothing (trusty just do not have generic libfitsio).

Add libcfitsio3 to dependencies to let it build on trusty

---

3rdparty/indi-aagcloudwatcher/indi_aagcloudwatcher.xml.cmake

I did it. First contribution.
aag cloudwatcher device will appear again in the list of weather device.

fix device group

---

.travis.yml
travis-ci/deps-linux.sh
travis-ci/deps-osx.sh
travis-ci/install-gtest.sh

With the current push to get kstars running on OSX I thought it would be a good time to get indilib CI running on an OSX Travis instance.

Add OSX TravisCI configuration

---

travis-ci/deps-osx.sh

I didn't have BUILD_INSTALL_GTEST defined in my personal TravisCI settings so I missed this one. It now builds correctly but there are no unit tests running on TravisCI or on my local machine.
```
Seans-MBP:test seanhoughton$ ctest -V
UpdateCTestConfiguration  from :/Users/seanhoughton/Code/indi/libindi/test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/seanhoughton/Code/indi/libindi/test/DartConfiguration.tcl
Test project /Users/seanhoughton/Code/indi/libindi/test
Constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
```

Fix gtest on osx

---

cmake_modules/FindUSB-1.cmake

MacPorts installs the libusb-1.0 headers to /opt/local/include/libusb-1.0/ by default. This path was missing in the include directory search paths.

Add include path for libusb installed from macports

---

libindi/drivers/ccd/ccd_simulator.cpp

the simulator now correctly draws fields even at north pole, ie centered on Polaris

Correct a minor math error in ccd simulator

---

3rdparty/indi-asi/asi_ccd.cpp

There are 2 changes in this PR. Not sure if you want to take both but it seems to have helped with the exposure looping on my PC with my camera. Although I'm not 100% convinced that this solves the problem...
1) **Prevent an infinite loop** in the while(true) loop that waits for exposure to complete.
I was able to create an infinite loop by setting EKOS to take continuous 2 sec exposures with the camera using the focus module 'framing' option. Then disconnect the driver and re-connect. It gets stuck in this while loop. I added a debug statement in the loop and could see it being logged continuously.
2) **Set the the usb bandwidth to 40** (auto) on connect. I noticed a strange problem on my PC. Not sure if you also see this.... To replicate: Set debug log on, take a few exposures, now go …

Prevent infinite loop in indi-asi and also set bandwidth to 40 on connect

---

libindi/drivers/video/v4l2driver.cpp
libindi/libs/webcam/v4l2_base.cpp
libindi/libs/webcam/v4l2_base.h

Worked in the V4L2 driver around the problem of corrupted frames on my DMX21.
I tested with a few other webcams, but of course this would need more test samples.
I tried very hard to conform strictly to the V4L2 spec in my changes. There are portions of the code (which I didn't touch) indicating much fiddling with buggy drivers :) I don't think I broke anything there, but well, as long as the problematic device isn't tested...
There's much to do here to clarify the code, perhaps I'll return to this soon.
I have another rework for cropping, but the feature isn't much used probably so that can wait.

Fixing DMX21/V4L2 corrupted frames

---

3rdparty/libfli/libfli-camera-usb.c

Proline PL09000 camera resulted in this and the cooler did not work:
2016-12-30T20:29:17: FLIGetCoolerPower() failed. Bad address. 
2016-12-30T20:29:16: FLIGetCoolerPower() failed. Bad address. 
2016-12-30T20:29:15: FLIGetCoolerPower() failed. Bad address. 
Now it shows correct cooler power and temperature

indi_fli_ccd: fix cooler to work with PL9000

---

libindi/libs/webcam/v4l2_base.cpp
libindi/libs/webcam/v4l2_base.h

Make sure source compatibility is preserved with 3.x kernels:
- Field 'flags' is available in the V4L2 API starting kernel 3.17,
- Timestamps were introduced in the V4L2 API starting kernel 3.15,
- DMABUF was introduced in the V4L2 API starting kernel 3.8.
Tested with kernel headers 3.6, 3.8, 3.9, 3.16, 3.17, 3.19, 4.4.

Fixes #137 - compile issue in V4L2 client with 3.x kernels.

---

3rdparty/indi-fli/fli_ccd.cpp
3rdparty/libfli/libfli-camera-usb.c

libfli: Make FLIGrabRow() return error on failure it used to return always success.
indi_fli_ccd: handle correctly broken frames.
indi_fli_ccd: fix wrong exposure time left display.

indi_fli_ccd - bugfixes

---

libindi/drivers/telescope/lx200pulsar2.cpp
libindi/drivers/telescope/lx200pulsar2.h

This version deals with time outs in the communication with the Pulsar controller in the proper way. After a time out the input is cleaned so that commands and responses are resynchronized.
It also fixes a typo in the Unpark routine that prevented unparking of the mount.

Modifications in pulsar2

---

libindi/drivers/dome/roll_off.cpp

This fixes a small bug in the roll off simulator which prevented it being used in the 'Observatory startup procedure' of ekos scheduler. 
During the startup procedure, on unpark, it temporarly changed to IPS_ALERT which triggered an error in the scheduler which causes it to stop the schedule.

Small bug fix in roll off simulator

---

libindi/drivers/telescope/lx200_10micron.cpp
libindi/drivers/telescope/lx200_10micron.h
libindi/drivers/telescope/lx200driver.cpp
libindi/drivers/telescope/lx200driver.h
libindi/drivers/telescope/lx200generic.cpp
libindi/libs/indicom.c
libindi/libs/indicom.h

For example as tested on a GM2000HPS : 
```
SCOPE   64.116921 sec   : <setObjectRA>
SCOPE   64.116961 sec   : CMD <:Sr 00:10:03.24#>
SCOPE   64.161167 sec   : CMD <:Sr 00:10:03.24#> successful.
SCOPE   64.161200 sec   : <setObjectDEC>
SCOPE   64.161218 sec   : CMD <:Sd +59:14:45.60#>
SCOPE   64.237205 sec   : CMD <:Sd +59:14:45.60#> successful.
SCOPE   64.237257 sec   : <Slew>
SCOPE   64.237263 sec   : CMD <:MS#>
SCOPE   64.361598 sec   : RES <0>
INFO    64.361628 sec   : Slewing to RA:  0:10:03.24 - DEC: 59:14:45.60
```

ultra precision goto

---

libindi/drivers/filter_wheel/quantum_wheel.cpp
libindi/drivers/filter_wheel/quantum_wheel.h

For some reason I cannot set default port with serialConnection->setDefaultPort("/dev/ttyACM0") but it does not impact driver's functionality. It works as expected.

Migrate Quantum Filter Wheel to updated connections plugin framework

---

3rdparty/indi-qhy/qhy_ccd.cpp

This is the best approach so far for QHY 5P-II C. I look into the driver if I can fix and make it better.

Set a certain USB speed for QHY 5P-II C camera by default

---

libindi/drivers/telescope/skywatcherAPIMount.cpp
libindi/drivers/telescope/skywatcherAPIMount.h

First commit:
The driver flooded the KStars status bar with tracking messsages. Now it is rewritten to give reasonable information over time.
Second commit:
I noticed that the Virtuoso mount has a constant drift on the Alt axis downwards in tracking mode and it makes impossible to keep the target in the FOV with telescope+CCD configuration. This mount does not have PEC implementation thus I checked the drift and it was about 0.009 degree/minute. I added support for this static compensation in the driver and works very well. I named SoftPEC (software PEC). I will document it after merge on the wiki.

Fix status messages and SoftPEC implementation in skywatcherAPIMount driver

---

libindi/drivers/video/v4l2driver.cpp
libindi/drivers/video/v4l2driver.h
libindi/libs/indibase/indiccd.cpp
libindi/libs/webcam/v4l2_base.cpp

This should fix switching frame characteristics with a V4L2 CCD driver.
Tested switching back and forth fields (MJPEG) type, frame sizes and streaming robustness.
Streaming robustness is a bit feeble for now as it is the recorder which selects frame while the V4L2 driver remains at full rate. Most often KStars breaks because of the data rate.
The crash was caused by an invalid buffer copied, a bit difficult to reproduce in the debugger. Use "set disable-randomization off" in gdb to get in a situation closer to the normal use.
MJPEG is reported as not compressed by the kernel, so this is now patched in is_compressed(). If there are other useful formats like this observed in such situation, feel free to add a case to the switch.
There as also a problem when reopening the device after …

Bugfix  v4l2 compressed formats

---

libindi/drivers/focuser/focuslynx.cpp
libindi/drivers/focuser/focuslynxbase.cpp

to set correctly communication channel with the HUB.
As coding related to TCP is not done yet, set only SERIAL one for now.

use setFocuserConnection() instead unregister fonction

---

libindi/drivers/video/v4l2driver.cpp
libindi/drivers/video/v4l2driver.h
libindi/libs/webcam/v4l2_base.cpp
libindi/libs/webcam/v4l2_base.h

This pull request should allow users of USB CCDs to better manage exposures.
- Added exposure left report to client.
- Fixed various start/stop/restart/abort situations which would lock the driver logic up.
- Implemented CCD_CAN_ABORT logic over those fixes.
- A few log changes to make driver behavior clearer.
Basically, it allows the end-user to abort that 20-minute exposure launched by mistake.
It also makes starting and stopping streaming and exposure more robust.

Feature  v4l2ccd exposure left

---

3rdparty/indi-dsi/99-meadedsi.rules

It's a fix for ATTR{idProduct}=="01ed". Tested on the camera and it works fine.

Fix for unrecognized meadedsi camera model (01ed)

---

3rdparty/fliusb/fliusb.c

This should work... I did not pay attention that the API
changed since 4.6 and then changed again since 4.9...

fliusb: another attempt to fix build for linux 4.8

---

3rdparty/CMakeLists.txt
3rdparty/fxload-libusb/CMakeLists.txt
3rdparty/fxload-libusb/README.md
3rdparty/fxload-libusb/ezusb.c
3rdparty/fxload-libusb/ezusb.h
3rdparty/fxload-libusb/fxload.c
3rdparty/fxload-libusb/get_sources.sh

Newer cameras (for instance, QHY5III290) require fx3 firmware, unsupported by the fxload provided by most distributions.

Add fxload-libusb for QHY new cameras

---

3rdparty/indi-asi/asi_ccd.cpp

Fix binning/roi validation: first bin w/h, then run validation to ensure it follows ASI restrictions (w%8 = 0; h%2 = 0).

Asi binning fix

---

3rdparty/indi-qhy/qhy_ccd.cpp

bayer patterns were wrong, there are no GBGR and GRGB patterns...

indi-qhy: fix bayer patterns

---

libindi/libs/webcam/v4l2_base.cpp

This should remove warnings issued during the x64 build.

Fixed warning requiring "*" format specifier to be of type "int".

---

libindi/drivers/video/v4l2driver.cpp

This fixes the current iteration of the crash described #242.
I'll need to clarify why AbsExposureN is null in that context, and what are the consequences.
Basically, in the scenario described, ImageAdjustNP does not contain "Exposure (Absolute)".

Fixed debug log using AbsExposureN while possibly null.

---

libindi/CMakeLists.txt

Testing for flag _FORTIFY_SOURCE with warnings as error to determine whether CMake will be able to test for library dependencies without optimization using the local compiler. Fixes #260 for CMake 3.6.3 with gcc 4.9.4 on Gentoo.

Avoid using _FORTIFY_SOURCE on systems where compiler predefines it.

---

3rdparty/indi-mgen/indi_mgenautoguider.xml
3rdparty/indi-mgen/mgenautoguider.cpp
3rdparty/indi-mgen/mgenautoguider.h
3rdparty/indi-mgen/mgio_insert_button.h
3rdparty/indi-mgen/mgio_read_display_frame.h

This fixes #200.
As the remote buttons are a ATMOST1 type, there can happen that one of them is released by the user when clicking before the message is handled by the driver. This is especially visible on a remote server. In that case looking for a "ON" switch while managing inputs caused a null dereference.

Fix repeated keys issue in MGen driver

---

libindi/drivers/video/v4l2driver.cpp
libindi/drivers/video/v4l2driver.h

First step of clarifying issues with V4L2 exposures not working, and stuff around exposure-related controls.
This to support follow-ups investigating cases of missing absolute exposure exposure control, and weird offset frame in FITS files. Also, possibly switching from manual exposure to aperture priority is not enough for certain cameras, which might also need some other settings such as white balance to be reset.

Bugfixing V4L2 exposures #1

---

libindi/drivers/video/v4l2driver.cpp
libindi/libs/webcam/v4l2_base.cpp

This is what the PR displays in the debug console (reversed here for clarity):
```
2017-07-12T17:42:07: Found 4 V4L2 adjustments 
2017-07-12T17:42:07: - Brightness 
2017-07-12T17:42:07: - Gamma 
2017-07-12T17:42:07: - Gain 
2017-07-12T17:42:07: - Exposure (Absolute) (used for absolute exposure duration) 
2017-07-12T17:42:07: Found 1 V4L2 options 
2017-07-12T17:42:07: - Exposure, Auto (used for manual/auto exposure control) 
```
This to understand which control is used in the context of the recent issues with exposure.

Attempt to fix V4L2 exposure issue for devices not providing manual/auto control

---

libindi/drivers/telescope/lx200ap.cpp

This change will make sure a data communication error will not cause the pier side to be set erroneously.
The error is reported to the debug log.

More robust handling of reading pier side from mount

---

libindi/libs/indicom.c

Linux and OSX builds fail when configured to build only the client library
> cmake -DINDI_BUILD_SERVER=OFF -DINDI_BUILD_DRIVERS=OFF -DINDI_BUILD_CLIENT=ON -DINDI_BUILD_QT5_CLIENT=OFF

Fix compile error when building only the indi client

---

libindi/drivers/telescope/lx200gotonova.cpp
libindi/drivers/telescope/lx200gotonova.h

Changes for how GotoNova 8400 Kit handles certain commands, as documented in the hand controller. These are for the calendar date, UTC offset, longitude and latitude.

Changes for how GotoNova 8400 Kit handles certain commands

---

libindi/drivers/telescope/ieqpro.cpp
libindi/drivers/telescope/lx200ap.cpp
libindi/drivers/telescope/lx200basic.cpp
libindi/drivers/telescope/lx200generic.cpp
libindi/drivers/telescope/lx200gotonova.cpp
libindi/drivers/telescope/lx200pulsar2.cpp

These drivers set the tracking state to SCOPE_IDLE after a synchronize event.  I don't see why this was done since all a sync does is adjust the stored position of the mount and shouldn't cause any change in motor state.
I thought I'd bring this up - perhaps we can have the authors of these drivers review?

Removed code that set tracking state to SCOPE_IDLE after sync event.

---

libindi/drivers/auxiliary/sqm.cpp
libindi/drivers/auxiliary/sqm.h

I've added USB connectivity feature to the SQM driver.
Can you test that I have not broken the TCP connectivity feature as I only have a USB device to test with?
Its working fine with my SQM-LU device.

Adding USB connectivity to SQM driver

---

libindi/drivers/telescope/lx200_OnStep.cpp
libindi/drivers/telescope/lx200classic.cpp

On both LX200Classic and OnStep instead of comparing the return value of setMaxSlewRate() for being less than zero we compare instead value[0].
Besides, it seems that the current release of OnStep does not implement this command.

LX200: fix check of return value for setMaxSlewRate()

---

3rdparty/indi-inovaplx/inovaplx_ccd.cpp

I changed the minimum and maximum exposure settings with real ones in inovaplx. These settings apply to all i.Nova cameras of the PLx series. (not all the cameras of this series exceed 1000s exposure, but can reach sub-ms exposure for solar observation)

[inovaplx] changed min/max exposure setting and gain/blacklevel tab

---

3rdparty/indi-eqmod/align/pointset.cpp

At the moment if you load an AlignData.xml file, you can never save it again because of the rounding error in the floating point comparison.
Worst the file is cleared because it is opened for write before this test.
This patch fix the problem by comparing the coordinates to 1E-4 (10 meters) and opening the file after the test.

Fix geographic coordinate comparison

---

libindi/libs/indibase/indidome.cpp

More updates to point math based on the suggestions of changes from ferran
Added snooping to get pier side from the mount
Pier side handling is changed considerably
- It now starts in the unknown state
- State of the side is only set when a snoop message arrives, or user pushes the ui button
Slaving code will use the pier side from mount if it's been set, otherwise it will revert to internal calulations
When a 'target goto' is recieved, pier side is unset and the initial slave movement will be based on the calculated pier side to anticipate where the mount is going, rather than where it is at the start of the move
All of these changes are tested on my setup with the EQ8 driven by the Eqmod driver, and the NexDome using the webcam setup pointed at marked shutter to validate pointing and …

Dome fixes

---

libindi/drivers/focuser/focuslynx.cpp
libindi/drivers/focuser/focuslynx.h
libindi/drivers/focuser/focuslynxbase.cpp
libindi/drivers/focuser/focuslynxbase.h

Remove unnecessary procedure as Ekos is able to start correctly both interfaces from the driver.
Improve simulation as absolute focuser (Wasn't correct sequence of events before)
Set options as Simulation and debug in only one driver (F2) to avoid confusion.
Change setting depend if focuser is an absolute or a relative one to reflect correct options (Max travel ticks R or RW)
Allow selection of "no focuser", "ZZ" value, to allow Ekos to start all drivers. FocusBoss manage this case too, without error if commands are sent to the focuser.
Activate network/serial connection !! Hub firmware >= 2.0.4 to works correctly !!

Cleaning code and other improvements

---

libindi/drivers/telescope/ioptronHC8406.cpp
libindi/drivers/telescope/ioptronHC8406.h

After the mount  firmware update (v1.1 ->v1.12) it is posible to start/stop tracking (:RT9# stop, :RT2# start) so implement SetTrackEnabled() using this CMDs. 
Other minor changes:
.- More descriptive properties
.- New ioptronHC8406Init() function. This mount doesn't report to much so I initialize the mount in order to get a consistent state between GUI and the mount at start time: Unparked, Guide rate x0.5, tracking stopped
IMPORTANT to note: firmware v1.12 has a awfull bug. Guide commands :Mexxx#/:Mwxxx# stop working.  Also  move commands :Me#/:Mw# are broken. Only RA axes, the equivalent on DEC axes :Msxxx#,.. work perfect. Nothing to do with the driver. I asked ioptron to fix it.

Start/Stop tracking commands. Init mount state at start time.

---

libindi/libs/webcam/v4l2_base.cpp

Apparently Raspberry Pi Camera v2 is managed by a kernel driver which
marks JPEG frames as uncompressed. This is weird.
Pull this change if required, this is probably innocuous as JPEG frame should always be considered compressed.

Override JPEG as V4L2 compressed format systematically.

---

3rdparty/indi-qhy/qhy_ccd.cpp

Hi,
I noticed in http://indilib.org/forum/ekos/2219-items-from-last-night-s-indi-ekos-kstars-session.html?start=48#20094 with up to 7 QHY cameras and the loops in the driver ignore the array end that holds the cameras.
Karsten

limit the QHY devicecount to prevent writing to random memory

---

libindi/drivers/telescope/skywatcherAPI.cpp
libindi/drivers/telescope/skywatcherAPI.h

The comments describing the "SetMotionMode" function "Func" parameter
were incorrectly labelled.
The changes in this commit have no affect on the code itself which was handling the parameters correctly. However it makes sense to correct the commenting as it only serves to add confusion otherwise.

Correct SetMotionMode Comments in skywatcherAPI Driver

---

libindi/drivers/weather/gason.cpp

Now that weather here in Finland has got colder, I noticed that Wunderground weather driver started to give error about unquoted key. I debugged this a bit and noticed that the problem was that negative numbers weren't handled correctly due to an extra break; statement added in commit c6be880a80be51604bc0a068aeb65bf61567307b

Fix handling of negative numbers in JSON

---

libindi/CMakeLists.txt
libindi/drivers.xml
libindi/drivers/auxiliary/snapcap.cpp
libindi/drivers/auxiliary/snapcap.h

This pull request adds driver for Gemini SnapCap (http://www.geminitelescope.com/snapcap-motorized-tube-ota-cap/) motorized OTA cap and flat light. It's mostly the same driver as for Flip Flat but with some serial protocol and behavior differences. The controller is Arduino based and uses the same USB ids as any other Arduino Uno so specific udev rules are unfortunately not possible, but otherwise something like this works:
`SUBSYSTEM=="tty", ATTRS{idVendor}=="2a03", ATTRS{idProduct}=="0043", SYMLINK+="snapcap", ENV{ID_MM_DEVICE_IGNORE}="1"`
Also the current firmware version doesn't provide very good way of identifying the device and whether it has a light or not so I just read the firmware version and assume the device is there if the response looks valid and that it has a light.

Driver for Gemini Snapcap 

---

libindi/libs/indibase/indiweather.cpp
libindi/libs/indibase/indiweather.h

Noticed I couldn't set GPSD as snoop device for Wunderground driver and discovered that the snoop device field didn't actually do anything so added the necessary code to update and save the device name.

Fix setting and saving GPS snoop device in weather base class

---

libindi/drivers/focuser/tcfs.cpp

When connecting to TCFS focuser, check that a "!" response is received when FMMODE command is issued. This helps confirm that the device is in fact the TCFS focuser and not some other serial device. It is also mandatory for further comms. TCFS manal notes: "A successful return from this command (“!” LF CR) is required before the TCFS/ TCF-S3 will accept any other user commands."
A retry loop is included as the manual also warns that: "Warning: The FMMODE command may need to be executed more than once to successfully exit the serial AUTO loops. The user will see the return character for FMMODE after the serial AUTO loop has been successfully exited.

TCFS check for FMMODE response on connect

---

libindi/drivers/telescope/lx200ap.cpp
libindi/drivers/telescope/lx200ap.h
libindi/drivers/telescope/lx200apdriver.cpp
libindi/drivers/telescope/lx200apdriver.h

The Astro-Physics mounts use a slightly different serial command for guide movements than the generic LX200 so this patch creates an overriding method for the lx200ap driver to handle these requests.
I've been using it for several imaging sessions now and the guide results are very good under PHD2.

Fix LX200AP pulse guide to use proper AP serial commands

---

libindi/drivers/telescope/lx200ss2000pc.cpp
libindi/drivers/telescope/lx200ss2000pc.h

This change adds a configurable slew accuracy parameter to the SkySensor 2000 PC hand controller. 
The previous default difference between current and target RA/DEC was 0.01, and that caused slews to not end. Work around was to Abort the slew manually. 
Now there is no need for this workaround. One can set the slew accuracy to a different value than the default 3 arc minutes. On my Vixen GPDX with the Sky Sensor 2000 PC ROM version 2.05, a value of 4 arc minutes seems to work well indoors.

Add Slew Accuracy to Sky Sensor 2000 PC

---

libindi/drivers/telescope/lx200ss2000pc.cpp
libindi/drivers/telescope/lx200ss2000pc.h

The setting of latitude and longitude on Sky Sensor 2000 PC is different from the generic LX200. First, a space is required between the Sg and St command and its arguments. Also, seconds can be used unlike the generic LX200.

Correct setting of latitude and longitude on Sky Sensor 2000 PC

---

libindi/drivers/telescope/lx200ap.cpp
libindi/drivers/telescope/lx200ap.h
libindi/drivers/telescope/lx200apdriver.cpp
libindi/drivers/telescope/lx200apdriver.h

This modification allows changing the guide rate used by the lx200ap driver to 0.25x, 0.50x, or 1.0x.  I've tested changing the guide rate and doing a calibration run with PHD2 and the guide rate appears to change as expected.

Lx200ap setguiderate

---

README.md

I had to install those in order to build all 3rd party packages on Debian GNU/Linux 9 (stretch)

Added 3 new dependancies for 3rd party build

---

libindi/CMakeLists.txt

If I try to compile only the client config.h is not gerated -> compilation error
I am configuring the build as follow:
cmake .. -DINDI_BUILD_SERVER=OFF -DINDI_BUILD_DRIVERS=OFF -DINDI_BUILD_CLIENT=ON -DINDI_BUILD_QT5_CLIENT=OFF

config.h always generated

---

3rdparty/indi-eqmod/skywatcher.cpp

As I have a HEQ5 mount I was interested in seeing how the alignment changes looked like and first tried with simulator only to see it crash due to buffer overflow in line 430 of skywatcher.cpp:     sprintf(boardinfo[1], "%04lx", (MCVersion >> 8));
In gdb I noticed the MCVersion variable wasn't set and contained some garbage which sprintf then happily tried to print to too small buffer. Removing this one return statement makes the driver initialize the simulated MountCode and MCVersion variables correctly and things work again.

Fix crash with eqmod simulator due to uninitialized variables

---

3rdparty/indi-qsi/qsi_ccd.cpp

On my QSI 660 WSG the call to QSICam.get_AntiBlooming(&cAB); sets the value of 3 in cAB.  Since it is only a 2 element vector this causes an indi driver crash.  Added a bounds check to fix the crash while I look to see if the QSI api itself has been updated with additional enum values for anti-blooming.

Added bounds check to antiblooming switch index

---

libindi/drivers/auxiliary/snapcap.cpp

I had made rather embarrassing typo in the name the driver returns and also noticed the controller sometimes gives a corrupt reply to first request which required connecting twice, which isn't good for my remote setup so I added code to retry handshake once which fixes this.

Small fixes to SnapCap driver

---

libindi/libs/indibase/baseclient.cpp

OpenBSD and FreeBSD needs this header otherwise build will fail with undeclared identifiers (AF_INET, SOL_SOCKET, etc).

Include sys/socket.h for AF_INET

---

3rdparty/indi-eqmod/align/align.cpp

After recent revert of alignment subsystem I reenabled only WITH_ALIGN_GEEHALEL option and WITH_ALIGN disabled and noticed that align.cpp didn't compile anymore like it did when I had both options enabled before the alignment changes. From the errors it was clear it uses strcmp and trigonometric functions without including their headers directly and they happen to get included in usual configuration where both alignment systems are enabled.

Add missing includes for strcmp and sin/cos in eqmod

---

libindi/libs/indibase/indilightboxinterface.cpp

This is the delete() usage I mentioned earlier.

Use free instead of delete as the memory is from malloc and realloc

---

libindi/CMakeLists.txt
libindi/drivers/telescope/lx200ap.cpp
libindi/drivers/telescope/lx200ap_experimental.cpp
libindi/drivers/telescope/lx200ap_experimental.h
libindi/drivers/telescope/lx200ap_experimentaldriver.cpp
libindi/drivers/telescope/lx200ap_experimentaldriver.h
libindi/drivers/telescope/lx200apdriver.cpp
libindi/drivers/telescope/lx200apdriver.h

This update contains improvements to the lx200ap_experimental telescope driver.  
Changes:
- checks for 'V' level of firmware and will not load if not present
- adds ability to choose from 4 park positions as defined by Astro-Physics
- better mount initialization

Lx200ap experimental 20171230

---

README.md

- Files: README.md
- Changes: checkout
Why co is not OK?
Actually "co" is not a git command it is a alias. If someone (who doesnt have exp. about VCS) tried to execute that he got errors, and he open a issue about that. I think this is better way to do that.

[README] Checkout alias (co) changed as Checkout

---

3rdparty/indi-apogee/apogee_ccd.cpp
3rdparty/indi-apogee/apogee_ccd.h
3rdparty/indi-dsi/CMakeLists.txt
3rdparty/indi-dsi/DsiDevice.cpp
3rdparty/indi-qhy/qhy_ccd.cpp
3rdparty/libapogee/CMakeLists.txt
3rdparty/libapogee/apgHelper.cpp
3rdparty/libapogee/linux/GenOneLinuxUSB.h
3rdparty/libqhy/CMakeLists.txt
macosx/INDI Server/CMAppDelegate.m
macosx/INDI Server/INDI Server-Info.plist

This pull request will apply the OS X installation path changes for KStars, INDI Server, and home-brew INDI as was discussed by Peter and myself.  In a home-brew install, the firmware and other camera support files will install to subfolders in /usr/local/lib/indi/DriverSupport.  Currently in a home-brew install, these subfolders will be for DSI, Apogee, and QHY files.  For KStars and INDIServer, these files will be placed in a similar manner into the app bundle in /Contents/Resources/DriverSupport. Thus at runtime, if the INDIPrefix Environment variable exists on OS X such as in KStars and INDI Server, the drivers will look for their files in this folder in the app bundle.  But if it doesn't exist, such as in a home-brew install, then it will look in the default folder listed above. …

Path updates and OS X Changes

---

libindi/drivers/telescope/lx200_10micron.cpp
libindi/drivers/telescope/lx200_10micron.h

SCOPE   16.312062 sec   : <setLocalDate>
SCOPE   16.312073 sec   : CMD <:SC2018-01-30#>
SCOPE   16.492003 sec   : CMD <:SC2018-01-30#> successful.

ISO date setLocalDate, override

---

libindi/libs/indibase/indiccd.cpp

Fix memory/resources leak leading to 'too many open files' error in libindi

Close opened directory resource

---

3rdparty/CMakeLists.txt
3rdparty/indi-fli/fli_ccd.cpp
3rdparty/libfli/CMakeLists.txt

Three changes.  Disable parallel port driver in libfli for OSX.  Include indi-fli for OSX.  Change method for determining when exposure is complete.  Used method from FLI test program ported to OSX. Test program can be found at http://www.flicamera.com/downloads/sdk/wintakepic.zip  
Not tested under Linux.

Changes for new FLI libusb driver under OSX.

---

3rdparty/indi-asi/asi_ccd.cpp

Fixes the issue where the image thread's request state is reset after the call to
grabImage(), which clears the request state set when Rapid Looping is enabled.

Fix for Rapid Looping feature

---

3rdparty/indi-fli/fli_ccd.cpp

Old code resulted in.
[2018-02-17T09:19:04.758 CST DEBG ][           org.kde.kstars.indi] - FLI CCD : "[DEBUG] Binning (1x1). Final FLI image area is (140462610448384, 140462610448384), (4872, 3248). Size (4872x3248) "

Fix formatting problem under OSX in debug logging

---

3rdparty/indi-maxdomeii/maxdomeii.cpp
3rdparty/indi-maxdomeii/maxdomeiidriver.cpp
3rdparty/indi-maxdomeii/maxdomeiidriver.h
3rdparty/indi-maxdomeii/test_maxdomeii.cpp
3rdparty/indi-qhy/qhy_ccd.cpp
libindi/drivers/telescope/celestrondriver.cpp
libindi/drivers/telescope/celestrondriver.h
libindi/drivers/telescope/celestrongps.cpp
libindi/libs/indibase/indilogger.h

Currently, only celestrongps and maxdome_ii drivers are using these macros.

Add shorter logging macros to indilogger.h

---

3rdparty/indi-mgen/indi_mgenautoguider.xml
libindi/drivers.xml
libindi/drivers/telescope/skywatcherAPI.cpp
libindi/drivers/telescope/skywatcherAPI.h
libindi/drivers/telescope/skywatcherAltAzSimple.cpp
libindi/drivers/telescope/skywatcherAltAzSimple.h
libindi/libs/indibase/alignment/CMakeLists.txt

It is "forked" Skywatcher Alt-Az mount driver. Changes:
- Removed alignment subsystem codes
- Alt/Az <-> Ra/Dec conversions are based on pure libnova
- Supporting wedge and "EQ wedge" (placing the Alt/Az mount on the top of an EQ mount) modes
- Guiding support in wedge/EQ wedge modes.

Add Skywatcher Alt-Az Simple mount driver

---

libindi/libs/indibase/defaultdevice.cpp

If DefaultDevice doesn't get any connections registered, it doesn't initialize ConnectionModeSP member, but its name is still compared against when DefaultDevice::ISNewSwitch() is called causing an uninitialized access. This happens with at least GPSD and Wunderground drivers and probably others that don't use the default connection plugins. It's unlikely that the uninitialized name would match anything, but better to fix it anyway.

Initialize ConnectionModeSP to avoid uninitialized access

---

libindi/drivers/telescope/lx200ap_experimental.cpp

Currently the UnparkFrom position is saved with other config options.  It is better to have it always default to "Last Parked" which is the safest option.  If someone needs to override it for a one time situation then at least it will go back to the safe option when they reconnect to the mount the next time.
Also disabled code to try to read in the UnParkFromSP property in case someone ran the original driver and the value is saved in their config.

20180410 lx200ap unparkfix

---

libindi/libs/indibase/basedevice.cpp

For some reason BLOBVector code was missing initializing timeout field like other types had, which caused uninitialized access later on.

Initialize timeout for BLOBVector

---

libindi/libs/indibase/inditelescope.cpp

Telescope base class had similar issue with uninitialized parkdata XML root that dome class had so initialize and free it.

Initialize parkdata XML root and free it in destructor

---

libindi/libs/indibase/indilightboxinterface.cpp

Checking for duplicate filter names went one iteration too far accessing past the allocated memory.

Checking for duplicate filters off-by-one overflow

---

libindi/drivers/rotator/pyxis.cpp
libindi/drivers/rotator/pyxis.h

Jasem, my changes.
- Added firmware and model parameters to an info tab
- Use the CVxxxx command to return the firmware version of the rotator and set
- Firmware parameter
- Model parameter (3 inch or 2 inch)
- Correct default rotator rate (delay) of 6ms or 8ms (2 inch)
- Changed isMotionComplete to loop and consume all microsteps and update the PA parameter.
- Sized read in isMotionComplete to be approximately 1 degree so GUI update occurs each degree. Number of steps in 1 degree dependent on rotator model.
- Fixed setRotationRate to read response which was not being done and made setting the rate non-reliable.
I'm new to the indi driver parameter/property api so please take a good look at my changes. Also is my approach, the while loop calling isMotionComplete in TimeHit, ok?   Waiting …

Updates to pyxis rotator to support 3 inch and 2 inch rotators

---

libindi/drivers/rotator/pyxis.cpp
libindi/libs/indibase/indirotatorinterface.cpp

Jasem, my changes.
- Added firmware and model parameters to an info tab
- Use the CVxxxx command to return the firmware version of the rotator and set
- Firmware parameter
- Model parameter (3 inch or 2 inch)
- Correct default rotator rate (delay) of 6ms or 8ms (2 inch)
- Changed isMotionComplete to loop and consume all microsteps and update the PA parameter.
- Sized read buffer in isMotionComplete to be approximately 1 degree so GUI update occurs each degree.  Number of steps in 1 degree dependent on rotator model.
- Fixed setRotationRate to consume terminator which was not being done and made setting the rate non-reliable.
I'm new to the indi driver parameter/property api so please take a good look at my changes. Also is my approach, the while loop in isMotionComplete, ok?   Waiting for …

Fix problems with Pyxis Reverse functionality

---

libindi/drivers/weather/weatherwatcher.cpp
libindi/drivers/weather/weatherwatcher.h

Main reason for this change is to allow users to specify their own keywords for 4 weather related parameters: temperature, rain, wind, wind gust. 
So before connecting you have to set in option tab the file  (or URL) containing weather data and the 4 keywords matching the names in the file.

update weather watcher driver

---

libindi/drivers/telescope/lx200ap_experimental.cpp
libindi/drivers/telescope/lx200ap_experimental.h
libindi/drivers/telescope/lx200apdriver.cpp
libindi/drivers/telescope/lx200telescope.h

CP3 documentation states duration can go up to 999msec so for longer requests we manually time the pulse in the driver.
Also the AP driver was using the LX200Telescope implementation of GuideNorth/South/East/West which was trying to set the slew speed of the mount to the guide speed.  On AP mounts we must use a different command to do this.  I implemented these functions in the experimental driver.

Fix pulse guide support for AP mounts.  

---

3rdparty/indi-eqmod/eqmod.cpp
3rdparty/indi-eqmod/eqmod.h
3rdparty/indi-eqmod/indi_eqmod_sk.xml

This change adds support for setting minimum pulse length and running short pulses synchronously without timer in EQMod.
As communication delay is quite big especially with Bluetooth serial connection, it's better to ignore very short pulses altogether rather than overcorrect with too long pulses. This delay seems to be around 50ms for Bluetooth connection and supposedly around 16ms for EQDIR cables and 32ms via handset in PC Direct mode (I have only tested BT version, other info from http://eq-mod.sourceforge.net/prerequisites.html)
Also added support for doing short pulses without timer by sleeping the remaining time after communication delay from starting the pulse. Timer is also now started before starting the pulse to remove that excess time from the delay. 
Last change is skipping …

EQMod pulse limits and deferring status update during pulses

---

3rdparty/indi-eqmod/align/align.cpp

Noticed I couldn't write align data out after adding couple of new sync points, but pressing the button didn't do anything as it was already "on" after I had saved the data just a bit earlier. So reset the buttons back to off state so they can be pressed multiple times without changing to another button in between and they are all "action" type switches anyway.
Also noticed there was an extra IUUpdateSwitch() call as the same call had been done before checking which button was turned on.

Switch align action buttons back to off to allow pressing same button multiple times

---

libindi/libs/indibase/indiccd.cpp

On 32-bit operating systems, such as Raspbian, and only on some filesystems, enumerating a folder would fail, because some values would be too big for 32 bit ints.  This would cause INDI to believe the folder was empty, and it would continuously create a Light_001.fits file, over and over, constantly overwriting the previous file.

Fix issue where image files would continuously get overwritten

---

3rdparty/indi-gphoto/gphoto_driver.cpp

The documenation for gp_file_get_data_and_size says the pointer returned is owned by libgphoto2, and will be destroyed when the file is destroyed.  This is only true if you used gp_file_new().  If instead you use gp_file_new_from_fd(), then the pointer returned is entirely owned by the caller, and must be freed. *sigh*

Fix memory leak in indi_gphoto_ccd

---

3rdparty/indi-gphoto/gphoto_driver.cpp

Employ PTP property called CustomFuncEx to enable/disable mirror
lockup for EOS cameras. Before this commit mirror lockup works only,
when mirror lockup is enabled by hand via the EOS camera menu.
Details of the EOS customfuncex are provided at
https://github.com/gphoto/libgphoto2/blob/master/camlibs/ptp2/canon-eos-customfunc.txt
The CustomFuncEx can be tested with gphoto2 as follows:
enable mirror lockup:
gphoto2 --set-config customfuncex=20,1,3,14,1,60f,1,1
disable mirror lockup:
gphoto2 --set-config customfuncex=20,1,3,14,1,60f,1,0

Enable/disable EOS camera mirror lockup with custom function

---

3rdparty/indi-gphoto/gphoto_driver.cpp

If mirror lockup seconds is set to 0, always
disable mirror lockup for EOS cameras. Otherwise always
enable mirror lockup. This prevents the conflict when mirror lockup
is enabled by hand via the EOS camera menu, however in INDI
it is disabled.

Disable EOS camera mirror lockup always when sec = 0

---

libindi/libs/indibase/indiccd.cpp

Based on the location settings add additional FITS keyword
SITELAT  = <double> / Latitude of the imaging site in degrees
SITELONG = <double> / Longitude of the imaging site in degrees
See: https://www.plate-archive.org/wiki/index.php/FITS_header_format

Add additional FITS Keyword SITELAT and SITELONG

---

3rdparty/indi-shelyak/indi_shelyakalpy_spectrograph.cpp
3rdparty/indi-shelyak/indi_shelyakalpy_spectrograph.h

When Flat or calib lamp is on and user clicked directly on Dark, there was a little bug : 
dark goes on, then there was a switch emitted, that lights off lamp that was on before. So the dark goes off. (dark is when signal for flat And signal for calib lamps are on).
Code needs a little refactoring to manage this.

Little changes to improve behaviour

---

3rdparty/indi-eqmod/eqmod.cpp
3rdparty/indi-eqmod/eqmod.h

The Dec axis inversion state (DEInverted) was being initialized based on the mount side of pier at the time of driver initialization.  You could get a different value for DEInverted depending on the orientation of the mount at the initialization time.  This was a problem for PHD2 or any other application that expected the mount's response to a guide command to be consistent across driver restarts. PHD2 users could get unexpected runaway dec guiding if they did nor recalibrate every time the driver started up.
The fix is to remove the dependency on side of pier when initializing DEInverted.  DEInverted is now set based on the site latitude (northern/southern hemisphere) and the REVERSEDEC switch.

eqmod: do not initialize dec axis inversion state from side of pier

---

libindi/drivers/video/v4l2driver.cpp

This adds control name "Exposure" as manual exposure control for camera ov534 in the context of issue #637.

Added exposure control name for ov534 camera.

---

3rdparty/CMakeLists.txt

Fixes problem with trusty build

Disable Moravian driver on gcc <4.9

---

libindi/drivers/video/v4l2driver.cpp

Summary:
This changeset re-enables and fixes the feature stacking streamed frames, in order to simulate absolute exposure on V4L2 cameras not providing any control.
This allows MJPEG-only cameras to stack video frames up to the requested exposure, using either mean or additive consolidation, and darks.
Code is completely unoptimized, and could well hog small-performance systems.
The most suitable stack method for low-light frames is probably the additive algorithm.
Test Plan:
Use a MJPEG camera, preferentially one that rejects absolute exposure because of the lack of V4L2 control.
Try an exposure, see it fail, check the error message displayed in the console.
Switch INDI control to "MEAN" or "ADDITIVE", retry exposure and check the result (in Ekos for instance).
Test stack item "TAKE …

Fix feature stacking streamed frames to simulate absolute exposure

---

libindi/CMakeLists.txt

Reported here: https://github.com/indilib/indi/issues/669
I don't really know why I seem to be the only one to experience this issue with libinconv. I do not want to force anybody on this, I'll just continue to keep using my own fork if this PR does not comply with you cmakefiles guidelines

Fixed the undefined reference issue for libiconv

---

3rdparty/libdspau/CMakeLists.txt

Currently the CMake module path points to non-existent directory and finding FFTW3 fails even though installed, at least under Ubuntu 18.04.

Libdspau: Point CMAKE_MODULE_PATH to directory under main INDI repository for FindFFTW3.cmake

---

libindi/drivers/focuser/tcfs.cpp
libindi/drivers/focuser/tcfs.h

Primarily to implement the Mode A and B temperature compensation slopes and delay to complete full set of functions.
In the process I removed the dependency on the skeleton XML since I couldn't work out how it works.  Hope this is a good thing.
Fixed an issue with the Auto modes where the focuser does not accept any commands so the polling commands continually time out. Now when in Auto mode TimerHit reads the messages sent by the focuser
Altered FFMODE to retry 5 times whenever used (via SetManualMode())
Altered timeout to 2 seconds from 5 seconds. 5 seconds seems like an eternity

Optec TCFS driver enhancements for your consideration

---

3rdparty/indi-gphoto/gphoto_driver.cpp

There's further discussion in the forum at http://indilib.org/forum/general/2255-dsusb.html, but this is a slight fix to the GPhoto driver when using a DSUSB device from Shoestring Astronomy.  Because the DSUSB is configured by setting the `bulb_port` (which also applies to serial shutter releases), we need an additional check that we're _not_ using a DSUSB before attempting to release the shutter via a serial port.

When using a DSUSB, don't attempt to open the shutter via the serial port for shorter exposures

---

libindi/drivers/focuser/usbfocusv3.cpp
libindi/drivers/focuser/usbfocusv3.h

This PR does a quite big overhaul of the USBFocusV3 driver:
- Serial communication changed to deal with lines instead of fixed
lengths. This fixes issues with reading temperature for example as the
response length varies. Old code didn't work correctly when
temperature was between +/- 0-9.99 degrees as the response was shorter
than expected.
- Also removed ad-hoc usleeps that weren't really necessary at all and
centralized serial access to a couple of functions instead of each
command separately.
- Added code to try to restore command sync in case something else
like ModemManager has written something to the serial port before. The
protocol doesn't have any sync mechanism and assumes all commands are
six characters long. This doesn't work quite as well as I hoped, but is
better than …

Update to USBFocusV3 driver

---

libindi/drivers/focuser/focuslynxbase.cpp

Was due to test and validation with focuser configured in "Reverse" mode.

Corected wrong "Sync" setting position.

---

3rdparty/libapogee/CMakeLists.txt
3rdparty/libdspau/CMakeLists.txt

This will resolve build errors in craft because cmake cannot find the header files for the dependencies because they are located in the craft root directory instead of the system root directory.  I already fixed this problem for the main INDI build, but not these libraries.

Adding support for craft builds for mac to libapogee and libdspau

---

3rdparty/indi-qhy/qhy_ccd.cpp

Tried both CancelQHYCCDExposingAndReadout and CancelQHYCCDExposing from the SDK with the QHY5-M- (SSAG). In either case, this results in a crash of the indi driver. Added a condition to bypass this call for the QHY5-M-. The device now works using Ekos as a guide camera.

Added fix for QHY5-M- CancelQHYCCDExposing* crash

---

3rdparty/indi-atik/atik_ccd.cpp
3rdparty/indi-atik/atik_ccd.h

Adds mutex to resolve access conflict between timer and imaging thread. Also enable sub-framing unconditionally and remove some stray white space.

Atik driver fixes

---

libindi/libs/indibase/indiweather.cpp

Refactoring of the weather class missed passing ISNewNumber data to the new weather interface so limits couldn't be changed. Also removes a couple of stray white space again (sorry my editor has OCD for white space :)

Fix setting limits to weather values

---

3rdparty/indi-atik/atik_ccd.cpp

I got a new SDK version from Atik support (seems you had already submitted the Mac version) and added waiting for camera to be idle before starting exposure as flushing after abort seems to take essentially as long as downloading the image would, which is around 10s on my 383L+ in full resolution. Starting a new exposure while this flushing is ongoing messes things up somewhat which is why the documentation has this: "Note: If you have previously stopped the exposure, then you have to wait for the camera state (listed below) to return to Idle before another exposure can be made." I also added a timeout in case the camera is somehow stuck in weird state, though 100s might be a bit overkill, but I don't know how long downloads take in worst case scenario.

Update AtikCamerasSDK to version 110 and fix abort issue

---

3rdparty/indi-eqmod/eqmod.cpp

When the values are loaded from skel, the backlash setting was not sent to mount, so the mount values were uninitialized.
This fixes https://github.com/indilib/indi/issues/457

Initialize backlash on eqmod connect

---

debian/libatik/control

There seems to be some confusion in PPA that causes new indi-atik builds to fail as libatik hasn't been updated. Wondering if this might have something to do with it.

Typo in source package name?

---

3rdparty/indi-eqmod/eqmod.cpp
3rdparty/indi-eqmod/skywatcher.cpp

Without this patch eqmod on aarch64 prints confusing debug messages like this:
```
DEBUG<->5267645.183416 sec<---->: Init() : Motors not initialized -- read Init steps RAInit=8388608 DEInit = 281470690131968
```

Use long arg with printf %ld

---

3rdparty/indi-eqmod/align/triangulate.h
3rdparty/indi-eqmod/eqmod.cpp
3rdparty/indi-eqmod/skywatcher.h

Testing with valgrind shows that these values were used from EQMod::ReadScopeStatus before initialization.
BTW, the location is saved to config file immediately after each change but it is not auto-loaded on startup. Is this correct behavior?

Fix more unitialized variables in eqmod driver

---

libindi/drivers/focuser/usbfocusv3.cpp
libindi/drivers/focuser/usbfocusv3.h

This fix a number of problem with the usbfocusv3 driver: timeout error, truncated data, ... 
One of the problem is because a timer was started part of updateProperties(), this meant that two concurrent timer event where running at the same time.
I also remark the Ascom driver retry the command that return truncated data, maybe to bypass a problem in the firmware.
As I where there I add a mutex for the serial command to avoid other issue of the same kind.
This change include:
- retry failed command as the Ascom driver do.
- lock serial command with a mutex
- ensure we receive the termination string \n\r
- do not run multiple simultaneous timer
- log correctable error as warning.

Fix for usbfocusv3 driver

---

3rdparty/indi-gphoto/gphoto_driver.cpp

I had a problem when bulb exposure was started using shutter release cable. It never finished because on bulb stop it assumed using bulb widget and did not close the open fd... This is fixing it.

Fix bulb exposures initiated with shutter release cable on Pentax.

---

3rdparty/indi-gphoto/gphoto_readimage.cpp

See LibRAW API: https://www.libraw.org/docs/API-CXX.html#COLOR
For testing I used my (old) Nikon D50 which has bayer pattern:
>dcraw -i -v IMG_0001.NEF
Timestamp: Tue Jan  1 23:02:51 2019
Camera: Nikon D50
ISO speed: 400
Shutter: 1/60.0 sec
Aperture: f/4.5
Focal length: 31.0 mm
Embedded ICC profile: no
Number of raw images: 1
Thumb size:  3008 x 2000
Full size:   3040 x 2014
Image size:  3039 x 2014
Output size: 3039 x 2014
Raw colors: 3
Filter pattern: BG/GR
Daylight multipliers: 2.458272 0.928173 1.258317
Camera multipliers: 570.000000 256.000000 389.000000 256.000000
Taking an image with INDI gphoto driver (incorrect order) resulted in:
...
FRAME   = 'Light   '           / Frame Type
XBAYROFF=                    0 / X offset of Bayer array
YBAYROFF=                    0 / Y offset of …

Correct order of Bayer pattern in DSLR RAW

---

libindi/drivers/telescope/lx200_OnStep.cpp

This change is to make the user interface terminology within INDI, the same as what is on the Android App for OnStep.

Labels renamed to be consistent with the Android App.

---

libindi/drivers/video/v4l2driver.cpp

Optional pull request
See forum thread: https://www.indilib.org/forum/ccds-dslrs/4392-indi-pixel-size-detection.html#33485
Basically means that some (reported) V4L2 devices will get correct pixel sizes instead of the standard size, meaning less work for people in the future.

V4L2: Neximage5, others Add automatic pixel size

---

libindi/drivers/telescope/lx200_OnStep.cpp

The driver LX200_OnStep now implement the FocuserInterface. 
FOCUSER_INTERFACE must be added to DRIVER_INTERFACE so the client know it can use this driver as a focuser.
See:
https://www.ap-i.net/mantis/view.php?id=2051

Advertise client that the driver implement the FocuserInterface

---

3rdparty/indi-starbook/CMakeLists.txt
3rdparty/indi-starbook/command_interface.cpp
3rdparty/indi-starbook/command_interface.h
3rdparty/indi-starbook/connectioncurl.cpp
3rdparty/indi-starbook/connectioncurl.h
3rdparty/indi-starbook/indi_starbook.cpp
3rdparty/indi-starbook/indi_starbook.h
3rdparty/indi-starbook/starbook_types.h

Main change in this patch is custom connection plugin and command interface.
I'm taking away much of unneeded connection handling from logic inside `Starbook` class.
Code is more bloated but hopefully more testable and safe. This is also preparation for more intelligent state handling. With knowledge of current Starbook state, we can prevent some errors and inform user. This should streamline initial connection where any wrong command can put Starbook into a _bad state_.
I need assistance with `Connection::Curl`, I can't get `saveConfig()` and `loadConfig()` working.

Starbook 0.3

---

3rdparty/indi-avalon/CMakeLists.txt
3rdparty/indi-avalon/lx200stargo.cpp
3rdparty/indi-avalon/lx200stargofocuser.cpp
3rdparty/indi-avalon/lx200stargofocuser.h

Focuser status is updated regularly with the scope status. This fixes the problem that the focuser position was not shown after a move, preventing all relative focuser moves.
Now both absolute and relative focuser movement is working.

Avalon StarGO: focuser bugfix

---

libindi/drivers/telescope/lx200ap_experimental.cpp
libindi/drivers/telescope/lx200ap_experimental.h
libindi/drivers/telescope/lx200apdriver.cpp

The lx200ap_experimental driver had leveraged a guide timer routine in lx200telescope.cpp but I believe that function has been modified in such a way that it broke the simulated pulse guides we must do with the AP driver for durations > 999ms.   For a pulse guide > 998ms this meant the pulse guide event NEVER STOPPED and the mount kept moving forever.
I have moved the timeout routines into the AP driver now and have verified pulse guide requests for <= 999ms are handled by the protocol command to the mount controller and > 999ms are handled by the AP INDI driver by initiating a MOVE at GUIDE speed and then turning off the MOVE after the requested duration using a timer.
This is an important fix since it would have pretty much made pulse guiding unusable for the AP experimental driver. …

Fixed bug for pulse guide > 999ms

---

libindi/drivers/telescope/lx200ap_experimental.cpp

When unparking the mount the lx200ap_experimental driver would enable tracking but the internal INDI state was not correctly updated to reflect the mount was tracking.  So the INDI Control Panel UI showed the mount was NOT tracking.
This patch updates the TrackState to fix this behavior.  Also reordered the SetParked() and SetTrackEnabled() calls as the SetParked() call then calls SyncParkStatus() which sets the TrackState to SCOPE_IDLE if the mount is unparked.

Make sure tracking state is set properly after unparking.

---

libindi/drivers/focuser/tcfs.cpp
libindi/drivers/focuser/tcfs.h

Two changes bundled together.
The main one allows changes to the focuser position whilst it is in Auto mode. Normally disallowed by TCFS this allows the client scheduler to adjust the offset on filter change without manual intervention. The driver puts the focuser in manual mode to change the offset then returns to auto mode.
The second change implements a feature of TCFS Commander which allows not just a temperature gradient but also a zero degree intercept so that the focuser position can be determined for a given ambient temperature (assuming complete linearity). This allows fully automatic operation which can be enabled/disabled by StartMode switch. Arguably this should be a client feature but should help adoption of INDI by TCFS Commander users.
Would you like me to move the driver …

Optec Tcfs focuser

---

libindi/drivers/focuser/hitecastrodcfocuser.cpp

https://github.com/indilib/indi/issues/495
Managed to get the Hitecastro DC Focus controller 2 driver working. The patch is:
danniesim@20a11ef
I am not sure if this breaks the "non 2" version of the controller - the Hitecastro DC Focus controller ( note there is no "2") as I don't have that hardware. One idea is to have a configuration option so that the user can select between the versions.

Hitecastro DC Focuser 2 - Change command to move focuser

---

3rdparty/CMakeLists.txt

This will provide an option to use the 3rd party cmakelists to build all of the required libraries without the 3rd Party drivers.  This way you can build the libraries first.  This is very useful for making our craft recipes.

Adding 3rd Party Library build option to cmakelists for craft

---

libindi/drivers/telescope/lx200ap_experimental.cpp
libindi/drivers/telescope/lx200ap_experimental.h
libindi/drivers/telescope/lx200ap_experimentaldriver.cpp
libindi/drivers/telescope/lx200ap_experimentaldriver.h

This patch changes the lx200ap_experiemental driver to not rely on the lx200telescope.cpp routines for setting the 'move' ('centering') rates of the mount.   The AP driver has to simulate a pulse guide for durations > 999ms.  This is done by changing the centering rate to 'GUIDE'.  The other centering rates supported are '12x', '64x', '600x' and '1200x'.  A new routine was created in lx200ap_experimentaldriver.cpp that supports the 'GUIDE' rate.
I have tested this change and it fixes a bug where you could end up having simulated pulse guide events happen at a rate other than GUIDE rate.
Also the macros for park and unpark were replaced by functions for better logging.

20190130 fix lx200 ap pulseguide

---

libindi/drivers/telescope/pmc8.cpp

The device name was being referenced too early leading to problems with a flood of debug windows being created by kstars.

Initialize device name properly

---

libindi/drivers/telescope/pmc8.cpp

Recent versions of PHD2 was not allowing the user of the PMC8 driver.  This was because the PMC8 driver did not advertise it had a GUIDER_INTERFACE.  This patch corrects the problem.  I have verified the latest PHD2 (built from their git repository) will properly recognize the PMC8 now with this fix.

Need to advertise GUIDER_INTERFACE so PHD2 will accept mount

---

3rdparty/indi-avalon/CMakeLists.txt
3rdparty/indi-avalon/ChangeLog
3rdparty/indi-avalon/lx200stargo.cpp
3rdparty/indi-avalon/lx200stargo.h
3rdparty/indi-avalon/lx200stargofocuser.cpp
3rdparty/indi-avalon/lx200stargofocuser.h
debian/indi-avalon/changelog

Querying the focuser status without a focuser connected leads to problems with StarGO when running several hours. It might lead that the StarGO device no longer responds and requires a reset.
With this version, the focuser can be activated and deactivated avoiding unnecessary (and potentially troublesome) querying to the AUX device.

[Avalon StarGO] Enabling/disabling focuser

---

libindi/CMakeLists.txt
libindi/drivers.xml
libindi/drivers/focuser/lacerta_mfoc.cpp
libindi/drivers/focuser/lacerta_mfoc.h

New focuser driver for the Lacerta MFOC :
https://teleskop-austria.at/MFOC_LACERTA-Motorfokus-Stand-Alone-und-ASCOM-kompatibel-mit
Developed thanks to the documentation and support from Lacerta GmbH (Tommy Nawratil, Braskó Sándor and Lajos Szantho). Testing, refactoring and polishing thanks to Christian Liska.

Focuser Lacerta MFOC

---

libindi/indiserver.c

1. Do not use file descriptors from inactive DvrInfo. It crashes when the same fd is re-used. There already is the same handling for clients.
2. Indiserver allocates 50KB for each message, but for the -m option it considers real message size - typically under 0.5KB. When the queue size reaches the default 128MB limit, it allocates more than 12GB of memory, so it is usually killed by OOM killer much earlier.
The patch reduces the buffer to 2KB per message and changes size calculation to report all the allocated memory.

Indiserver fixes

---

libindi/indiserver.c

One more place where dp->active should be checked.

indiserver: skip inactive driver

---

libindi/drivers/focuser/celestron.cpp
libindi/drivers/focuser/celestron.h
libindi/drivers/focuser/celestronauxpacket.cpp

Check the limits returned from the focuser and only use them if they are sensible.
Implement focuser calibration.

Check focuser limits and implement calibration

---

libindi/drivers/telescope/celestrondriver.cpp

The data is read from the hardware as a char array and some compilers
treat this as signed, giving bad values. Cast to uint8_t to prevent this
- hopefully.
We may not be able to tell until users try it.

Fix problem with limits and position of focuser

---

libindi/drivers/telescope/synscandriver.cpp

Slew directions are inverted on my Synscan GOTO Dobson mount (Orion SkyQuest XT8g) using the new driver (it doesn't happen with the Synscan legacy driver), so that the "up" ("north") button moves the tube downwards and, viceversa, the "down" button moves the tube upwards.
The same happens with the "left" button which moves the tube to the right and viceversa.
So, in my mount (and I think also in other AltAz mounts), the negative direction (37) means "North" for the vertical (altitude) axis and "West" for the horizontal (azimuth) axis.
Anyway, I don't know if this is a general issue for all other AltAz mounts, as I can only test it with my own mount.
So, I think it's worth to better investigate this behaviour in order to understand if it's a general behaviour for all AltAz mounts (I guess …

Synscan: invert slew direction for AltAz mounts

---

.gitignore
libindi/libs/indibase/indicontroller.cpp
libindi/libs/indibase/inditelescope.cpp
libindi/libs/indibase/inditelescope.h

Dear maintainers,
when I tried to use an XBox 360 wireless controller for slew control, I realized that
- the only joystick which got mapped correctly (as JOYSTICK_1) was the left analog joystick;
- the other joysticks (JOYSTICK_2 and JOYSTICK_3) where partly mapped to the right analog joystick's axes, partly to the two triggers;
- the directional pad wasn't mapped to any JOYSTICK_* at all.
To this end, I implemented a mechanism which allows for explicitly defining which joystick axes are to be used for controlling N/S and W/E motion, respectively.
During the course of this work, I also fixed two general bugs regarding joystick axis handling.
Finally, I modified the code responsible for snapping a joystick's angle to x/y direction. I have the impression that this greatly facilitates …

Extended telescope joystick motion control

---

libindi/drivers/auxiliary/sqm.cpp

I found that anything other than 115200 causes the device to crash (has to be unplugged and plugged in again) It also causes the driver to crash and I have to kill the process. It seems to get stuck in the handshake getDeviceInfo() method on the line ` read(PortFD, buffer + received, 39 - received);` 
Setting to 115200 in the driver UI before connecting and it works fine. Thought it might be a good idea to default to this baud rate to prevent any future confusion

Set a default baud rate of B_115200 for serial connection

---

libindi/drivers/telescope/celestrondriver.cpp
libindi/drivers/telescope/celestrongps.cpp

focuser now managed OK with StarSense.
Set time and set location disabled if the mount is aligned, doing this
with StarSense undoes the alignment and changing the date or time will
upset the mount model for all mounts.

Updates for StarSense

---

3rdparty/indi-avalon/CMakeLists.txt
3rdparty/indi-avalon/ChangeLog
3rdparty/indi-avalon/lx200stargo.cpp
3rdparty/indi-avalon/lx200stargo.h
3rdparty/indi-avalon/lx200stargofocuser.cpp
3rdparty/indi-avalon/lx200stargofocuser.h
debian/indi-avalon/changelog

**New features**
- control for reversing focuser direction added
- storing focuser parameters into the config file added
**Bug fixes**
- connection handling of focuser follows the base device

Avalon Stargo 1.4 - Reversed mode for focuser

---

3rdparty/indi-avalon/CMakeLists.txt
3rdparty/indi-avalon/ChangeLog
3rdparty/indi-avalon/lx200stargo.h
debian/indi-avalon/changelog

Bugfix declaring Connect() and Disconnect() as override fixing travis-ci errors.

Avalon Stargo 1.4.1 - Bugfix for compile problems

---

3rdparty/indi-qhy/qhy_ccd.cpp

This solves the issue of getting "Set QHYCCD ROI resolution failed" messages when using binning. It seems unscaled X,Y coordinates were being used, while scaled width/height was used.

Fix binned subframe capture in QHY driver

---

libindi/drivers/telescope/lx200_OnStep.cpp
libindi/drivers/telescope/lx200_OnStep.h

This pull request adds support for driving output ports of Onstep controller.
It adds a new tab "Outputs" which allows entering values for 10 outputs. 
Both binary and analog values can be passed to Onstep controller.
Onstep will interpret the values accordingly: 
* if output is binary, then any value above 0 will toggle the output to high
* if output is analogy, the analog output will be set per the input value
With my RAMPS based Onstep I can toggle output 6 as binary and set values between 0 and 255 on port 7.
This code intentionally does not impose any validations on values, passed to Onstep in order to support future enhancements in Onstep.

Support for driving output ports of Onstep controller

---

3rdparty/indi-asi/asi_ccd.cpp

ASI requires, that a ROI has a width mod 8 = 0 and height mod 2 = 0. To ensure this, the driver reduces the frame size internally by the respective mod values, if necessary. That means there might be a difference between the set frame size and the size of the captured image.
This is done intentionally to avoid very technical error message that might annoy users. For details about this decision see the discussion here: https://indilib.org/forum/ccds-dslrs/4956-indi-asi-driver-bug-causes-false-binned-images.html

Incompatible frame sizes are reduced internally to ensure compatibility

---

libindi/drivers/focuser/celestron.cpp
libindi/drivers/focuser/celestron.h
libindi/drivers/telescope/celestrondriver.cpp
libindi/drivers/telescope/celestrondriver.h
libindi/drivers/telescope/celestrongps.cpp
libindi/drivers/telescope/celestrongps.h

Celestron recommend that moves are not allowed when the focuser is not calibrated because running into the hard stops at full power could cause damage.

Prevent moves when the focuser is not calibrated

---

libindi/drivers.xml
libindi/drivers/dome/scopedome_dome.cpp
libindi/drivers/dome/scopedome_dome.h

In current version pressing CW or CCW motion buttons crashes due to unimplemented Move method in the driver class when dome base class tries to call it causing it to call itself instead ending up in infinite recursion.

Implement CW/CCW motion controls in ScopeDome driver

---

libindi/drivers/telescope/eq500x.cpp
libindi/drivers/telescope/eq500x.h
libindi/drivers/telescope/eq500x.md

Fixes North/South guiding/movement orientation.
Fixes property switch "Use Pulse Cmd" so that it rejects the pulse command feature (only timed moves).
Markdown documentation was missing.

Bugfix  pulse and movement

---

3rdparty/indi-qhy/qhy_ccd.cpp
3rdparty/indi-qhy/qhy_ccd.h
3rdparty/indi-qhy/qhy_ccd_test.cpp

Added support for multiple read modes in QHY sCMOS cameras, code has been tested in one QHY42Pro, that allows two read modes:
* HDR: output is a single 4096*2048 resolution image, it contains two images. Left is low gain channel image and right side is high gain channel image.
* STD: output is a single 2048*2048 resolution image. 
Implementation uses INumber types, as future improvement I plan to use ISwitch that will provide a more user friendly implementation, showing read modes names instead its index number.

Added support for multiple read modes in QHY sCMOS cameras

---

3rdparty/indi-eqmod/CMakeLists.txt
3rdparty/indi-eqmod/skywatcher.cpp
debian/indi-eqmod/changelog

The HEQ5 with the old motor board with firmware version 106 as a bug that make the RA to drift at a rate about 4 arcsec per minute when driven at sidereal rate. Unfortunately this board cannot be upgraded to a new firmware. This issue was the reason for the "drift compensation" slider in EQASCOM.
The solution is to override the Timer Interrupt Frequency returned by the board when this board version is detected, as this is already done for the 80GT and 114GT.
I find the new frequency after some trial and now my mount as no more drift.

Eqmod: Fix RA drift with HEQ5 firmware 106

---

3rdparty/indi-talon6/CMakeLists.txt
3rdparty/indi-talon6/indi_talon6.xml.cmake

This driver is not included in the stable / nightly releases. There are no compile errors, I think it is the installation that is failing. 
Found a minor typo in xml.cmake that can cause this issue.
I will check in the next nightly

Fixed typos in conf files

---

libindi/drivers/telescope/eq500x.cpp
libindi/drivers/telescope/eq500x.h
libindi/test/lx200drivers/test_eq500xdriver.cpp

When a Go-To is requested to the driver, the final slew rate was always "guide". Because SkySafari is not updated with slew rate changes, there was in general a discrepancy between the mount control on the mount settings.
This PR restores the slew rate after a Go-To request and an Abort request. It also makes sure executing a second Go-To while one is running properly restores the original slew rate.
This PR adds tests reproducing the issue, then code fixing that issue. CircleCI validated all tests in the branch this PR originates from, but this PR does not run any actual tests.

Bugfix  slew rate after goto

---

libindi/libs/indibase/alignment/MathPluginManagement.cpp

In my previous commit to this file, I wrote a series of if statements that should make the path to the math plugins correct in various system configurations including embedded within app bundles.  Unfortunately, in the last step, I made a typo that overwrote the result of the if statement with the default value.  This bug didn't show up till now because on Linux, the INDI_MATH_PLUGINS_DIRECTORY is the correct directory.  On OS X, I didn't see any issue either because on my system, the plugins are there. It was only with the new craft recipes that the issue became apparent.

fixing a typo I made

---

libindi/drivers.xml
libindi/drivers/focuser/sestosenso.cpp

Quick fix to stop the focuser direction reversal after a SM;xxxxx! command. This hack simply means that these command will no longer be sent. This is intended to allow people to use the focuser until the proper solution is completed. A more complete version will be released at a later date.

Version 1.3 of the Sestosenso Focusser. Hack to make it work

---

3rdparty/indi-atik/atik_ccd.cpp

ATIK library call: ArtemisProperties(...) returns by reference call
struct ARTEMISPROPERTIES *pProp, where pProp->Protocol contains
the firmware version of the camera. The firmware is however
decoded as major.minor, where major = prop.Protocol >> 8
and minor = prop.Protocol & 0xff. This patch was tested with
camera ATIK 414EX where used firmware is: 3.44 and pProp->Protocol = 812.

Decode ATIK firmware version correctly in pProp->Protocol

---

libindi/indidriver.c

The original code snippet is:
FILE *fpin = fopen(configFileName, "r");
if (fpin != NULL)
{
FILE *fpout = fopen(configDefaultFileName, "w");
if (fpout != NULL)
{
int ch = 0;
while ((ch = getc(fpin)) != EOF)
putc(ch, fpout);
fclose(fpin);
}
fclose(fpout);
}
...
However, fclose(fpin) must be exchanged with fclose(fpout), that is:
FILE *fpin = fopen(configFileName, "r");
if (fpin != NULL)
{
FILE *fpout = fopen(configDefaultFileName, "w");
if (fpout != NULL)
{
int ch = 0;
while ((ch = getc(fpin)) != EOF)
putc(ch, fpout);
fclose(fpout);
}
fclose(fpin);
}
...

Fix possible resource leak found by static checker

---

3rdparty/libfli/unix/libusb/libfli-usb-sys.c

Present INDI driver does not use FLI kernel module. So I was not able to connect my FLI Filter Wheel CFW-1-8 via usb port.
I supposed the problem was inability to detect DEVICE→devinfo.model.
I modified this file /indi/3rdparty/libfli/unix/libusb/libfli-usb-sys.c to verify the content of devinfo.model. If this descriptor is empty, I provide for completing it. This solution prevents FLI driver crash and reactivates the functions of my CFW. 
[log_17-51-42.txt](https://github.com/indilib/indi/files/3438343/log_17-51-42.txt)

Prevents indi_fli_wheel crash for FLI-CFW-1-8 model.

---

libindi/drivers/focuser/focuslynxbase.cpp
libindi/drivers/focuser/focuslynxbase.h

This fixes an issue with the new Optec ThirdLynx FocusLynx controller (which allows a value in a response to be null be default). It also changes the isResponseOK() to match the behavior of the Optec Gemini (by reading to the END for commands) and adds the new Optec Sagitta focuser device type.

Various FocusLynx fixes / enhancements

---

libindi/drivers/telescope/celestrongps.cpp

Celestron NexStar Evolution mounts do not seem to support retrieval of pier side information. At least with my mount (latest FW), the Celestron GPS driver even warns about that fact upon startup.
The ReadScopeStatus() operation exits if HasPierSide() is FALSE, directly before it would read the position of the motorized focus motor. This PR reverses the order: first read the position of the focus motor, then perform the pier side handling. 
At least here, this fixes the problem: the motor position is reported correctly, thus enabling autofocus workflows.

Celestron Focuser position not update with Evolution mount

---

libindi/libs/indibase/indidome.cpp

For rolloff roofs, the parking state is not initialized. As a result, the INDI client shows neither parked nor unparked as selected. This creates subsequent problems when a user wants to park the roof and gets the result that it is already closed.

Initializing parking mode correctly for rolloff roofs

---

libindi/libs/indibase/indidome.cpp

When parking, the Indi dome controller needs to set the switches correctly such that clients are informed about the parking action.

Set switches correctly when parking dome

---

libindi/libs/indibase/basedevice.cpp
libindi/libs/indibase/indidome.cpp
libindi/libs/indibase/inditelescope.cpp

As per thread at https://www.indilib.org/forum/development/5528-inditelescope-cpp-left-open-files.html I also checked a few other places which had left files open in my system and added the missing fclose calls.

Add missing fclose calls

---

3rdparty/CMakeLists.txt

If it is an aarch64 or ARM64 system, then it will cause the whole 3rd Party build to fail, since it will try to build sbig and it cannot.

Adding check to 3rd Party build to verify this is not an ARM 64 system

---

libindi/libs/indibase/defaultdevice.cpp
libindi/libs/indibase/defaultdevice.h

As discussed in thread at https://www.indilib.org/forum/development/5694-override-focuser-polling-period-control.html it would be useful to have methods to set device specific minimum and maximum polling rates. Some devices don't work with too frequent polling and some need to be polled often enough (at least ScopeDome is such, it resets the serial connection if there isn't traffic for a certain time). I haven't actually tested these functions yet, but they seemed straight forward enough to implement and at least it compiles :)

Add methods to set polling rate limits in DefaultDevice

---

debian/rules

Building indi Debian packages with command:
DEB_BUILD_OPTIONS='parallel=$(nproc --all)' debuild -i -us -uc -b
results in error:
CMake Error: The source directory "/home/indi/dev/astronomy/indi/indi/libindi" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [/usr/share/cdbs/1/class/cmake.mk:75: obj-x86_64-linux-gnu/CMakeCache.txt] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
due to not existing libindi directory. Thus remove it.

Remove not existing (previous) source directory.

---

drivers/focuser/myfocuserpro2.cpp

There seems to have been a small gaffe that TemperatureSettingN array is being accessed by index 1 even though there is only one value in the array. This causes compiler warning and is obviously bad otherwise too, so I wonder why no one noticed before :)
`
/home/pi/src/indi/drivers/focuser/myfocuserpro2.cpp: In member function ‘bool MyFocuserPro2::readTempeartureCoefficient()’:
/home/pi/src/indi/drivers/focuser/myfocuserpro2.cpp:458:30: warning: array subscript 1 is above array bounds of ‘INumber [1]’ [-Warray-bounds]
TemperatureSettingN[1].value = val;
~~~~~~~~~~~~~~~~~~~~~^
/home/pi/src/indi/drivers/focuser/myfocuserpro2.cpp: In member function ‘virtual bool MyFocuserPro2::ISNewNumber(const char*, const char*, double*, char**, int)’: …

Fix out of bounds access in myfocuserpro2.cpp

---

drivers/focuser/focuslynxbase.cpp

The sync capability has disappeared for relative focusers. At least my PDMS focuser accepts the sync command and I assume that all other relative focusers do this as well.

Add sync capability for all Optec focuser types

---

drivers.xml
drivers/telescope/pmc8.cpp
drivers/telescope/pmc8.h
drivers/telescope/pmc8driver.cpp
drivers/telescope/pmc8driver.h

PMC8 driver update to better support Ethernet/WiFi connections, simplify mount communication, and more intelligently determine mount type and associated parameters
- Wrapped all tty_reads in a get_pmc8_response function that performs various associated actions such as error checking, debug output, and compensation for certain errors/events that can occur when communicating over WiFi
- Auto detect mount type from firmware
- Added variable for detected mountType to firmwareInfo so that we can access it without relying on the UI switches
- Changed set_myMount function name to set_mountParameters to be more consistent with its purpose
- Set mount parameters from driver if we can auto-detect mount type, instead of waiting for UI to do it
- Moved mount type guessing code to else loop after we …

PMC8 Driver update

---

drivers/telescope/telescope_simulator.cpp

The meridian flip currently works only for short polling intervals. With this fix the initial move is always big enough so that the next move is eastward and jumps not simply back.
Test case: select a polling interval of 2secs and slew to a position close, but east of the meridian. Wait until the target crosses the meridian so that a meridian flip is issued. Without this fix, the mount makes one step eastward and then jumps immediately back to the original position. With this this fix, the mount makes an entire round.

Bug fix: meridian flip working for longer polling intervals

---

drivers/telescope/telescope_simulator.cpp

PR #1042 fixed the meridian flip behavior of the telescope simulator for long polling periods. Unfortunately, the PR created a regression for short polling intervals, which is fixed with this patch.

meridian flip working for short polling intervals (again)

---

drivers/focuser/dmfc.cpp

When e.g. Reverse motor direction is disabled, that is,
DEBUG   1036.928082 sec : CMD <0X41>
DEBUG   1036.955548 sec : RES <OK_FC:1.2:1:19.7:4000:0:1:0:0:0>
^
|
One cannot enable it, due to
reverseStatus != IUFindOnSwitchIndex(&FocusReverseSP)
check where e.g. reverseStatus := 1, however,
IUFillSwitch(&FocusReverseS[REVERSED_DISABLED], "DISABLED", "Disabled", ISS_ON);
also results in 1.
int IUFindOnSwitchIndex(const ISwitchVectorProperty *svp)
{
int i;
for (i = 0; i < svp->nsp; i++)
if (svp->sp[i].s == ISS_ON)
return i;
return -1;
}
and
IUFillSwitch(&FocusReverseS[REVERSED_ENABLED], "ENABLED", "Enabled", ISS_OFF);
IUFillSwitch(&FocusReverseS[REVERSED_DISABLED], "DISABLED", "Disabled", ISS_ON);
IUFillSwitchVector(&FocusReverseSP, FocusReverseS, 2, m_defaultDevice->getDeviceName(), …

Fix enabling/disabling DMFC properties and remove dead code

---

drivers/focuser/dmfc.cpp
drivers/focuser/dmfc.h

According to DMFC serial command table:
http://pegasusastro.com/wp-content/uploads/2015/01/DMFC-Serial-Command-Table.pdf
the command to select the motortype is: "R:X", where X := 0 is DC and X := 1 is stepper.
In addition, the reverse motor direction is read out as N:0 (normal) or N:1 (reverse),
however, the enum is defined as follows:
enum { REVERSED_ENABLED = 0, REVERSED_DISABLED = 1 }.
So it is vice versa to the enum.
The focuser backslash cannot be activated because the command to
enable it, is issued as "C:0" (Disables compensation).

Fix select motortype, reverse status and enable focuser backslash

---

libs/indibase/dsp/convolution.cpp

Compiler gives an error from incompatible pointer type for ffimem, which expects size_t. Happens to work on 64-bit where types are the same.

Use size_t to fix compilation on 32-bit ARM

---

CMakeLists.txt
cmake_modules/FindIconv.cmake
drivers/auxiliary/skysafari.cpp
drivers/telescope/celestrondriver.h
drivers/telescope/lx200driver.cpp
drivers/video/v4l2driver.h
libs/indibase/connectionplugins/connectiontcp.cpp
libs/indibase/hid_libusb.c
libs/webcam/pwc-ioctl.h
libs/webcam/v4l2_base.cpp

This makes libindi compile on FreeBSD 12.0. It also adds support for webcamd. webcamd is essentially a a port Video 4 Linux to FreeBSD user space. Using a few defines, it is possible to compile the indi support for v4l2 for FreeBSD.
I don't know if it still compiled on earlier FreeBSD versions, but I did not try to maintain backwards compatibility, meaning I haven't tried compiling it on anything other than 12.0.
I tested the v4l2 support by forwarding the client over SSH to my Linux machine running OpenPHD2 and could capture images from the FreeBSD machine.
A build and test run has been performed on Linux and it still seems to work fine.

Freebsd 12.0 compilation fixes and webcamd support

---

drivers/telescope/celestrondriver.cpp

The UTC offset set in the mount was always zero and this messed up the pointing.  This should do a better job of getting the cast from double to char correct.

Update set time so it works correctly with negative UTC offsets

---

CMakeLists.txt

FreeBSD normally doesn't support Linux udev rules. Only install the DBK21 udev rule on linux.

FreeBSD: don't install DBK21 udev rule

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/ccd_simulator.h

Hello Jasem
I added the the hour axis offset to the ccd simulator.
Most of the code is only in effect if the angle (CP,TCP) > 0, with CP: celestial, TCP: HA axis pole.
I derived from the center locations of the simulated images the offset of the hour axis and they are in good agreement. I'm investigating the differences further.
Kind regards, wildi
E.g. I set lamnda to .8 deg and theta to 90. deg (theta denotes the great circle, where the HA axis lies in), results:
King h         :         90.21 degree
King lambda    :       2803.13 arcsec
King lambda    :          0.78 deg

added hour axis offset

---

drivers/filter_wheel/xagyl_wheel.cpp
drivers/filter_wheel/xagyl_wheel.h

This patch set fixes all issues I could find with Jasem's new Xagyl driver, when running against my physical wheel.
Major features:
1. Strict command/response with no timers or tcflush. The device firmware crashes on me when it receives commands out of sequence.
2. Relative commands like Jitter/Offset/etc. are implemented using loops.
3. Device error messages are reported to the user.
4. Device reboot/etc. work correctly and poll the device.
I'm not sure if offset etc. ever worked with the old driver (the device's command set seems to imply they're meant to be used interactively!) but they work now.
My device cannot use the v3+ Xagyl firmware, so I cannot verify that the Pulse Width command works as intended.

Debug/implement new Xagyl driver

---

drivers/filter_wheel/xagyl_wheel.cpp

This bug was introduced after being handled correctly in the middle of
my previous patch.
When issuing a (G)oto command, the device firmware will sometimes return
the message: "ERROR 7 - Magnet weak" after returning the successful
position response.
In this case, the error should be printed and ignored rather than
treated as a failure.

Fix spurious error in new Xagyl driver

---

libs/indibase/indiweatherinterface.cpp
libs/indibase/indiweatherinterface.h

This comes from the discussion at https://github.com/indilib/indi-3rdparty/issues/83
This extracts the check of a parameter (added with addParameter) against
the user defined limits.
IPState checkParameterState(std::string param);
IPState checkParameterState(INumber parameter);
Returns:
- IPS_IDLE:  The given parameter name is not valid.
- IPS_OK:    The given parameter is within the safe zone.
- IPS_BUSY:  The given parameter is in the warning zone.
- IPS_ALERT: The given parameter is in the danger zone.

Weather: adds checkParameterState()

---

drivers/telescope/lx200ap_experimental.cpp

Hello Jasem
I corrected and tested the changes to the PARK3 position. The person who tested it was INDI forum member Spartacus, the person who originally reported the bug.
Besides I added 0.1 degree to park position alt = latitude + .1 I corrected the call of calcParkPosition and added isSimulation() where necessary.
The addition .1 degree is a kind of a minimal fix to guarantee that the mount is more or less at HA = -6 hours. Transforming Alt=latitude, Az=0, 180 deg to HA/Dec coordinate system yields not a defined HA angle. This is the source of the error.
Currently all park positions are defined within Alt/Az coordinate system. Since AP mounts are all equatorials this is introduces an unnecessary intermediate step, namely delegating the calculation of the HA/Dec coordinates to the AP …

AP drivers, undefined park position in HA/Dec coordinate system

---

CMakeLists.txt
drivers/ccd/ccd_simulator.cpp
drivers/ccd/guide_simulator.cpp
drivers/telescope/scopesim_helper.cpp
drivers/telescope/telescope_simulator.cpp
libs/libastro.cpp
libs/libastro.h

The conversion of the JNow position to a J2000 catalogue position for
the GSC catalogue was  not done correctly, only the Precession was
removed, leaving aberration and nutation.
This adds libastro.cpp,.h files which contain converters to and from
J2000 catalogue and apparent positions.  When converting apparent to
J2000 the aberration, nutation and precession are all removed.  These
converters may be useful elsewhere, this isn't the only place
conversion from aparrent to J2000 is needed.

Update CCD and Guide simulators to improve image accuracy

---

drivers/telescope/synscandriver.cpp
drivers/telescope/synscandriver.h

There is a problem with using indi_synscan_telescope driver with Alt/Az mounts (like a Dobsonian Goto Mount). Sometimes the Goto command does not moves exactly where it was asked for. It turns out that the problem occures after issuing some sync operations to refine pointing accuracy. 
The problem is demonstrated in this forum topic: https://indilib.org/forum/mounts/6444-az-synscan-strange-behavior-can-someone-explain-please.html
It has turned out that the problem goes back to the fact that in case of AltAz mount the Goto operation falls back to GotoAltAz by calculating the Alt/Az coordinates from the requested Ra/Dec coordinates.
In the comment it says:
// For Alt/Az mounts, we must issue Goto Alt/Az
But it is not true, at least not for today's hand controller firmware versions.
The hand …

Goto mode selectable for Alt/Az mounts via an UI Switch.

---

drivers/telescope/skywatcherAPIMount.cpp
drivers/telescope/skywatcherAltAzSimple.cpp
indidriver.c

Reissuing PR #1150 (fix for bug #1097), now issuing assert() on debug builds.
Also prevent calling IUUpdateSwitch() with svp==nullprt from drivers/telescope/skywatcherAPIMount.cpp and drivers/telescope/skywatcherAltAzSimple.cpp.
The root cause is still unknown, but it is related to how .indi/*_congif.xml is created when .indi is empty. After one successful driver open/close the config.xml changes so that the error does not occur  anymore.

Fix skywatcher altaz crash

---

drivers/focuser/focus_simulator.cpp
drivers/focuser/focus_simulator.h

Simply added the focus temperature property, in read/write mode.
This allows to perform more testing.

Add the focus temperature property to the focus simulator

---

drivers/video/v4l2driver.cpp

Add Logitech HD C270 USB camera to the v4l2 driver. Set pixel size to 2.8um.

Logitech HD C270 webcam data added to v4l2_ccd driver

---

indidriver.c

While trying to debug a memory problem with my camera driver I found this. This method can return a buffer that is not properly zero-terminated (malloc does not zero memory). I also got rid of compiler warnings regarding strncpy.
Regards, Lars

Make sure buffer is nullterminated

---

drivers/telescope/lx200classic.cpp
drivers/telescope/lx200classic.h

I have implemented Parking for the LX200 classic. The classic does not natively support parking so it is emulated by eventually going to LAND mode to stop tracking.
There is however one thing that is not perfect. When Unparking, the alignment mode needs to be set to its previous value: Polar or AltAz. This state is however not saved. Please advice.

Implement Parking for LX200 classic

---

drivers/telescope/skywatcherAPI.cpp
drivers/telescope/skywatcherAPI.h
drivers/telescope/skywatcherAPIMount.cpp
drivers/telescope/skywatcherAPIMount.h
drivers/telescope/skywatcherAltAzSimple.cpp
drivers/telescope/skywatcherAltAzSimple.h

SkywatcherAPI::TalkWithAxis() changed to use tty_read_section() to read the response for a command. This way both Serial and UDP connection can work. Fix #1158

UDP support for skywatcherAPI

---

drivers/telescope/scopesim_helper.h
drivers/telescope/telescope_simulator.cpp

Still not satisfied with unpark/park of lx200ap driver I studied the process with the mount simulator. 
The current version parks to RA/Dec frame which is rotating for an earth bound observer. The simulator parks now to HA/Dec frame.
I changed the Angle method lst() from private to public. It comes in handy.

parking to HA/Dec frame

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/ccd_simulator.h

Removed E.S. King's calculation since the equivalent infrastructure is available in mount simulator, based on P.T. Wallace.

equivalent quantities are already available in mount simulator

---

drivers/telescope/lx200classic.cpp

In general the LX200 classic needs almost three seconds after the LX200Telescope::isSlewComlpete() until it beeps to indicated that it is done with positioning. In this time interval one can hear the motors still making some microcorrections.
For normal goto's this does not matter that much. Only occasional star traces in the alignment images. But for parking in polar mode it had the negative effect that changing to landmode while the scope was still busy it reinterprets the slew coordinates given in RaDec as land coordinates (AzAlt?) and rapidly slews to a completely different position.
Adding the settling time by making a few iterations through ReadScopeStatus() solves this.
I am not aware of any LX200 classic commands to detect whether the mount things slewing is really done.

LX200 classic fix Park issue in polar mode: Let mount settle (beep) after slew to park is completed

---

drivers/telescope/skywatcherAPIMount.cpp
drivers/telescope/skywatcherAPIMount.h
drivers/telescope/skywatcherAltAzSimple.cpp
drivers/telescope/skywatcherAltAzSimple.h

Moving commands does not work in tracking state, because the command starts slewing the scope, but the next tracking update tick reverses back to target.
Solution: prevent tracking updates during move operation, and update the tracking target to the new position of the scope at the end of moving.
Maybe a better solution for moving (instead of commanding the mount to unlimited slewing) in tracking state would be to periodically adjusting the tracking target, and let the tracking code do the job. But it needs a much bigger reorganization.

Skywatcher altaz move

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/ccd_simulator.h
libs/indibase/indiccd.cpp
libs/indibase/indiccd.h

Currently, the CCD simulator supports focusing only in combination with the Focus Simulator. This change creates the option to attach a real (absolute) focuser and using the CCD simulator so that focusing can be tested during daytime.
**Test Plan**
Create a EKOS profile combining an absolute focuser with the CCD Simulator. Use the Simulator settings of the CCD Simulator to configure the focus position and the maximal focuser position. Using this setup, try different focuser positions and check, whether the stars change their FHWM values.

CCD Simulator focusing

---

drivers/focuser/myfocuserpro2.cpp

According to the [latest documentation I could find](https://sourceforge.net/projects/arduinoascomfocuserpro2diy/files/Documentation/Comms%20Protocol%20v241.txt/download), the "coil power" command needs only one digit and not two as the current INDI driver implementation assumes. This means coil power will never be switched on (only the first digit will be read by the firmware, hence 0).

[myFocuserPro2] Fix coil power command

---

libs/indibase/indiccd.cpp
libs/indibase/indiccd.h

According to https://diffractionlimited.com/help/maximdl/FITS_File_Header_Definitions.htm there is a FITS extension field called FOCUSTEM which contains the focuser temperature so add that to the FITS header if available. This makes it possible to later correlate focus position with temperature for temperature compensation and other analytics purposes.
I also changed the "snooped focus position not valid" value to -1 instead of NaN as long type doesn't have NaN defined and std::numeric_limits<long>::quiet_Nan() returns 0 which is a valid focuser position where as -1 currently isn't.

Add focuser temperature to FITS header

---

drivers/filter_wheel/qhycfw3.cpp

The QHYCFW3 driver tries to issue the VRS command immediately
after connection, but the filter wheel protocol will first
do a full turn or sometimes more than that, and report
the current filter position before that.
The process takes considerable time and always causes a timeout,
but even if the timeout is increased, the initial position
report will desync commands if not read.
This adds a read to expect that initial report with a longer
timeout that lets it do a full initialization under most
conditions.
Tested with a QHYCFW3-S

Fix QHYCFW3 driver handshake

---

spec/libindi.spec

This PR adds a timestamp to the RPM filename for 2 reasons:
1. rpm updates can happen automatically as they key off the version in the file name to notice updates
2. the timestamp can be tied back to the git log

modify libindi.spec to add a timestamp to the RPM package generated

---

libs/indibase/baseclient.cpp
libs/indibase/basedevice.cpp
libs/indibase/indiproperty.cpp
test/core/CMakeLists.txt
test/core/test_property_class.cpp

These fixes were tested to help resolve deadlock and sigsegv issues with KStars.
They are not expected to change any functionality from the specification.
The first commit - the delay after setting the disconnection state - is the most fragile. It embeds an arbitrary duration and requires clients to check the `isConnected()` flag before trying to interact with properties. However, it resolves most if not all deadlock situations with little side-effect (waiting a bit more for disconnection is non-critical).
Note that KStars also requires a few fixes to successfully manage its own shortcomings (part of another pull request).
Although the `INDI::Property` API is very light, those changes include a few unitary tests. Integrity tests are skipped because it is not obvious yet that we do want …

Improve on deadlocks and integrity

---

spec/libindi.spec

F33 and F-rawhide changed the way cmake uses a build directory. By declaring it, we make sure that old distributions and new distributions both build.
Successful builds from this branch are here: https://copr.fedorainfracloud.org/coprs/xsnrg/libindi-bleeding/build/1701422/

spec_updates: set the build directory the new way for F33 and rawhide

---

drivers/telescope/ieqpro.cpp

Hi,
From my forum post 
https://indilib.org/forum/mounts/7902-cem25p-slewing-to-home-position-park-bug-or-missing-feature
I have now added a stop to the "slewing to home position" while mount is parked.
Stephane

1st fix for CEM25p Slewing to home position while parked

---

drivers/focuser/steeldrive2.cpp

The condition should check the minimum number of arguments needed to work properly.
A newly purchased Baader SteelDrive II sends additional information, being backward compatible.

Compatibility fixed - the new firmware has more arguments.

---

CMakeLists.txt
libs/stream/fpsmeter.cpp
libs/stream/fpsmeter.h
libs/stream/streammanager.cpp
libs/stream/streammanager.h

Problems that occurred:
- Subframe - The SER recording has the correct resolution header, but the frame data is saved at the original resolution.
- Signal processing, sending and saving block the possibility of taking a new photo, even though it is done in a separate thread. This is very problematic when recording short videos with a lot of FPS.
What has been done:
- You can adjust the queue size for frames by setting the value in "Maximum Buffer Size (MB)" for non blocking processing.
- You can set a FPS limit for preview. This has no effect on recording.
- After enlarging the preview image, you can record this subframe to a SER file. Very useful for recording planets.

Rework/streammanager - fix recording subframe issue, add processing queue, configurable limits memory/fps

---

libs/stream/fpsmeter.cpp
libs/stream/fpsmeter.h
libs/stream/streammanager.cpp
libs/stream/streammanager.h

Hi!
Waiting for the frame to close its stream is annoying due to the long exposure times.
I moved the counting of time and frame rate from the processing thread to be able to stop the stream.
:)

Fix/streammanager - fix recording long exposure time

---

drivers/focuser/steeldrive2.cpp
drivers/focuser/steeldrive2.h

Implementation of current regulation based on technical documentation.
Now in the Options tab you can set:
- Inverse Current Move, Set the digital potentiometer whiper setting controlling the reference voltage VREF, which is inversly
proportional to the stepper driver current for movement. I ∝ 1/V (uint8 [0-127], DEFAULT = 25, safety limit = 10). This is an expert setting and should only be changed if one wants to use a different stepper motor or lift even heavier loads.
- Inverse Current Hold - The motor current while in holding position (not moving). The CURRENT HOLD value is the digital
potentiometer whiper setting controlling the reference voltage, which is inversly proportional to the stepper driver current in STOPPED state. I ∝1/V (uint8 [0-127], DEFAULT = 100, Safetly limit=10). …

Baader SteelDrive II - feature, Adjustable holding and move current for stepper drive

---

libs/stream/streammanager.cpp
libs/stream/streammanager.h

I found another performance issue that has been around for a long time. I didn't notice him last time.
This simple fix sends the FPS value without blocking threads.
This is important when running the indi server remotely.

fix/performance/streammanager - Do not block the stream thread when sending FPS status, fix frames discarding.

---

drivers/telescope/celestrondriver.cpp

If the observer longitude was less than 1 degree East the code wrongly sent West to the mount because it checked to see if the degrees where > 0 not accounted for the case such as my location which is 000:07:24 East. Changing to >= fixes this issue.

Fix for when observer location is less than 1 degree East

---

libs/indicom.c

`__MACH__` indicates any Mach-based OS, which does not mean only macOS.

Use __APPLE__ for macOS

---

drivers/focuser/smartfocus.cpp
drivers/focuser/smartfocus.h

The MaxPosition property which is now a duplication of a similar property in INDI::Focuser, has been removed.
The SmartFocus unit has a systematic error when moving to a given target position. The MotionError property
was added. This property is used to correct for this systematic error so that the actual target position matches
the desired position.

Update of SmartFocus driver

---

libs/stream/fpsmeter.cpp
libs/stream/fpsmeter.h
libs/stream/streammanager.cpp
libs/stream/streammanager.h

I moved all the "processing" of time to the fpsmeter class. I used [steady_clock](https://en.cppreference.com/w/cpp/chrono/steady_clock) (from the c ++ 11 standard) - monotonic clock that will never be adjusted.
The previous implementation had a counter counting down with an initial value:
`fpssettings.it_interval.tv_sec = 24 * 3600;`
After 24 hours, the application crashed.
I'm getting down to work on the streammanager class. I will keep simplifying the code and optimizing some parts of it.
Once libAsiCamera2Boost is stable, the Indi Library fragments will be ready to be linked.
I am adding myself as a co-author so that I can be found in case of confusion.

Streammanager/chrono - Fix the 24h time limit.

---

CMakeLists.txt
libs/stream/gammalut16.cpp
libs/stream/gammalut16.h
libs/stream/streammanager.cpp
libs/stream/streammanager.h
libs/stream/uniquequeue.h

Hi!
I am request in another cleaned version of the StreamManager class.
Additionally, I replaced the queue logic from std::list with std::queue (UniqueQueue).
std::list always allocates an extra header to create a node when adding an element.
std::queue is optimized not to allocate every time.
GammaLut16 class, you do not need to watch out to free memory, I try not to use new / delete operators, when the standard library offers its proven solutions for this.
I am trying to make the code more error-tolerant without sacrificing performance.
By the way, it would be nice to do d-pointers for common classes. In particular, shared with Indi 3rd Lib.

Streammanager/refactoring - move queue and gamma lut to anothers files

---

indidriver.c

Improving the performance, more stability.
The escapeXML function is quite a big problem, I fixed it so there is no memory leak. Where it was easy to swap, I used the escapeXML2 function which does not allocate and copy.
I've marked 'TODO' where work is critical.
I can see that I will work here longer.

Indidriver/refactoring - fix memory leak, increase performance

---

libs/stream/uniquequeue.h

Fix for "error: unknown type name 'uint'; did you mean 'int'" on MacOS

MacOS Fix - replace non-standard uint type with unsigned

---

drivers/telescope/lx200driver.cpp

The checkLX200Format should really be rewritten to try U2, then U1, and then U. It only does U today.

prevent setting a lower precision for 10micron

---

drivers/telescope/ioptronHC8406.cpp
drivers/telescope/lx200_10micron.cpp
drivers/telescope/lx200_TeenAstro.cpp
drivers/telescope/lx200ap.cpp
drivers/telescope/lx200ap_experimental.cpp
drivers/telescope/lx200ap_gtocp2.cpp
drivers/telescope/lx200basic.cpp
drivers/telescope/lx200driver.cpp
drivers/telescope/lx200driver.h
drivers/telescope/lx200ss2000pc.cpp
drivers/telescope/lx200telescope.cpp
drivers/telescope/rainbow.cpp
libs/indibase/inditelescope.cpp

This allows to set the higher precision on the mount : 
```
#:Gg#
-005*32#
#:U1#
#:Gg#
-005*31:46#
#:U2#
#:Gg#
-005:31:46.2#
```
These values however are not shown yet on the Site Management (seconds are, fractions of seconds are not).
I'll add this later and update this PR.

Fix for #1270, use d m s.f with f being tenths for LX200_GEO_LONGER_FORMAT

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/ccd_simulator.h

To make testing https://invent.kde.org/education/kstars/-/issues/56 easier, add a manual rotation prop to the ccd simulator.

add new ccd rotation prop to ccd simulator

---

libs/indibase/alignment/AlignmentSubsystemForDrivers.cpp
libs/indibase/alignment/AlignmentSubsystemForDrivers.h
test/alignment/alignment_scope.h
test/alignment/test_alignment.cpp

Now adding the helper methods for Alt/Az mounts. I would appreciate if someone with an Alt/Az mount could test this. The test cases I wrote seem to work well, though.
```cpp
/** \brief Adds an alignment point to the model database, usually called from Sync.
* \param[in] actualRA actual Right Ascension in decimal hours
* \param[in] actualDec actual Declination in decimal degrees
* \param[in] mountAlt Altitude where the mount thinks it is in decimal degrees
* \param[in] mountAz Azimuth where the mount thinks it is in decimal degrees
* \return true if the alignment point was added to the database, otherwise false
*
* This will return false if either the alignment point was already added, or if the location
* is not set. Call UpdateLocation to set the current location.
*/
bool …
```

Add new helper methods to the AlignmentSubsystemForDrivers (Alt/Az)

---

drivers/video/v4l2driver.cpp

The trailing colon appears to be part of the actual reported name, so left it in.
https://www.ovt.com/sensors/OV9712-1D
https://www.ovt.com/download/datasets/2876/OV9712_Microsoft_Lifecam_Cinema.pdf

add Microsoft LifeCam Cinema to pixelSizeInfo

---

libs/indibase/property/indiproperty.cpp
libs/indibase/property/indiproperty.h
libs/indibase/property/indiproperty_p.h

Is it possible to add automated tests for OS X?
I think I fixed the weak linking problem.
If the methods are not used (apply / define / save), there will be no reference to functions that are compiled only for drivers.
Additionally, I prepared the class for inheritance.
In some places, strongly typed, it is unnecessarily reduced to the INDI::Property type.
Later I will add another layer as template for IText/INumber/ISwitch/ILight/IBLOB that inherits from INDI::Property.

fix: inline methods that use unlinked functions

---

drivers.xml
drivers/focuser/sestosenso2.cpp
drivers/focuser/sestosenso2.h

While this includes code for editing, saving and apply user presets, it seems there's an issue with the Sesto Senso 2 firmware v1.3 that prevents applying the user presets. So for now I've disabled the apply/save user preset switches until a firmware fix is confirmed. If the fix becomes available the functionality can be enabled by removing the two commented TODO code blocks within SestoSenso2::updateProperties().
The builtin defaults can be applied without issue.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#1262: Primaluce Sesto Senso 2 - user profile / hold current control support](https://issuehunt.io/repos/58881442/issues/1262)
---
</details>

Sesto Senso 2: Motor settings

---

drivers/telescope/lx200_OnStep.cpp

OnStep recently modified the command for manipulating output ports. This pull request is to modify the command.

Fix for issue with manipulating output ports

---

libs/indibase/indicontroller.cpp
libs/indibase/indicontroller.h

Adds the ability to change the device name of the Joystick for the Controller. This will allow other devices not named "Joystick" to be used as a joystick. Defaults to "Joystick" so it is not a breaking change.

Add snoop device to joystick controller

---

CMakeLists.txt
libs/indibase/property/indiproperty.cpp
libs/indibase/property/indiproperty.h
libs/indibase/property/indipropertyview.h
libs/indibase/property/indiwidgettraits.h
libs/indibase/property/indiwidgetview.h

I have decided to split my work as milestones that will be extended.
This pull request includes the creation of decorators for existing IXXXVectorProperty/IXXX structures.
Additionally, I used "#define" for switch-case to avoid confusion when referencing structure fields.
Decorators, hereinafter called views, will enable implementation in C++ in the future.
Decorators to help get rid of direct calls to low-level functions.
Structures from indiapi.h can be projected onto decorators at any time for easy manipulation.
Everything about a given "Widget" in one place.
These classes will be the basis for the further implementation of Qt-Like widgets.

Refactoring - Widget decorators

---

drivers/telescope/synscandriver.cpp

Track mode was read from the properties and send as the track mode to be used to the handset, however since the track mode was periodically read from the handset and updated in the properties. If tracking was off, then the property was always off too ... which prevented tracking to be switched on.
Now the mode is only updated from the handset if we are not already tracking and the track mode has changed.

Tracking can now be switched on/off

---

drivers.xml
drivers/telescope/celestrongps.cpp
drivers/telescope/celestrongps.h

This is my first development work for INDI to address Issue https://github.com/indilib/indi/issues/1329
While I was able to successfully compile locally on two platforms, running from a DEV version of indi alongside the distributed version still eludes me, so I was unable to test locally.
The "IUFillNumber" parameters should be reviewed closely for appropriateness, as I took my best guess there based on the change and the function defintion.

Fix celestrongps guide rate scaling

---

libs/indibase/connectionplugins/connectionserial.cpp

Fix a SEGFAULT when there are no system ports defined.

fix: add null pointer check to serial connect

---

drivers/dome/ddw_dome.cpp
drivers/dome/ddw_dome.h

Poll DDW controller status every 60s if there is no other traffic to keep communication watchdog from triggering and parking the dome. In reference to https://www.indilib.org/forum/general/447-digital-dome-works-does-this-work.html?start=48#66806

Avoid DDW communication watchdog

---

drivers/dome/ddw_dome.cpp
drivers/dome/ddw_dome.h

- restrict to serial connection as the controller only support that to avoid confusion
- if dome is currently moving when a new command to move arrives (from slaving or similar), latch the command and issue the goto after current one completes
- the state of DomeAbsPosNP was set to IPS_OK too early in a few places causing client to think move is over, corrected those so the state stays IPS_BUSY correctly until the move is actually finished

Updates to DDW driver

---

CMakeLists.txt
libs/indibase/indimacros.h
libs/indibase/indiutility.h

Hi,
New header file for C/C++ with no dependencies. It can be added anytime, anywhere.
Here I propose to create macros related to compiler and library support.
I added macros that I created in indi-3rdparty to remove compiler warnings.

Separate useful macros to indimacros.h

---

drivers/dome/ddw_dome.cpp

Avoid spamming shutter state updates if the state hasn't changed.
At first looked like there was some issue with the shutter status value, but it seems to have been just a testing issue that the user didn't open the shutter fully so it reported as indeterminate.

DDW shutter state fix

---

drivers/filter_wheel/ifwoptec.cpp
drivers/focuser/focuslynxbase.cpp
drivers/rotator/gemini.cpp

Hi!
`char * strncat ( char * destination, const char * source, size_t num );`
_num - Maximum number of characters to be appended. size_t is an unsigned integral type._
There is no point in using this function for a known constant string.
It is overused in some places and the target buffer length is not checked.
I added an extra condition when removing the last character so there is no leakage for the empty string.
It is possible that when I replace with new widgets (Property), I will improve part of the implementation.

Fix warnings, use strcpy/strcat for string literal

---

CMakeLists.txt
libs/indibase/basedevice.cpp
libs/indibase/basedevice.h
libs/indibase/defaultdevice.cpp
libs/indibase/defaultdevice.h
libs/indibase/defaultdevice_p.h
libs/indibase/property/indiproperty.cpp
libs/indibase/property/indiproperty.h
libs/indibase/property/indipropertybasic.cpp
libs/indibase/property/indipropertybasic.h
libs/indibase/property/indipropertybasic_p.h
libs/indibase/property/indipropertyblob.cpp
libs/indibase/property/indipropertyblob.h
libs/indibase/property/indipropertyblob_p.h
libs/indibase/property/indipropertylight.cpp
libs/indibase/property/indipropertylight.h
libs/indibase/property/indipropertylight_p.h
libs/indibase/property/indipropertynumber.cpp
libs/indibase/property/indipropertynumber.h
libs/indibase/property/indipropertynumber_p.h
libs/indibase/property/indipropertyswitch.cpp
libs/indibase/property/indipropertyswitch.h
libs/indibase/property/indipropertyswitch_p.h
libs/indibase/property/indipropertytext.cpp
libs/indibase/property/indipropertytext.h
libs/indibase/property/indipropertytext_p.h
libs/indibase/property/indipropertyview.h
libs/indibase/property/indipropertyview_client.cpp
libs/indibase/property/indipropertyview_driver.cpp

Hi!
As previously mentioned (#1361), I am moving to stage two.
My plan:
1. Implementation of PropertyView/WidgetView decorators (collection of used low-level functions)
2. **implementation of widgets (eg PropertyText...) which have methods from PropertyView/WidgetView and additionally inherit from INDI::Property.**
3. implementation of signals / slots for PropertyText...
In brief:
- minor PropertyView / WidgetView fixes
- For example, Merge ISwitch** and ISwitchVectorProperty** to PropertySwitch, see defaultdevice_p.h
- Ability to dynamically change the number of elements, see "ConnectionModeSP"
** ISwitch and ISwitchVectorProperty is the same as WidgetView <ISwitch> PropertyView <ISwitch> with additional method implementation.
I'm going to spend this night on additional testing. If there …

Refactoring - Typed property

---

drivers/ccd/ccd_simulator.cpp

Fix typo in CCD simulator GUI

---

libs/indibase/defaultdevice.cpp
libs/indibase/defaultdevice_p.h

Hi!
Currently, each driver must support the functions:
```c++
void ISGetProperties(const char *dev)
{
mydriver->ISGetProperties(dev);
}
void ISNewSwitch(const char *dev, const char *name, ISState *states, char *names[], int n)
{
mydriver->ISNewSwitch(dev, name, states, names, n);
}
void ISNewText(const char *dev, const char *name, char *texts[], char *names[], int n)
{
mydriver->ISNewText(dev, name, texts, names, n);
}
void ISNewNumber(const char *dev, const char *name, double values[], char *names[], int n)
{
mydriver->ISNewNumber(dev, name, values, names, n);
}
void ISNewBLOB(const char *dev, const char *name, int sizes[], int blobsizes[], char *blobs[],
char *formats[], char *names[], int n)
{
mydriver->ISNewBLOB(dev, name, sizes, blobsizes, blobs, formats, names, n);
}
void …
```

Add global ISGetProperties/ISNewXXX/ISSnoopDevice propagation functions for drivers

---

drivers/focuser/onfocus.h
drivers/rotator/integra.h
drivers/rotator/nightcrawler.h
test/drivers/CMakeLists.txt

Hi!
**Add missing overide specifier** - no comment.
**Remove indiclient from ccd driver test** - The library should not be included with driver side programs.
Causes an incorrect operation ("fill method available only on driver side") when using INDI::PropertyView<> because the priority is the source indipropertyview_client.cpp.

Bugfix - test_ccd_simulator with incorrect library, missing override

---

examples/tutorial_eight/simple_spectrograph.cpp
examples/tutorial_eight/simple_spectrograph.h
examples/tutorial_five/dome.cpp
examples/tutorial_five/dome.h
examples/tutorial_five/raindetector.cpp
examples/tutorial_five/raindetector.h
examples/tutorial_four/simpleskeleton.cpp
examples/tutorial_four/simpleskeleton.h
examples/tutorial_one/simpledevice.cpp
examples/tutorial_one/simpledevice.h
examples/tutorial_seven/simple_telescope_simulator.cpp
examples/tutorial_seven/simple_telescope_simulator.h
examples/tutorial_six/tutorial_client.h
examples/tutorial_three/simpleccd.cpp
examples/tutorial_three/simpleccd.h
examples/tutorial_two/simplescope.cpp
examples/tutorial_two/simplescope.h

Hi!
I have removed the function implementations from the examples.
- ISGetProperties
- ISNewSwitch/Text/Number etc
- ISSnoopDevice
The role was successfully taken over by the implementation in DefaultDevice.
Additionally, I improved the formatting, override specifier and public/private/protected visibility.
I will try to upload the updated documentation today.

Cleaning up the examples - Remove global 'IS' functions.

---

drivers/agent/agent_imager.cpp
drivers/agent/agent_imager.h
drivers/weather/weather_safety_proxy.cpp
libs/lx/Lx.cpp
libs/lx/Lx.h

Minor changes to prevent future refactoring problems.

Bugfix - Use const qualifier for const string

---

libs/indibase/indidome.cpp
libs/indibase/indidome.h

Looking for a solution of this bug (https://github.com/indilib/indi/issues/1364) I improved how Dome drivers deal with the side of the pier where the telescope is in GEM mounts.
Before this change, user can inform to Dome driver which side was the telescope, but if the mount has this information, then it takes from the mount. However, in some circuntances (when telescope was moving) it's not clear what side must be taken.
To make the dome driver behaviour more predictable and clear, now the user can choose from 5 diferent options:
**East** : Dome always positions as if telescope tube was at the east of the pier
**West**:  Dome always positions as if telescope tube was at the west of the pier
**Mount**: Dome positions as if the telescope tube was at the side the mount reports. If the mount …

Improving Dome slave to telescope regarding telescope pier side

---

eventloop.c
eventloop.h
indidevapi.h
libs/indibase/timer/indielapsedtimer.cpp
libs/indibase/timer/indielapsedtimer.h
libs/indibase/timer/inditimer.cpp
libs/indibase/timer/inditimer.h

Hi!
A lot of drivers uses periodic timers. Currently, "addTimer" must be called again.
This causes an imprecise frequency of callback calls.
```
2021-03-17T12:44:25: Driver timer_old_way: 1000.049 ms
2021-03-17T12:44:26: Driver timer_old_way: 2001.132 ms
2021-03-17T12:44:27: Driver timer_old_way: 3002.262 ms
2021-03-17T12:44:28: Driver timer_old_way: 4002.311 ms
2021-03-17T12:44:29: Driver timer_old_way: 5003.407 ms
2021-03-17T12:44:30: Driver timer_old_way: 6004.504 ms
2021-03-17T12:44:31: Driver timer_old_way: 7005.568 ms
```
I implemented the 'addPeriodicTimer' function.
```c
/** Register a new periodic timer function, \e fp, to be called with \e ud as argument after \e ms.
*
* \param ms timer period in milliseconds.
* \param fp a pointer to the callback function.
* \param ud a pointer …
```

Implement real periodic timer.

---

libs/indibase/property/indipropertybasic.cpp
libs/indibase/property/indipropertybasic.h

Hi!
This PR is an extension of INDI::Property family functionality.
Changes:
- Add findWidgetIndexByName method.
- Add reserve / shrink_to_fit - like std::vector.
- Add iterators useful for foreach loops. For example:
```cpp
std::vector<double> oldValues;
for (const auto &it : ControlNP)
oldValues.push_back(it.getValue());
```
- Add find_if - Now you can find for an item in a readable way. For example:
```cpp
auto sw = ControlSP.find_if([&numCtrlCap](const INDI::WidgetSwitch &it) -> bool {
return static_cast<const ASI_CONTROL_CAPS *>(it.getAux())->ControlType == numCtrlCap->ControlType;
});
if (sw != ControlSP.end())
sw->setState(ISS_OFF);
```

Add STL-style iterators to INDI::PropertyBasic

---

CMakeLists.txt
libs/indibase/thread/indisinglethreadpool.cpp
libs/indibase/thread/indisinglethreadpool.h
libs/indibase/thread/indisinglethreadpool_p.h
libs/stream/encoder/rawencoder.cpp
libs/stream/encoder/rawencoder.h
libs/stream/streammanager.cpp
libs/stream/streammanager_p.h

Hi!
On a poor network connection indiserver <-> KStars, the buffer for frames gets full because sending blocks further processing of frames. I found that manually selecting the FPS limit for the preview is inconvenient.
In this PR, I mainly introduce `INDI::SingleThreadPool`.
```cpp
class SingleThreadPool
{
DECLARE_PRIVATE(SingleThreadPool)
public:
SingleThreadPool();
~SingleThreadPool();
public:
/** @brief Reserves a thread and uses it to run functionToRun.
*  A running function can check the 'isAboutToClose' flag and decide whether to end the work and give the thread. */
void start(const std::function<void(const std::atomic_bool &isAboutToClose)> &functionToRun);
/** @brief If thread isn't available at the time of calling, then this function does nothing and returns false.
*  Otherwise, …
```

StreamManager - thread pool for uploadStream

---

libs/indibase/thread/indisinglethreadpool.cpp
libs/indibase/thread/indisinglethreadpool_p.h

Deadlock appeared when function "quit" was called by the same process.
```cpp
static INDI::SingleThreadPool pool;
static void bar(const std::atomic_bool &)
{
pool.quit(); // there is no thread change, no need to wait
fprintf(stderr, "bar!\n");
}
static void foo(const std::atomic_bool &)
{
pool.start(bar); // no thread change, execution priority
}
int main(int, char *[])
{
pool.start(foo); // start
pool.start(foo); // wait and run
pool.quit();     // wait
return 0;
}
```
Output:
```
bar!
bar!
```

Bugfix - INDI::SingleThreadPool - self quit/start deadlock.

---

CMakeLists.txt
drivers.xml
drivers/focuser/teenastro.cpp
drivers/focuser/teenastro.h

This pull request adds support for the TeenAstro focuser. It supports all currently available INDI focuser capabilities except FOCUSER_HAS_BACKLASH, which is not yet implemented in the TeenAstro focuser device firmware. It also supports all commands supported by the serial protocol of the TeenAstro focuser firmware, except named goto locations as INDI already provides those in the driver.
All controls relating to basic location can be found on the Main Controls tab. The remaining controls can be found on the Focuser tab and include motor settings for direction/steps/microsteps/resolution/current, motion settings for speeds/accelerations, as well as device firmware reboot and EEPROM erase.
Confirmed to work on my RasPi4 and TeenAstro focuser, as well as François Desvallées machine.

Added support for TeenAstro focuser 

---

drivers/focuser/teenastro.cpp
drivers/focuser/teenastro.h

This pull request fixes a race condition during automated port scanning. 
Background: TeenAstro main units have two USB ports, one for the mount and one for the focuser. However, the USB connection for the mount forwards focuser commands to the focuser unit via an internal serial connection. This causes the following race condition: if during port scanning, the focuser driver is first to acquire the port which belongs to the mount, it will receive a correct challenge response for the focuser and will claim the port. Hence the mount driver cannot connect to the mount.
The patch is straightforward: after receiving a valid challenge response for the focuser, also send the challenge to detect the mount. Keep the port only if no challenge response for the mount is received within the given …

Fixed TeenAstro mount/focuser race condition during automated port scanning

---

indidriver.c
scripts/indi-core-package-build.sh
scripts/indi-core-package-install.sh
test/celestrondriver/test_celestrondriver.cpp
test/core/test_base64.cpp

MacOS tests finally passed.
Changes:
- bsdtar support
- Refreshed implementation of base64 tests
- Replace nullptr with "" for 'me' variable.
Not all tests respect the global variable "me".
Conversion `const char *` to `std::string`
https://github.com/indilib/indi/blob/a2ebd7db5cc484a6f1383d5dc99a3f85afa211dd/libs/indibase/defaultdevice.cpp#L947-L948
https://github.com/indilib/indi/blob/a2ebd7db5cc484a6f1383d5dc99a3f85afa211dd/libs/indibase/defaultdevice.cpp#L1198-L1201
https://github.com/indilib/indi/blob/a2ebd7db5cc484a6f1383d5dc99a3f85afa211dd/indidriver.c#L47
If 'me' is null then we have an error:
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
```

Fix warnings - MacOS

---

CMakeLists.txt
indiapi.h
indidriver.c
libs/indibase/baseclient.cpp
libs/indibase/baseclientqt.cpp
libs/indibase/baseclientqt.h
libs/indicom.c
libs/indiuserio.c
libs/indiuserio.h
libs/userio.c
libs/userio.h

Hi!
I moved the XML build to a separate file, indiuserio.c.
Changes:
- A secure XML leak (https://github.com/indilib/indi/issues/1412)
- Fewer calls to printf
- Fewer intermediary buffers
- Single function implementations
To minimize the number of buffers, and not to repeat the implementation for streams, sockets etc, I created a 'userio' (User Input-Output). Currently, it is an introduction to further development.
With a userio, you can write a universal code (INDI Style):
```cpp
void IUUserIOTextContext(const userio *io, void *user, const ITextVectorProperty *tvp)
{
for (int i = 0; i < tvp->ntp; i++)
{
IText *tp = &tvp->tp[i];
userio_prints    (io, user, "  <oneText name='");
userio_xml_escape(io, user, tp->name);
userio_prints    (io, user, "'>\n");
userio_prints    (io, user, " …
```

Fix XML Escape

---

indidriver.c
libs/indiuserio.c
libs/indiuserio.h

Original implementation by introducing Userio:
```cpp
void IUSaveConfigTag(FILE *fp, int ctag, const char *dev, int silent)
{
if (!fp)
return;
/* Opening tag */
if (ctag == 0)
{
fprintf(fp, "<INDIDriver>\n");
if (silent != 1)
IDMessage(dev, "[INFO] Saving device configuration...");
}
/* Closing tag */
else
{
fprintf(fp, "</INDIDriver>\n");
if (silent != 1)
IDMessage(dev, "[INFO] Device configuration saved.");
}
}
```

Fix, use IDMessage to send info message.

---

drivers/telescope/pmc8.cpp
drivers/telescope/pmc8.h
drivers/telescope/pmc8driver.cpp
drivers/telescope/pmc8driver.h

Various changes for PMC8 firmware
- Fixes crash due to unexpected version string with v2 firmware
- Changes to be able to fetch model type
- Support for standard serial cable (no longer have to invert DTR)
- Increase stability of wireless connection / auto-reconnect
- Auto-detect if mount is already tracking when first connect
- Other minor changes

PMC8 V2 Firmware update

---

libs/indibase/baseclient.cpp
libs/indibase/baseclient.h

https://github.com/indilib/indi/pull/1430 https://github.com/indilib/indi/issues/1424
The function closing the connection is non-blocking.
Closing descriptors only happens on the thread.
The connection opening and closing functions are synchronized - There is no race.
Waiting for a thread to finish with a timeout is only implemented in the destructor.
@knro Can you check it's ok? (on windows)
I found some additional problems but completely unrelated to sockets.

INDI::BaseClient - Fix sockets deadlock.

---

drivers/video/v4l2driver.cpp

pwc Toucam pro 2 device has no auto exposure control, if stackMode is STACK_NONE and exposure time is out of bounds, the driver crashes.
Tested on my setup (raspberry pi4 / Kernel 5.10.31-V7l+ / Kstars 3.5.2).
Closes #1435

fix null pointer dereference

---

CMakeLists.txt
libs/indibase/basedevice.cpp
libs/indibase/basedevice.h
libs/indibase/defaultdevice.cpp
libs/indibase/property/indiproperties.cpp
libs/indibase/property/indiproperties.h
libs/indibase/property/indiproperties_p.h
libs/indibase/property/indiproperty.cpp
libs/indibase/property/indiproperty.h
libs/indibase/property/indiproperty_p.h
libs/indibase/property/indipropertyview.h
libs/lx/Lx.cpp

Hi!
I have an idea of how to get rid of completely raw pointers in the future.
Linked: https://github.com/indilib/indi/issues/1449
For example:
https://github.com/indilib/indi/blob/07e51770a2d5c1853d931b66656ab3836b0941b5/libs/indibase/basedevice.h#L147-L155
Current usage example:
```cpp
INDI::Property *pointerProperty = device->getProperty("HELLO");
```
If the BaseDevice object is destroyed, the pointer expires.
This problem can be solved already when using the function, e.g. like this:
```cpp
INDI::Property sharedProperty = *device->getProperty("HELLO");
```
The current possibility to solve the problem is not ideal because you have to remember this '_Current solution_'.
`INDI::Property` have a built-in `std::shared_ptr` that enables secure data sharing. A nice solution would be for the …

BaseDevice::getProperty as non-pointer result

---

drivers/telescope/paramount.cpp
drivers/telescope/paramount.h

I believe I've fixed the "Guiding problem", Issue #1456, which was primarily caused by the underlying driver having general problems with polling theSkyX TCP server.
It appears that it was listening to the TCP response for TIMEOUT (3 sec) duration, but not triggering a timeout error, as it successfully read bytes into the buffer.  This was for EVERY action which performed a `tty_read_section` in order to determine a command response.  This was noticeable in the background RaDec coordinate polling, which was returning every 3 seconds, even though configured every 1000ms.
I've updated the commanding and readout to insert a '#' character as the stop character, and subsequently re-coded all the result parsing to take this into account.  It seemed that the regex examination of the result was …

TheSky Server TCP read fixes

---

indiserver.c
tools/evalINDI.c
tools/getINDIproperty.c
tools/setINDIproperty.c

As per the man page (`man 3 gethostbyname`), both `gethostbyname` and `gethostbyaddr` are obsolete functions that should be replaced by `getaddrinfo` and `getnameinfo`.
What's been tested:
I've opened the PR before the "real world scenario test", so I can get a code review in the meanwhile :)

Replace gethostbyname with getaddrinfo

---

drivers/telescope/lx200driver.cpp
drivers/telescope/rainbow.cpp

same as https://github.com/indilib/indi/pull/1478 but al changes are implemented directly into rainbow.cpp.
lx200driver.cpp has been reverted.
fixed:
- location accuracy is now received in arcsec resolution
- date & time & UTC offset are received properly now 
- I renamed a lot of "title" comments because I found them misleading
not fixed:
location in mount gets overwritten when Ekos is started from scratch
Ongoing discussion in: https://indilib.org/forum/ekos/9645-rst-135-location-issue.html

Fixing location accuracy and date&time for RST-135

---

libs/stream/jpegutils.c

In case of YUV420 JPEG format, bitmap data are handled every 16 lines.
But when the image height is not multiple of 16, such as 1920x1080,
it accesses to out of 1080 line and it causes crashes.
So I added "yl < height" to limit the memory access to up to image height for Y plane.
And  I did the same things for U and V plane.

In this commit, a crash at jpeg extraction is fixed.

---

drivers/telescope/skywatcherAPIMount.cpp
libs/stream/jpegutils.c

When connecting to indi_skywatcherAltAzMount from ekos, the driver crashes if telescope and guider info ScopeParametersN are not set because their default values are zero. So I set default values for them and avoid the crash.
The set values have no means. Just avoiding zero is needed

Fix crash on connecting to indi_skywatcherAltAzMount without setting telescope and guider info.

---

drivers/focuser/rainbowRSF.cpp
drivers/focuser/rainbowRSF.h

There were two issues fixed. (1) The doc from Rainbow Astro from which the original driver was written (https://github.com/indilib/indi/files/5457979/RSF_focuser_Protocol_200313_EN.pdf) mis-states the response to the focuser-current-position command, at least on the hardware that I've been testing. Instead of returning  :FPsDDDD# where s is the +/- and DDDD is a 4-digit position, it seems to return something like :FP-06.150# in other words a signed float that's between -8 and 8.0. I've modified the driver to accept either the original format or the floating point one.
Also, probably because of the marginal precision (3 decimal places) which exactly matches the possible position used, I observed off-by-one edge case. I corrected this by accepting off-by-one as "reached destination". …

fix rainbow astro focuser driver

---

libs/indibase/indidome.cpp

Fix OTA azimuth calculation after change from libnova to libastro as EquatorialToHorizontal expects RA in hours and does the *15 internally for libnova, where as previously RA was stored in degrees in dome class and given to libnova ln_get_hrz_from_equ function directly. This caused double conversion for RA and wrong OTA and dome azimuth result.

Fix OTA azimuth calculation for dome slaving

---

libs/indibase/indiccd.cpp
libs/indibase/indiccd.h

This info is used for example by NormalizeScaleGradient-script in PixInsight.
Also adds a bit of precision to some values.

Add object azimuth and altitude to FITS headers

---

drivers/telescope/celestrondriver.cpp
drivers/telescope/celestrondriver.h
drivers/telescope/celestrongps.cpp

Due to a buggy comparison, only the CGX mount was identified as supporting the last align command, not the CGX-L. I fixed the bug and refactored the code to add a feature flag in the low-level driver to check if the mount supports home indexes. The INDI driver then enables the last align command if the mount has home indexes.
PS: I followed the PR guide, and used artistic style to format the code. It introduced a lot of noise, I hope it is not too much a inconvenience.

CGX-L wasn't supported for last align command

---

libs/indibase/baseclient.h

This fixes #1501 . Verified on:
* openSUSE Tumbleweed x86_64
* openSUSE Tumbleweed aarch64
* openSUSE Leap x86_64
* openSUSE Leap aarch64
https://build.opensuse.org/package/show/Application:Astrophotography/libindi

Fix indimacros include path on baseclient.h

---

libs/indibase/baseclient.cpp
libs/indibase/connectionplugins/connectiontcp.cpp

Last time I replaced `gethostbyname` with `getaddrinfo` it seems that I forgot a couple of them.
This PR now concludes the porting from the deprecated `gethostbyname` to `getaddrinfo`.
Code has been compiled on both openSUSE Leap 15.3 and openSUSE Tumbleweed for both x86_64 and aarch64: https://build.opensuse.org/package/show/home:polslinux:teststuff/indi-git
I'll test it with my hardware later on.

Use getaddrinfo instead of gethostbyname (part 2)

---

libs/indibase/baseclient.cpp

Move calling of parent->serverConnected/serverDisconnected out of scope of the socket lock to prevent deadlock if the callback in turn calls socket locked functions (possibly from different thread). This happens with PHD2 for example and causes timeout when connecting to devices.

Move calling of (dis)connect callback out of lock scope

---

drivers/auxiliary/planewave_delta.cpp

The driver for the Planewave Delta-T was not working, it always displayed "Invalid Checksum", even tho the checksum was correct. Changing the type of the checksum from `uint8_t` to `char` fixed everything, and the driver is now working properly

The driver for the Planewave Delta-T was not working

---

drivers/auxiliary/planewave_delta.cpp

As suggested in PR #1515  I changed the type of `chk` from `char` to `int8_t`

Changed the type of chk from char to int8_t as suggested in #1515

---

drivers/auxiliary/99-indi_auxiliary.rules

udevd complained with the following:
```
Invalid value "/bin/sh -c 'test -f /sys/module/usbcore/parameters/usbfs_memory_mb && test $(cat /sys/module/usbcore/parameters/usbfs_memory_mb) -lt 256 && echo 256 > /sys/module/usbcore/parameters/usbfs_memory_mb'" for RUN (char 76: invalid substitution type), ignoring.
```
The command substitution was interpreted as a udev substitution, it can be escaped with a second dollar sign.

Fix invalid substitution in udev rules file

---

developer-build.bash

This script is meant to build INDI inside computer RAM shared memory,
i.e. /dev/shm/indi-build, to reduce wear and tear stress on HDD/SDD.
It also aborts if there is less than 1GB space left on their RAM,
since INDI build directory could take 300MB memory.

Script: Developer build script for UNIX users

---

README.md
developer-build.bash

1. Update the script so it can take a directory other than the default `/dev/shm/indi-build`.
2. Update the script so it will check if the target build directory sits in `/dev/shm` and abort if memory is less than 1Gb.
2. Update the README.md file with instructions and explanations on using the `developer-build.bash` script.
3. Update the README.md file  pre-requisits section with packages in sync with the indilib website.

Developer build script

---

README.md
developer-build.bash

This version of the bash script takes three arguments:
1. `-j` will specify number of `x` jobs in `make -jx`, uses the maximum cores available by default.
2. `-o` will specify path to the target build directory
3. `-f` will skip checking for free memory available
The new `-j` argument is necessary because the `make -j` will freeze virtual machines. To determine the os type, I have used the output from `uname` function. The output starts with `Linux` for GNU/Linux systems, and with `Darwin` for macOS. The script will use `-j1` for other types of systems by default, unless specified otherwise by the user.
The new `-f` argument is necessary because there might be enough free RAM in `docker` containers, but the `/dev/shm/` directory can be limited. Mine was limited to a mere `64MB`. I used …

Script: Developer build update

---

drivers/auxiliary/astrometrydriver.cpp
drivers/weather/weather_safety_proxy.cpp

GCC 11 warns about this with -Wmismatched-dealloc.

Pipes should be closed with pclose(), not fclose()

---

drivers/focuser/focuslynxbase.cpp
drivers/focuser/focuslynxbase.h

The END from devices that did not support HomeOnStart would contain a '\10' or other characters from the last response on the end, causing them to fail the strcmp check for a match with END. When they failed the driver would timeout trying to read the next line (which would never come). Other end checks (~line 1062 as an example) would set the last byte to '\0' so they would pass. In this case the response may be used for processing so instead of setting the last character as a '\0' this checks the first 3 characters as a response key will never start with END .
This was tested on Ubuntu 20.04 with a ThirdLynx and FocusLynx controller. Both controllers were tested with firmware from before and after the addition of HomeOnStart being an option.

Fix FocusLynx GetConfig for focusers without HomeOnStart

---

drivers/focuser/focuslynxbase.cpp
drivers/focuser/focuslynxbase.h

Requesting review for the following changes to the Lynx driver
1. Removes the required sync before move from all Lynx focusers as they are all absolute
2. Use the controllers returned device ID to determine support for Home vs Sync
3. Disable syncing for homing focusers
This should fix #1554 
Please let me know if there are any required or requested changes, I am learning the layout and style for INDI drivers.
So far I have tested this on a FocusLynx hub with a DirectSync and TCF-S 2 as well as a ThirdLynx and a TCF-LSI.

Improve lynx sync and homing behavior

---

drivers/focuser/focuslynxbase.cpp

This fixes an incorrect command doc that listed the step size conversion as 10000 instead of the correct 1000. Because this is informational only (not used within the controller for anything other then display) changing it to the correct value should have no consequences.
The second more major fix is a cleanup of the device types. This makes a few device type names generic, removes unused device types and merges a few duplicates. The exact details are in the commit with additional notes in the code.

More Lynx fixes - Step Size and Devices Types

---

drivers/telescope/rainbow.cpp
drivers/telescope/rainbow.h

Save Alignment Data to mount before sync.
Users can checked the "Save Star Alignment to mount before sync". This would send the star alignment command before every sync operations. Then use the "Mount Model Tool", choose the "Sync" as the platesolve operation. Then at each sync, the alignment data will save to the mount.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#1564: Add Star Alignment option to Rainbow Astro RST-135(E) mount driver](https://issuehunt.io/repos/58881442/issues/1564)
---
</details>

Save Alignment Data to mount before sync

---

drivers/telescope/rainbow.cpp
drivers/telescope/rainbow.h

Pull request #1566 forgot to implement the needed property initialization and updating. This PR fixes that.
Built and tested on RST-135 mount successfully.
Linked to issue #1564.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#1564: Add Star Alignment option to Rainbow Astro RST-135(E) mount driver](https://issuehunt.io/repos/58881442/issues/1564)
---
</details>

Fixing pull request #1566 by adding missing property init and update

---

libs/indibase/indiccd.cpp
libs/indibase/indiccd.h

-  CCD drivers now also snoop for standard epoch positions (indi property EQUATORIAL_COORD)
- CCD drivers: conversion of epoch of day position (indi property EQUATORIAL_EOD_COORD) to standard epoch position (if no standard epoch position given) and calculation of ALT/AZ coordinates moved to addFITSKeywords such that they are updated during fast exposure
- CCD drivers: backup of exposure start time and duration before a new exposure is started in fast exposure mode. (Previously the fits keyword contained the exposure information of the next frame in fast exposure mode.)

CCD drivers: snooping for standard epoch positions and issues with fast exposure mode fixed

---

drivers/auxiliary/pegasus_upb.cpp

Trying to fix https://github.com/indilib/indi/issues/1580 I think there was some kind of copy/paste mistake, but I am not 100% sure. However, I tested this solution on my local install, and the behaviour is now the expected one.

Trying to fix https://github.com/indilib/indi/issues/1580

---

spec/libindi.spec

This fixes a path naming problem 
Branch COPR build: https://copr.fedorainfracloud.org/coprs/xsnrg/libindi-bleeding/build/3140371/

spec_autosetup: switch from setup to autosetup in the spec file

---

drivers/focuser/rainbowRSF.cpp
drivers/focuser/rainbowRSF.h

Increases the tolerance for reaching the focuser position target after waiting for a number of seconds. If the focuser has been busy for 60 seconds then finish no matter what.

Add timeouts to rainbow focuser

---

base64.c
base64.h
test/core/test_base64.cpp

macros like __BYTE_ORDER__ do not really work with gcc  (especially not on PPC64)
With this patch, the execution time increases about 25% on PPC64:
1: [ RUN      ] CORE_BASE64.Test_from64tobits_fast_time
1: [       OK ] CORE_BASE64.Test_from64tobits_fast_time (169 ms)
1: [ RUN      ] CORE_BASE64.Test_from64tobits_fast_with_bug_time
1: [       OK ] CORE_BASE64.Test_from64tobits_fast_with_bug_time (139 ms)
Whereas on amd64 the execution time increases about 10%:
1: [ RUN      ] CORE_BASE64.Test_from64tobits_fast_time
1: [       OK ] CORE_BASE64.Test_from64tobits_fast_time (79 ms)
1: [ RUN      ] CORE_BASE64.Test_from64tobits_fast_with_bug_time
1: [       OK ] CORE_BASE64.Test_from64tobits_fast_with_bug_time (72 ms)
(the second function from64tobits_fast_with_bug() is only needed to compare …

fix for bug 1359

---

drivers/dome/rigel_dome.cpp

When first started rigel dome would crash on unhandled exception thrown
from std::stoi() as it receive "E,1" because drive unit had some garbage
in input buffer.

Send command at start to flush serial line for Pulsar/Rigel dome

---

drivers/telescope/lx200driver.cpp

Add Meade Protocol spec definitions, and apply:
Swap :Sh and :So
Fix :Sd, setCommandXYZ, :SC, :SG, :Sz, :SM, :SN, :SO, :SP, :ST, DEBUGFDEVICE logging
Apply astyle (I hope it automatically uses what's in the repo)
Document a few 10Micron extensions

Add and apply Meade Protocol spec definitions

---

base64.c
drivers/focuser/focuslynxbase.cpp
drivers/focuser/focuslynxbase.h
drivers/rotator/gemini.h
drivers/telescope/celestrondriver.h

<stdint.h> is already being used in some places, as are its
types, e.g. uint8_t, but in some places, non-standard types
like u_int16_t were being mix-and-matched.
Consistently use the <stdint.h> types to fix build on e.g.
musl.
Bug: https://bugs.gentoo.org/829487
Signed-off-by: Sam James <sam@gentoo.org>

Use <stdint.h> for uint* types (fix build on musl)

---

drivers/telescope/lx200ap_v2.cpp
drivers/telescope/lx200apdriver.cpp

Same bug as previous, where negative values were poorly formatted. Seemed to work for A-P cp3 controllers but failed for CP4. This time went through all similar code in lx200apdriver.cpp and corrected all.

Fix similar negative sign bug in AP driver

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/ccd_simulator.h
drivers/video/v4l2driver.cpp
drivers/video/v4l2driver.h
libs/indibase/indiccd.cpp
libs/indibase/indiccd.h

+ CCD_CAPTURE_FORMAT is a list of native formats supported by the camera.
+ CCD_TRANSFER_FORMAT is how the capture format is encoded and uploaded to client. This is handled by INDI::CCD and not the driver. Currently supported formats are FITS and NATIVE. Native indicates that native camera capture format (e.g. jpg) should not be transcoded and transferred to client as-is.

Initial implementation for capture format and encode format

---

README.md

I believe libtheora-dev is also a pre-requisite, I went through compilation yesterday and saw a missing warning about it
PS: now that I look better, it seems libtheora-dev is optional, but also for example rtl-sdr is optional but presented in the pre-requisites. Not sure if it would be better to make a new section for optional dependencies?

Add libtheora-dev to pre-requisites

---

drivers/telescope/lx200telescope.cpp

This is important for software that rely on DRIVER_INTERFACE to detect the driver capability.

Update driver interface when the LX200 support a focuser

---

CMakeLists.txt
drivers.xml
drivers/focuser/esattoarco.cpp
drivers/focuser/esattoarco.h

Add new Driver for Esatto-Arco unit based on the existing Esatto / Sestosenso-Driver

Add Driver for Esatto with Arco (goto, abort, sync, cal)

---

drivers.xml
drivers/telescope/lx200ap_v2.cpp
drivers/telescope/lx200ap_v2.h
drivers/telescope/lx200apdriver.cpp
drivers/telescope/lx200apdriver.h

Modify the AstroPhysics V2 driver so that it uses the "LastParked" API logic to recover when mount connects uninitialized.
Also, cleans up the source file--there was a lot of dead code and obsolete comments inherited from previous driver iterations.

add lastparked logic

---

drivers/telescope/lx200apdriver.cpp

It turns out the get worm position command can return, e.g. 4#, where I expected more characters.
This change allows that 1-digit response.

fix issue reading worm position

---

drivers/telescope/lx200ap_v2.cpp
drivers/telescope/lx200ap_v2.h
drivers/telescope/lx200apdriver.cpp

Per A-P recommendation, the Sync :CMR# command is now used for all Syncs, except for when unparking from a pre-defined park position, where the :CM# command would be used.

Remove user choice for CM/CMR.

---

drivers/auxiliary/pegasus_upb.cpp
drivers/auxiliary/pegasus_upb.h

When indilib compiled with _GLIBCXX_ASSERTIONS indilib_pegasus_upb crashes
This update applies defensive check on the length of lastSensorData and
lastStepperData to avoid asserting against an invalid index.

Ensure defensive check of UBP previous data to fix crash - fixes #1662

---

CMakeLists.txt
indiserver.cpp
integs/IndiClientMock.cpp
integs/IndiClientMock.h
integs/IndiServerController.cpp
integs/IndiServerController.h
integs/TestClientQueries.cpp
integs/TestIndiSetProp.cpp
integs/TestIndiserverSingleDriver.cpp
sharedblob.c

Disable support for shared memory protocol on MACOS by default, since the current mechanism is very limited there (4Mb max) and no evident alternatives seem to be available
It can still be explicitly enabled with -DINDI_SHARED_MEMORY=ON

Disable broken shm support for macos

---

libs/stream/gammalut16.cpp
libs/stream/gammalut16.h

Improve probability that the LUT fits in L1 cache of smaller CPUs (esp. ARM)

Use 8bits samples in the lookup table

---

.github/workflows/docker.yml

This MR fixes an unfortunate array hyphen missing from the cron schedule rebuilding docker containers, as more than one schedule can be set up.

Fix typo in cron schedule for docker build containers.

---

indiserver.cpp

race condition in server code when handling async processing

Fix rare crash when doing base64 encoding

---

indiserver.cpp

This clears INDIPREFIX once, after arguments are processed. 
Driver started from command line will inherit it, others won't.

Ensure INDIPREFIX is cleared only for drivers started from FIFO

---

.github/workflows/default.yml
.github/workflows/macos.yml
.github/workflows/pyindi.yml

This PR trggers GitHub build actions for direct pushes to the `master` branch, and PRs targeting the `master` branch.
It retains manual triggers from the Maintainer on any branch, but prevents other builds.

Build pushes and PRs on master branch only.

---

libs/indibase/indiccd.cpp
libs/indibase/indiccdchip.cpp
libs/indibase/indiccdchip.h

Fix for issue #1719
Also make sure the fits is closed from cfitsio, since closing a file in cfitsio will do some realloc on sealed buffer (this error was hidden by the file size never actually growing)

Don't tell cfitsio about preallocated buffers

---

indiserver.cpp
libs/indibase/sharedblob_parse.cpp

Fix a bug in the way shared blob are handled into client, currently leading to one thread freeing all blobs  (and leaking others).

Fix blob id conflit

---

drivers/focuser/focuslynx.cpp

EKOS uses the DRIVER_INFO to detect INDI devices, therefore also the second focuser needs to provide this info.

DRIVER_INFO also present for F2 focuser so that the device is detected

---

drivers/focuser/deepskydad_af3.cpp

Otherwise the restart of focus procedure may start to early: 
https://invent.kde.org/education/kstars/-/issues/224

DeepSkyDad AF3: Mark as OK after backlash compensation

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/guide_simulator.cpp

To enhance star brightness for higher gains, the exposure time is multiplied by (1+sqrt(gain)) when using star creation with GSC. This improves star detection in the simulators for focusing, alignment and guiding.

Improved star brightness handling for higher gain

---

libs/indibase/abstractbaseclient.cpp
libs/indibase/abstractbaseclient.h
libs/indibase/indibase.h
libs/indibase/watchdeviceproperty.cpp
libs/indibase/watchdeviceproperty.h

This would ensure that references to INDi::BaseDevice are safe in memory when shared among clients.

Shared pointers for INDI::BaseDevice

---

CMakeLists.txt
drivers/agent/agent_imager.cpp
drivers/agent/agent_imager.h
examples/tutorial_six/tutorial_client.cpp
examples/tutorial_six/tutorial_client.h
libs/indibase/abstractbaseclient.cpp
libs/indibase/abstractbaseclient.h
libs/indibase/basedevice.cpp
libs/indibase/basedevice.h
libs/indibase/basedevice_p.h
libs/indibase/defaultdevice.cpp
libs/indibase/defaultdevice.h
libs/indibase/defaultdevice_p.h
libs/indibase/indibase.cpp
libs/indibase/indibase.h
libs/indibase/indimacros.h
libs/indibase/parentdevice.cpp
libs/indibase/parentdevice.h
libs/indibase/parentdevice_p.h
libs/indibase/property/indiproperty.cpp
libs/indibase/property/indiproperty.h
libs/indibase/property/indiproperty_p.h
libs/indibase/property/indipropertyview.h
libs/indibase/watchdeviceproperty.cpp
libs/indibase/watchdeviceproperty.h
test/core/test_property_class.cpp

Referring to https://github.com/indilib/indi/pull/1761. This pull request aims to get rid of the use of raw pointers and use the `shared_ptr` which is in the `INDI::BaseDevice` class to store the data.
Previously:
https://github.com/indilib/indi/blob/6b5ac8408ef021eb832479d4392aa97b66687c78/libs/indibase/abstractbaseclient.h#L128-L131
Now:
https://github.com/indilib/indi/blob/a53ae5bd45aa4c37361e5d50a28cb73b724f54c5/libs/indibase/abstractbaseclient.h#L128-L131
The virtual methods in `INDI::BaseMediator` require a bit of talking.
https://github.com/indilib/indi/blob/6b5ac8408ef021eb832479d4392aa97b66687c78/libs/indibase/indibase.h#L88-L103
This class is no longer needed after the introduction of `watchDevice` and `watchProperty`  https://github.com/indilib/indi/pull/1738
There is also …

Built-in shared pointers for INDI::BaseDevice

---

libs/indidevice/property/indiproperty.cpp
libs/indidevice/property/indiproperty.h

Adding constructors will enable type conversion for Python.
This conversion happened in C++ because classes inherit from each other.
Unfortunately for Python this was not enough.

Swig fix: add conversion constructors

---

libs/indicore/CMakeLists.txt
libs/indicore/indiapi.h.in

A small improvement suggestion to make the header file automatically update based on the version from the main CMakeLists.txt

Automatically take the version from the main CMakeLists.txt

---

libs/indidevice/basedevice.cpp
libs/indidevice/basedevice.h
libs/indidevice/property/indiproperties.h
libs/indidevice/property/indiproperty.cpp
libs/indidevice/property/indiproperty.h
libs/indidevice/property/indipropertybasic.cpp
libs/indidevice/property/indipropertybasic.h
libs/indidevice/property/indipropertyview.h
test/core/test_property_class.cpp

The most important changes:
- Deleted `void *BaseDevice::getRawProperty(const char *name, INDI_PROPERTY_TYPE type) const`
- Deleted `void Property::setProperty(void *p)` and `void *Property::getProperty() const`
- Deleted `void Property::setType(INDI_PROPERTY_TYPE t)`
- Different type returned by `INDI::Property::getXXX()` - `INDI::PropertyXXX` instead of `INDI::PropertyView<XXX>`

Use modern INDI::PropertyXXX in INDI::Property

---

debian/libindi-dev.links
debian/libindi1.install

Solving the problem of building a deb package.

Add libindiclient shared library

---

libs/indicore/indililxml.h

This behavior for macos does not throw an exception.
```cpp
const char *p = nullptr;
try
{
std::cout << std::stod(p) << std::endl;
}
catch(...)
{
std::cout << "error" << std::endl;
}
```

Fix - no exception for std::string construct with nullptr.

---

drivers/telescope/lx200gemini.cpp

This is no longer supported and could cause sdcard corruption.

Disable PEC training for Gemini firmware 6 and above.

---

drivers/filter_wheel/pegasus_indigo.cpp
drivers/focuser/esatto.cpp
drivers/focuser/sestosenso2.cpp
drivers/focuser/sestosenso2.h
drivers/focuser/tcfs.cpp
drivers/telescope/astrotrac.cpp
drivers/video/lx/Lx.cpp
drivers/video/lx/Lx.h
drivers/video/v4l2driver.cpp
drivers/weather/uranusmeteo.cpp
examples/tutorial_four/simpleskeleton.cpp
libs/indiabstractclient/abstractbaseclient.cpp
libs/indibase/defaultdevice.cpp
libs/indibase/defaultdevice.h
libs/indibase/dsp/dspinterface.cpp
libs/indibase/indiweatherinterface.cpp
libs/indibase/stream/streammanager.cpp
libs/indibase/stream/streammanager_p.h
libs/indidevice/basedevice.cpp
libs/indidevice/basedevice.h
libs/indidevice/basedevice_p.h
libs/indidevice/property/indiproperty.cpp
libs/indidevice/property/indiproperty.h
libs/indidevice/property/indipropertybasic.h

Changes are backwards compatible.
It is recommended to refer directly to `INDI::PropertyXXX` and `INDI:BaseDevice` without dereferencing.
The project source codes have been corrected to use the correct form of object reference.

Deprecated use of Property/BaseDevice as pointer.

---

ChangeLog
drivers/auxiliary/arduino_st4.cpp
drivers/auxiliary/astrometrydriver.h
drivers/auxiliary/flip_flat.cpp
drivers/auxiliary/pegasus_upb.cpp
drivers/focuser/myfocuserpro2.cpp
drivers/focuser/primalucacommandset.cpp
drivers/telescope/lx200_16.cpp
drivers/telescope/lx200_OnStep.cpp
drivers/telescope/lx200_TeenAstro.cpp
drivers/telescope/skywatcherAPI.cpp
drivers/telescope/temmadriver.cpp
examples/tutorial_five/raindetector.cpp
examples/tutorial_five/raindetector.h
libs/indibase/connectionplugins/ttybase.h
libs/indibase/indiccd.h
libs/indibase/indicorrelator.h
libs/indibase/indidetector.h
libs/indibase/indidome.h
libs/indibase/indireceiver.h
libs/indibase/indisensorinterface.h
libs/indibase/indispectrograph.h
libs/indibase/inditelescope.h
libs/indibase/stream/streammanager.cpp
libs/indibase/webcam/v4l2_base.cpp
libs/indicore/indicom.h
tools/evalINDI.c

The Debian tool lintian detected some spelling issues that should be fixed with this PR.

fix spelling (detected by lintian)

---

.github/workflows/linux-codestyle.yml
scripts/check-codestyle.sh

Leverage astyle source code indenter and formatter for pre-checking pull request code style by means of github CI's workflow.
If code style is not in agreement with astyle settings listed in script scripts/check-codestyle.sh, prepend string "[STYLE WARNING]" to each line with inproper code style and list the filename as well as message with link to https://github.com/indilib/indi/blob/master/README.md.

Check pull request with astyle for proper code style

---

drivers/telescope/lx200gemini.cpp
drivers/telescope/lx200gemini.h

Add Precision property to correct for refraction, and turn off J2000 format in the gemini.

Add refraction, and turn off J2000

---

indiserver/indiserver.cpp
integs/DriverMock.cpp
integs/DriverMock.h
integs/IndiServerController.cpp
integs/IndiServerController.h
integs/ProcessController.cpp
integs/ProcessController.h
integs/TestIndiserverSingleDriver.cpp
integs/utils.cpp

Force the blob sent to driver to be sent as base64 until proper support is implemented on driver side. (fix [#1822](https://github.com/indilib/indi/issues/1822) )

Downgrade to base64 for snooped blobs

---

drivers/auxiliary/lpm.cpp
libs/alignment/ClientAPIForAlignmentDatabase.cpp
libs/indicore/indicom.c
libs/indicore/indicom.h
libs/indicore/indiuserio.c
libs/indidevice/basedevice.cpp

The INDI and GPSD projects declare a timestamp function with different behavior and return types.
The suggestion is to rename the function in the INDI Core library from `timestamp` to `indi_timestamp`. This is a function also available in C, so the namespace is omitted.
The problem appeared when compiling indi-3rdparty on Raspberry PI.
```
[ 71%] Building CXX object indi-armadillo-platypus/CMakeFiles/indi_seletek_rotator.dir/seletek_rotator.cpp.o
In file included from /usr/include/libgpsmm.h:12,
from /home/pi/Projects/indi-3rdparty/indi-gpsd/gps_driver.cpp:31:
/usr/include/gps.h:2106:20: error: conflicting declaration of C function ‘timestamp_t timestamp()’
extern timestamp_t timestamp(void);
^~~~~~~~~
In file included from /usr/include/libindi/indidriver.h:28,
from …
```

Resolve timestamp name conflict.

---

drivers/telescope/pmc8driver.cpp

Simple fix for PMC8 resuming tracking at Solar rather than previous (usually Sidereal rate) after a slew. This issue was reported also here: https://indilib.org/forum/mounts/12752-tracking-rates-changing-in-indi.html.
The tracking rates were in solar arc seconds, but according to the docs (https://02d3287.netsolhost.com/pmc-eight/PMC_Eight_ProgrammersReferenceManual_Release2_2019_February_01.pdf), PMC8 responds to the get precision tracking rate ("ESGx!") command with sidereal arc seconds.
I have tested this on the iExos-100 and confirm that it now reports the correct tracking rate. I am not sure if there are any (negative) knock-on effects in any INDI internal calculations for guiding pulse duration etc .

Fix PMC8 tracking rate

---

examples/tutorial_five/dome.cpp
examples/tutorial_six/tutorial_client.cpp
libs/indidevice/basedevice.cpp
libs/indidevice/basedevice.h
libs/indidevice/basedevice_p.h
libs/indidevice/property/indiproperty.cpp
libs/indidevice/property/indiproperty.h

New features have been added, completely backwards compatible.
A function useful for writing clients (`BaseClient`), is an alternative to implementing virtual functions `newProperty`/`updateProperty` and creating a series of conditions to get to a specific property.
Of course, this does not mean that you should not use the implementation of virtual functions. It all depends on the implementation and purpose of the client program. If you want to easily read new values or react to their changes, the watchProperty function gives you such a possibility.
Now you can specify when the function is to be executed, you can choose:
- `WATCH_NEW` - when the property appears in the device - equivalent to `newProperty`
- `WATCH_UPDATE` - when the property changes its value - equivalent to …

Simplification of virtual functions - watchProperty with the ability to choose the behavior

---

libs/indixisf/indixisf.cpp

RGB images are stored in planar format not normal.

Save XISF as planar

---

drivers.xml
drivers/auxiliary/CMakeLists.txt
drivers/auxiliary/myDewControllerPro.cpp
drivers/auxiliary/myDewControllerPro.h

Addition of myDewController Driver for R Browns dew controller. https://sourceforge.net/projects/arduinonanodewcontrollerpro/files/myDewControllerPro%20v300%203channel/

Addition of myDewControllerPro driver

---

drivers/telescope/lx200gemini.cpp
drivers/telescope/lx200gemini.h

The old code says to change track mode we set the 130 property to
(131 + mode) value. That is not correct. Instead we should set the
(131 + mode) property with no value. I validated this change by
monitoring the track mode with handset.
Disabling tracking with parking sleep makes sense but seems to
interfere with INDI's state management badly. I did not figure out
what exactly was wrong.
This bug looks relevant: https://bugs.kde.org/show_bug.cgi?id=438995
Inspired by how other LX200 flavors work (AP for example), I disable
tracking by engaging the Terrestrial mode. This is also what user
is suggested to do manually if they want to stop tracking. Validated
in KStars by un/parking, toggling tracking, and slewing in different
permutations.

Re-do Gemini SetTrackMode and SetTrackEnabled

---

drivers/telescope/lx200gemini.cpp
drivers/telescope/lx200gemini.h

This switch was incorrectly disabling comunication with the mount when it was set to be sleeping. The mount is still fully functional when sleeping, it is just not tracking.

Removed the m_isSleeping boolean to fix the "tracking" status in ekos.

---

drivers/auxiliary/mydcp4esp32.cpp
drivers/auxiliary/mydcp4esp32.h

Command buffer was too short for the set CH3 power level to 100 and was getting truncated. Also changed setting ambient offset to be a float instead of an int.

Fix command buffer size. Ambient offset to float

---

drivers/focuser/primalucacommandset.cpp
drivers/focuser/sestosenso2.cpp

This contains 2 fixes:
1. A rather small JSON fix for goOutToFindMaxPos command
2. A more complex UI flow issue
The UI flow issue occured, when you needed to press the "CALIBRATION_NEXT" button for the second time. Apparently clicking the button for a second time de-selected it, causing the call in line 514 of sestosenso2.cpp to return -1:
auto current_switch = CalibrationSP.findOnSwitchIndex();
Which in turn caused a crash in the followup array access.
The proposed fix is to turn the button group into a radiogroup ( ISR_1OFMANY ), which will not de-select the button, thus returning the wanted index.
Calibration worked fine after those 2 fixes on my own SestoSenso2.
Greetings,
Frostregen
PS: SestoSenso2 has the latest firmware: 03.05.01

Fixed SestoSenso2 calibration

---

drivers/telescope/lx200gemini.cpp

Gemini maintains tracking mode across slews and park/unpark.
Ekos seems to expect that mount tracks after slew and unpark in some cases.
A few other mount drivers also explicitly start tracking and some other mounts
do that themselves without nudge from the driver.
Broken Ekos cases for me:
- Disable tracking and park the mount. Start a schedule with unpark option enabled.
It starts and go to focus phase with tracking still disabled.
- Have a couple of sky flats sequences added to the end of a schedule as separate entries.
In most (?) cases those sequences are stuck in the very beginning for an obscure reason.
With this change it works.

Force enable tracking after slew and unpark

---

drivers/focuser/esatto.cpp
drivers/focuser/esatto.h

Before this change Ekos is confused when exactly the focuser completes requested move
and what is the end position. AF Overscan feature is totally unusable. Without overscan
autofocus sort of works, but often ends a bit off the requested position. It also does not
quite return to the start position in case of an error. With this change all above is fine.
Temperature and voltage are ported too.

Esatto: Port state tracking from EsattoArco

---

drivers/focuser/primalucacommandset.cpp

My Esatto unit sends these `ERR: ...` messages along with normal JSON responses.
I don't know the formal protocol. Simple ignoring these messages works fine.

PLL: Treat ERR messages as out-of-bound warnings

---

drivers/auxiliary/pegasus_upb.cpp
drivers/auxiliary/pegasus_upb.h

Followup to 7df8ca6d0de4157268de625c88705c2d96349876. This regressed in 37860f05cb3e4aa55cf7f0d67968b1bcf579e6c3 with the addition of non-standard u_int* types (note the extra underscore).
Bug: https://bugs.gentoo.org/873403

drivers: auxiliary: use stdint.h types (fix musl build)

---

libs/indidevice/basedevice.cpp
libs/indidevice/property/indipropertyblob.cpp
libs/indidevice/property/indipropertyblob.h
libs/indidevice/property/indipropertyblob_p.h

Hi :smile: 
Referring to [libindiclient leaks last blob on driver restart](https://github.com/indilib/indi/issues/1528)
I'm uploading as a draft, I have some new equipment and I will thoroughly test if it's ok.
I wish you a clear sky!

Fix leaks last blob on driver restart

---

libs/indicore/indidevapi.c

Just fix building bug on Windows platform.I hava tested on Msys2(Mingw64)

Fix build bug on Windows

---

drivers/focuser/lacerta_mfoc.cpp
drivers/focuser/lacerta_mfoc_fmc.cpp

Fixes issue #1842. Lacerta MFOC with newer firmware (tested with version 3.1.01, driver `indi_lacerta_mfoc_fmc_focus`) fails to correctly change position when a relative change in the `Focus In` direction is selected.
The problematic code is `(ticks * (dir == FOCUS_INWARD ? -1 : 1))`, where `ticks` is an unsigned and `-1` a signed integer. `-1` gets converted into a huge unsigned value before the multiplication is carried out. Hence, the new desired `targetTicks` value is huge instead of decreased by the desired amount.
The same code can be found in the "old" driver `lacerta_mfoc.cpp`, the patch is applied there as well (untested).

Fix bug in relative positioning of Lacerta MFOC

---

libs/indibase/indiccd.cpp

PixInsight 1.8.9-2 added support for ZSTD compression which is much better than LZ4. So when compression is enabled use ZSTD.

Use ZSTD compression for XISF images when available

---

drivers/focuser/focuslynx.cpp

Due to the underlying device name setting in combination with the fact that FocusLynx has two independent drivers, its name setting does not work. As a result, at least when FocusLynx is initialized through KStars locally, only the first focuser is visible. This could only be avoided if the INDI server is started manually.
With this fix the device names of the two focusers are fix to FocusLynx F1/F2, FocusLynx works with both focusers also in KStars local mode.

Bug fix making both focusers visible

---

libs/indidevice/indibase.h

Referring to the question asked in: https://github.com/indilib/indi/pull/1946
The problem is the white space in `%include` that appeared earlier.
The change was detected based on subsequent commits on the master. Below are screenshots.
I'm submitting a pull request to confirm the issue.

Fix PyIndi build fail - revert code formatting changes

---

drivers/telescope/lx200_pegasus_nyx101.cpp
drivers/telescope/lx200_pegasus_nyx101.h

This moves the tacking logic into the pegasus driver. It now handles king mode, and updates when the mount get's an update from another client like unity mobile. Please review @chrysikos 
Jamie

Handling tracking mode in the pegasus driver, and enable King mode.

---

drivers.xml
drivers/auxiliary/snapcap.cpp
drivers/auxiliary/snapcap.h

This PR adds a new feature to SnapCap driver: TCP connections.
It also fixes an issue related to the Force button.

Snapcap driver with network connections

---

drivers.xml

There is an obsolete driver entry linking Avalon Legacy to Indi_lx200basic. Since there exists a dedicated and fully featured StarGO implementation, this driver is no longer necessary.

Remove obsolete Avalon Legacy driver

---

drivers.xml
drivers/telescope/lx200_TeenAstro.cpp
drivers/telescope/lx200_TeenAstro.h

as of #1977 :
Guide property state sets now to "busy" first, and "idle" when pulse is finished.
Guide property value sets now to 0 when pulse is finished.

TeenAstro pulse behaviour #1977

---

drivers/auxiliary/flip_flat.cpp

… (revised)
If initial IOCTL call fails, try premptively pinging the flip-flat anyway,  so that the handshake can succeed in the case of a virtual serial port (e.g. a pty with no IOCTL).
This shouldn't impact flip-flat driver users with 'real' or clone hardware, but will allow hardware implementations that use a virtual serial port (e.g. in my case, using stepper/relay hats via gpio on a rpi with a small python daemon)

Flip-flat: Allow handshake without ioctl on virtual serial connection

---

drivers/telescope/celestrondriver.cpp

Celestron NexStar mount hand controllers have been introduced with a number of firmware versions over the years.  Starting with the 4.xx NexStar controllers, the minor version is a 2-digit value (currently 4.22).  The older hand controllers (while sporting fewer features) still will talk to INDI since the basic serial communication protocol has not changed.
For these older controllers (v1.2, v1.6, and v2.2), the minor version is a single-digit value.  The current code in `CelestronDriver::get_version()` forces a two-digit minor version, so, for instance, the v2.2 controller is recorded as "2.02".  When the version is checked against device capabilities, `2.02 < 2.2`, so it is incorrectly rejected.
This PR checks the major version of the hand controller, and uses a 2-digit minor version …

Fix version reporting on older Celestron NexStar mounts

---

drivers.xml
drivers/focuser/CMakeLists.txt
drivers/focuser/alluna_tcs2.cpp
drivers/focuser/alluna_tcs2.h

The Telescope-Control-System TCS of ALLUNA Optics, has been designed for the remote control of high-quality telescopes. Alluna Optics  provides only ASCOM drivers and a Windows EXE program to control the  TCS2 Device. The TCS2 can also be controlled by an optional handheld  device. 
The indi driver has been developed by me, Peter Englmaier, and I am  not affiliated with Alluna Optics, but own a small Alluna Telescope  and want to use it with Ekos and other indi software.
With TCS several telescope functions are controlled and monitored:
- Air conditioning of the optical tube and the main mirror i.e., primary/secondary mirror heating and ventilation
- Temperature of ambient (focuser), primary and secondary mirror
- Focusing of the optics
- Control of the optionally available CCD Rotator
- …

Initial release of Alluna TCS2 Driver

---

drivers/focuser/moonlite.cpp
drivers/focuser/moonlite.h

My focusser runs via the Moonlite protocol and stores the temperature compensation coefficient in the flash memory of the focuser. Moonlite protocol supports this by the GC (get coefficient) command.

added support for the :GC# command for Moonlite focuser

---

drivers/auxiliary/pegasus_ppba.cpp
drivers/auxiliary/pegasus_ppba.h

Also fixed two little bugs:
1. stopChar being overridden causing auto search to fail
2. firmware version not being read

Support setting autodew aggression (#1992)

---

drivers/agent/agent_imager.cpp
drivers/agent/agent_imager.h

- Use the get/set method for values
- Avoid enums for a single value
- Update more properties

Migrate Agent Imager driver and avoid using a single ENUM

---

drivers/video/v4l2driver.cpp
drivers/video/v4l2driver.h

I've resolved the exposure issue https://github.com/indilib/indi/issues/1722 with the iOptron iGuider/iPolar cameras. 
Unfortunately fixing this has brought up another problem with excessively slow capture startup times. I've partially resolved this, however there's still a reliability issue where the camera sometimes refuses to start after being stopped, or ignores exposure commands. 
Any suggestions on dealing with this last issue would be appreciated!
The iGuider manual and ASCOM dialogs give the impression that negative values need to be used to set the Absolute Exposure time on the camera. This turns out to be not true. Sniffing the USB bus while changing exposure settings in ASCOM shows the negative values do not get sent to the USB Absolute Exposure Controls. Instead _somewhat_ …

Fix iguider issues

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/guide_simulator.cpp
libs/indibase/indiccd.cpp
libs/indibase/indiccd.h

Setting Scopeinfo property with previous settings: min, max, step, val:
`ScopeInfoNP[FocalLength].fill("FOCAL_LENGTH", "Focal Length (mm)", "%.2f", 10, 10000, 100, 0); ScopeInfoNP[Aperture].fill("APERTURE", "Aperture (mm)", "%.2f", 10, 3000, 100, 0);`
resulted in error:
Error: Invalid range for Aperture (mm) (APERTURE). Valid range is from 10 to 3000. Requested value is 0 [DEBUG] Configuration successfully saved for SCOPE_INFO. Error: Invalid range for Focal Length (mm) (FOCAL_LENGTH). Valid range is from 10 to 10000. Requested value is 0 [DEBUG] Configuration successfully saved for SCOPE_INFO.
because at least one property value is 0 by default however, min values are set to 10mm, so the value cannot be set via the property settings. In addition the step size is decreased to 1mm and enum …

Fix setting ScopeInfo property

---

CMakeLists.txt
libs/indibase/CMakeLists.txt

This MR changes the cmake procedure to
- avoid dependency on system-installed headers, picking from the build folder instead
- prioritise library build to shared, static and object libraries in that order, with the same target name for targets linking to it.

fix(cmake): rework static/shared/object build.

---

drivers/auxiliary/CMakeLists.txt
drivers/dome/CMakeLists.txt

This patch fixes the following build error if system provided httplib is used.
```
[392/503] : && /usr/bin/x86_64-pc-linux-gnu-g++ -march=native -O2 -pipe -D_FORTIFY_SOURCE=2 -O1 -Wa,--noexecstack  -Wall -Wextra -Wno-format-truncation -g -DHAVE_MREMAP -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs  -Wl,-z,nodump -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now drivers/dome/CMakeFiles/indi_dragonlair_dome.dir/dragonlair.cpp.o -o drivers/dome/indi_dragonlair_dome  -Wl,-rpath,/var/tmp/portage/sci-libs/indilib-2.0.7/work/indi-2.0.7_build/libs/indibase:  libs/indibase/libindidriver.so.2.0.7  -lusb-1.0  /usr/lib64/libnova.so  /usr/lib64/libcfitsio.so  /usr/lib64/libz.so  /usr/lib64/libjpeg.so  /usr/lib64/libfftw3.so  -lm  /usr/lib64/libtheoraenc.so  /usr/lib64/libtheoradec.so …
```

Link against httplib if using system libraries

---

drivers/telescope/astrotrac.cpp
drivers/telescope/astrotrac.h

Unguided dithering in Ekos does not work with the Astrotrac 360 when Astrotrac is selected with "Guide via" in the Kstars optical train. List of changes to potentially enable this feature and some possibly bug fixes:
- initialize the GuideRate property (currently not initialized). The new default is set to 0.1x, which is the default rate for the mount according to the author of the X2 plugin. However, users might need to set a longer guide pulse to see movement at the default rate. Note, I'm not sure if the missing initialization is a bug or was omitted by design.
- check if the mount is tracking before issuing a guide pulse
- Added new function to return current tracking rate
- use the current tracking rates rather than custom rates to calculate the mount movement in arcseconds. The …

Enable Astrotrac 360 driver guide pulse

---

drivers/focuser/alluna_tcs2.cpp
drivers/focuser/alluna_tcs2.h

I noticed, that the focuser temperature was not updated in kstars and other clients. The reason was, that the  .apply() method was not called when reading new values from the device.
Other (minor) changes:
- update temperature more often (every 10 seconds instead of once every 5 minutes)
- update fan speed less frequently (very 30 seconds instead of every 3 seconds)
- corrected the copyright message in the header file to reflect my authorship (getting it in sync with the source file).

Bugfix: update focuser temperature in alluna tcs2 driver

---

drivers/telescope/astrotrac.cpp

Moving the mount N/S or E/W via the motion buttons in the indi "Motion Control" tab can inadvertently enable tracking or change the velocity when the motion is stopped, even if the scope is idle, because the MoveNS and MoveWE functions always apply the custom tracking rates, which are set to sidereal by default. Fixed this issue by calling SetTrackEnabled when motion is stopped to reset tracking and tested with my Astrotrac 360 mount.

Astrotrac 360 Driver Motion Control Issue

---

.github/docker/Dockerfile.ubuntu

Hi Jasem,
I noticed that *.deb packages are not being built in GitHub Actions. Probably something changed on Ubuntu and I added the 'debhelper' package.
For everything to work fully, after accepting the pull request, you need to rebuild the docker images used by the build system.
I can also take care of it, and if there are any problems, I can fix the problems directly in the repository.

Add debhelper package - fix package build

---

drivers/telescope/celestrongps.cpp
integs/ConnectionMock.cpp

Referring to https://github.com/indilib/indi/issues/2023
In short:
The `XmlStatus` type is declared differently, but not used - I removed it.
Some variables may be uninitialized. I set the default values.
These are not complicated changes. Now building the project with the flags mentioned in the issue has been successful for me.

Fix Build fails with LTO

---

indiserver/indiserver.cpp

See http://man7.org/linux/man-pages/man7/unix.7.html for relevant information about sockaddr_un:sun_path.

fix(indiserver): avoid strict warning failure on socket struct copy.

---

libs/alignment/CMakeLists.txt
libs/indicore/CMakeLists.txt
libs/indicore/indicom.c
libs/indicore/indidevapi.h
libs/indicore/sharedblob.c
libs/sockets/tcpsocket.cpp

I've ported libindi to pkgsrc and needed these patches to fix the build on NetBSD. Please review and apply them.
Thanks.

NetBSD fixes

---

drivers/focuser/alluna_tcs2.cpp
drivers/focuser/alluna_tcs2.h

I finally figured out how to implement the DustCapInterface. The device controls the robotic dust cap for the main mirror. 
However, it does not close the light path, so light (and even dust) can still reach the sensor.
Without this modification, the driver can control the DustCap, but it is not registered as a DustCap device.

Implement DustCapInterface

---

.github/workflows/linux-pyindi.yml
libs/indidevice/property/indiproperties.h
libs/indidevice/property/indipropertyview.h

After upgrading Ubuntu from 22.04 to 24.04, there is a problem building PyIndi.
The new SWIG version 4.2.0, with the current code, can no longer deduce types correctly. The posted fixes declare types explicitly in templates, and by declaring new ones via `using`.
I also added the `break-system-packages` flag to `pip3` to install the `requirements-test.txt` packages from the `pyindi-client` repository.

Fix build - SWIG 4.2.0

---

drivers/weather/openweathermap.cpp

I noticed that openweathmap reports rain, but it does not show up in the driver panel. The API reports the rain like this:
```
"rain": {
"1h": 0.4
},
```
But, apparently indi driver expects this:
```
"rain": {
"h": 0.4
},
```
I could not figure out, if the format has changed or if this just is not the right data.
Should this PR change be made?

Make openweathermap show rain and snow data

---

libs/indibase/indiccd.h

I found this while reading the class reference docs.

Fix "Al" Typo in indiccd.h

---

drivers/weather/weatherwatcher.cpp
drivers/weather/weatherwatcher.h

This PR adds dynamic (user definable) labels for the weather parameters. While the default ones are still the same as before, a user can now name the labels at will. Even the critical parameters are selectable! This increases the usability and comprehensibility of the driver in a wide range.
The storing procedure is as simple a possible: Enter the desired names in the "Labels" tab, save the configuration in"Options", disconnect and reconnect the driver and the new labels are active. After that one can now check the critical parameters and repeat the above procedure.
There is a small drawback in that not all special characters are allowed. But normally one can find easily a possible transcription.
Example:
Default labels: "Rain", "Temperature", "Wind", "Gust", "Clouds", "Humidity", …

Weather watcher dynamic labels

---

drivers/ccd/ccd_simulator.cpp
drivers/ccd/ccd_simulator.h

Add button for custom resolution to reestablish the possibility to work with the resolution defined in simulator config.

Add button for custom resolution in simulator CCD

---

drivers.xml
drivers/auxiliary/CMakeLists.txt
drivers/auxiliary/waveshare_modbus_relay.cpp
drivers/auxiliary/waveshare_modbus_relay.h
libs/indibase/defaultdevice.cpp
libs/indibase/defaultdevice.h
libs/indibase/indirelayinterface.cpp
libs/modbus/nanomodbus.c
libs/modbus/nanomodbus.h
libs/modbus/platform.h

Add new auxiliary driver for [Waveshare 8 channel Modbus relay](https://www.waveshare.com/modbus-poe-eth-relay.htm)

Waveshare Modbus Relay Driver

---

libs/indidevice/indibase.h
scripts/indi-core-test.sh

I found a similar problem in another repository: https://github.com/pytorch/torchrec/pull/2208/files
Jasem, probably automatic code formatting, inserts space `% include`
```cpp
#ifdef SWIG
// api version for swig
% include "indiapi.h" // wrong!
#endif
```

Fix "Unknown argument: -v" and %include for swig

---

drivers.xml
drivers/telescope/lx200am5.cpp

Hello!
I have an AM5 mount and I noticed that the "INDI Control Panel" does not have the ability to change the buzzer volume. The property was not associated with the setBuzzer function and the command was missing the trailing sign (#).
I checked the command by intercepting the transmission from `StarGazing`.
https://github.com/pawel-soja/ZWO-AM5-Proxy

Feature - ZWO AM5 Buzzer setup

---

drivers.xml
drivers/telescope/ieqpro.cpp
drivers/telescope/ieqpro.h
drivers/telescope/ioptronv3.cpp
drivers/telescope/ioptronv3.h
drivers/telescope/lx200_OnStep.cpp
drivers/telescope/lx200_OnStep.h
drivers/telescope/lx200_OpenAstroTech.cpp
drivers/telescope/lx200_OpenAstroTech.h
drivers/telescope/lx200_pegasus_nyx101.cpp
drivers/telescope/lx200_pegasus_nyx101.h
drivers/telescope/lx200am5.cpp
drivers/telescope/lx200am5.h
drivers/telescope/lx200zeq25.cpp
drivers/telescope/lx200zeq25.h
drivers/telescope/paramount.cpp
drivers/telescope/paramount.h
drivers/telescope/rainbow.cpp
drivers/telescope/rainbow.h
drivers/telescope/telescope_simulator.cpp
drivers/telescope/telescope_simulator.h
libs/indibase/inditelescope.cpp
libs/indibase/inditelescope.h

Since several mounts support Homing controls. This PR moves the responsibility of defining available homing operations to the INDI::Telescope class. Three operations are currently supported and any combination of the three can be set by the concrete class:
* ***Find***: Command mount to search for home axis indexes.
* ***Set***: Accept current position as the new home position.
* ***Go***: Slew to home position.
Both **Find** and **Go** are transient operations so the driver must set the status of HomeSP to OK and must also reset all members of the switch property.

Adding Home support to base class

---

drivers/focuser/myfocuserpro2.cpp

This small change resolves an issue with autofocus using the myFocuserPro2. It simply refreshes the driver's internal position whenever the client requests the isMoving state of the focuser. For full details of what I found please see this forum post. 
https://www.indilib.org/forum/development/14887-myfocuserpro2-driver-fix-for-ekos.html

Fixed myFocuserPro2 Autofocus Issues in Ekos 

---

drivers/telescope/lx200_OnStep.cpp
drivers/telescope/lx200_OnStep.h

OnStepX controllers have a tendency to come up with a serial buffer blocked by garbage. As a result of this handshake with the mount will consistently fail, until that garbage is cleared.
To work around this issue the :GVP# command is sent to the mount twice.

Add workaround for OnStepX failing connection

---

drivers/dome/rigel_dome.cpp

Implements the `Close On Park` and `Open On Unpark` shutter options for the Pulsar (Rigel) dome.

drivers/dome: rigel_dome shutter parking

---

drivers/telescope/lx200_OpenAstroTech.cpp

We have found it convenient to be able to send more Meade commands via the INDI  Control Panel
The following commands are added 
:XSRn.n# :XSDn.n# :XS...  these command do not return values:
WARNING	564.754999 sec	: Executed Meade Command error: -4 :XSD317.2# -> ''
WARNING	530.018348 sec	: Executed Meade Command error: -4 :XSR315.5# -> ''
:Mgnxxxx# these commands do not return values:
WARNING	1022.177341 sec	: Executed Meade Command error: -4 :Mgn0200# -> ''
WARNING	2372.737374 sec	: Executed Meade Command error: -4 :MGN0200# -> ''
:MXxnnnnn# these commands return a character:
WARNING	509.919341 sec	: Executed Meade Command error: -4 :MXd00100# -> '1'
:SCMM/DD/YY# these commands return a string.   Other :Sxxx# commands return a character

enable more Meade commands

---

drivers/auxiliary/snapcap.cpp
drivers/auxiliary/snapcap.h

Deleting code always feels good :)

Update SnapCap driver to use common abort capability from DustCapInterface instead of doing it manually.

---

drivers/auxiliary/cheapodc.cpp
drivers/auxiliary/cheapodc.h
drivers/weather/weathersimulator.cpp
drivers/weather/weathersimulator.h

CheapoDC driver release to add support for firmware 2.x features
- bug fix for Longitude range checking (actually a firmware bug).
- adds support for Weather Device snoop for local temperature/humidity instead of using CheapoDC weather query
- move Latitude/Longitude settings to more common Site Management Tab with Location settings
- Location Snoop enabled by default for Telescope Simulator 
- maintain backwards compatibility with previous firmware version
Weather Simulator
- added Humidity as a weather value so that dew point may be calculated by snooping devices. (ie: CheapoDC)

Upgrade CheapoDC driver for new device firmware features

---

drivers/telescope/scopesim_helper.cpp
drivers/telescope/scopesim_helper.h
drivers/telescope/telescope_simulator.cpp

It was uninitialised value of mcRate
I added initialisation boundary checking and print in case something goes wrong
But seems to be root cause was missing initialization since I saw invalid values reported and after checking in Valgrind it complained at these spots.

Sim crash fix - looks like found root cause

---

drivers/filter_wheel/filter_simulator.h
drivers/focuser/alluna_tcs2.cpp

Hi Jasem
Some recent refactoring work has broken my driver. The DustCap was not working anymore. This PR fixes the issue.
Regards,
Peter

Fix DustCover open/close

---

drivers/auxiliary/joystickdriver.cpp
drivers/auxiliary/joystickdriver.h
libs/indibase/webcam/pwc-ioctl.h
libs/indibase/webcam/v4l2_decode/v4l2_builtin_decoder.cpp
libs/indibase/webcam/v4l2_decode/v4l2_builtin_decoder.h

```
In file included from /home/brad/ports/pobj/indi-2.1.1/indi-2.1.1/libs/indibase/webcam/v4l2_decode/v4l2_builtin_decoder.cpp:60:
/home/brad/ports/pobj/indi-2.1.1/indi-2.1.1/libs/indibase/webcam/v4l2_decode/v4l2_builtin_decoder.h:47:17: error: unknown type name '__u32'
virtual __u32 getFormat();
^
/home/brad/ports/pobj/indi-2.1.1/indi-2.1.1/libs/indibase/webcam/v4l2_decode/v4l2_builtin_decoder.cpp:541:1: error: unknown type name '__u32'
__u32 V4L2_Builtin_Decoder::getFormat()
^
2 errors generated.
```

Use C99 integer types

---

drivers/telescope/lx200am5.cpp
drivers/telescope/lx200am5.h

Hi
I often use a light and heavy tube on the ZWO AM5 mount.
With a heavier load, e.g. Celestron EdgeHD 800, or at low temperatures, the mount stops when aiming at the target or parking. For this reason, I propose a similar feature which is in the "SkyAtlas" program.
The mode enable/disable is now located in `INDI Control Panel -> ZWO AM5 USB -> Motion Control -> Heavy Duty Mode`
AM5 has a special command `:SRl720#` (720x speed) and `:SRl1440#` (1440x speed) which sets the maximum speed limit, regardless of other settings. To read, use the command `:GRl#`, which has also been implemented. The mount remembers the settings, so after a restart of the mount they are remembered.
I also added a fix for the slew rate selection, because the mount has 9 modes, not 10 as declared in the `SLEW_MODES` …

Feature for ZWO AM5 - Heavy Duty Mode and Fix slew rate

---

drivers.xml
drivers/telescope/lx200_10micron.cpp
drivers/telescope/lx200_10micron.h

The flip() function existed but was never called from inditelescope.cpp . This PR should fix that.
I have to wait for clear skies to test the code.

Respond to FLIP command (do not merge yet as code is not tested)

---

drivers/telescope/lx200zeq25.cpp
drivers/telescope/lx200zeq25.h

Lat and Long were formatted as "DD:mm:SS", instead of "DD*mm:SS" as stated in documentation;
RA and Dec were set using the short format, instead of long format. Implemented correct format for both cases, Lat/Long and now correctly set and Gotos are now precise.
Tested on iOptron ieq45 with HC8407.

Bugfix: lx200zeq25 RA, Dec, Lat, Long incorrectly formatted

---

drivers/rotator/wanderer_rotator_base.cpp

Fix(): wanderer rotator - the backlash value was incorrectly read during handshake

---

drivers/dome/scopedome_usb21.cpp
integs/ConnectionMock.cpp
integs/ProcessController.cpp

This PR addresses warnings regarding clang extensions for dynamic arrays. 
`warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]`
I replaced these locations with `std::vector` so we don't have to deal with new/delete.
Some of the `uint8_t` seem like they would be better off as a `std::byte`, but I'll leave that unless someone says otherwise.

Fix build warning - Removing clang-extensions for variable length arrays

---

drivers/telescope/skywatcherAPI.cpp
drivers/telescope/skywatcherAPI.h
drivers/telescope/skywatcherAPIMount.cpp
drivers/telescope/skywatcherAPIMount.h

1. Fixed incorrect tracking behavior - prevent negative trackRate and make sure it stays somewhat positive to prevent status change during tracking and makeing stacking smooth
2. Changed timeout to 300ms instead of 5s to prevent mount running away in case of UDP packet loss
3. Added movement to same direction after goto or for alignment - as synscan app does

Major Fixes in skywatcherAltAz driver:

---

drivers.xml
drivers/io/ipx800v4.cpp
drivers/io/ipx800v4.h

- typo in drivers.xml
- now APIKey field is optionnal
- solving issue on parsing of Analogs Inputs and Digital Outputs

IPX800v4 update

---

drivers/ccd/guide_simulator.cpp
libs/indibase/inditelescope.cpp

Fixed two issues which prevented the guide simulator from working well.
1- The simulator snoops on the telescope simulator, which was not updating its RA coordinates often enough because the RA coordinate (in hours) was using an update threshold (meant for degrees).
2- The calculations for distance from center of a star was made more accurate using sub-pixel distances.

Fix issues affecting guide simulator

---

CMakeLists.txt

Add a cmake option `INDI_BUILD_EXAMPLES` to make it possible to choose whether build the examples.
Its default value is ON for compatibility with the current behaviour.

Add INDI_BUILD_EXAMPLES cmake option

---

drivers/dome/CMakeLists.txt
drivers/weather/CMakeLists.txt

They explicitly use httplib, so make sure to link against it.

Link alpaca drivers with httplib

---

drivers/auxiliary/wanderer_cover.cpp
drivers/auxiliary/wanderer_cover.h

- Updated updateCoverStatus to check isCoverOpen state before changing status.
- Introduced TimerHit method to set the polling timer. This seems required for the capture to trigger while using the scheduler. This seems required to start the capture while using the scheduler.

Refactor WandererCover status update logic and add TimerHit method

---

drivers/auxiliary/CMakeLists.txt
drivers/auxiliary/ups.cpp
drivers/auxiliary/ups.h

This commit introduces a new driver that integrates with Network UPS Tools (NUT) to monitor UPS status and expose it through INDI's weather interface. The driver includes properties for server address, UPS name, connection settings, and simulation controls, along with methods for querying UPS status and updating weather parameters accordingly.

Add INDI UPS Driver using NUT for monitoring UPS status

---

drivers/telescope/lx200_OnStep.cpp
libs/indicore/indicom.c
libs/indicore/indicom.h

There is a serious bug in the LX200 OnStep driver (and all the others which uses the tty_read_section_expanded function).
The tty_read_section_expanded() function (included from libs/indicore/indicom.h) doesn't care with the read buffer size, and sometimes it can overflow and the driver crashes. The problem occurs when garbage gets on the serial line.

fixing buffer overflow in OnStep driver

---

drivers/focuser/celestronauxpacket.cpp

After getting back in to astrophotography I found that my Celestron focuser wasn't working on Linux, both on x86_64 and aarch64.  I could see that there was a buffer overflow error detected and traced it down to this 1 line of code. This looks like the issue raised in [INDI Forum - driver indi celestron sct](https://indilib.org/forum/focusers-filter-wheels/14833-driver-indi-celestron-sct) . The issue doesn't appear on macOS but definitely on my two different Arch (x86_64 is plain old ArchLinux, ODROID N2+ is Manjaro) based systems
I believe the compilers have been optimising away the size of the `rxbuf` and then resulted in the buffer oveflow. 
I've tested this change locally and see that it has resolved the buffer overflow.  I can now connect to the focuser and use it.

fix buffer overflow error found with Celestron focuser

---

docker/README.md
drivers.xml
drivers/weather/CMakeLists.txt
drivers/weather/weatherflow.cpp
drivers/weather/weatherflow.h
libs/indibase/indidome.cpp
test/weather/test_weatherflow.cpp

[WeatherFlow](https://weatherflow.github.io/Tempest/api/) makes some great weather devices. This adds WeatherFlow as a weather driver.

Adding Weather driver for WeatherFlow

---

drivers/auxiliary/CMakeLists.txt
drivers/auxiliary/gemini_flatpanel.cpp
drivers/auxiliary/gemini_flatpanel.h
drivers/auxiliary/gemini_flatpanel_adapters.cpp
drivers/auxiliary/gemini_flatpanel_adapters.h

Complete refactor of the Gemini Flatpanel driver using an adapter pattern to support multiple firmware revisions while maintaining backward compatibility.
- Fully backward compatible with existing Rev1 and Rev2 devices
- Forward compatible for future firmware revisions
- Preserves user configurations and settings
**Architecture**
- Implemented adapter pattern with `GeminiFlatpanelAdapter` base class
- Separated device communication from UI logic
- Clean protocol abstraction for different firmware revisions
**Multi-Device Support** 
- Rev1 adapter: Original firmware (`>X000#` format, `\n` terminator)
- Rev2 adapter: Enhanced firmware (`>X#` format, `#` terminator) 
- Lite adapter: Non-motorized variant with light control only
- Auto-detection with manual override option in Connection tab …

Refactoring GeminiFlatPanel driver to support multiple devices.
